import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
import {execute,initialState,balance} from '../supabase/functions/_shared/economy.mjs';
const {PGlite}=await import(process.env.QA_PGLITE_MODULE||'@electric-sql/pglite');const db=new PGlite(),u=randomUUID(),sid=randomUUID();
try{
 await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id),created_at timestamptz default now());create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('session_id',current_setting('test.sid',true))$$;`);
 for(const name of ['01-account-storage.sql','02-ranking-party.sql'])await db.exec(await readFile(new URL('fixtures/'+name,import.meta.url),'utf8'));
 for(const name of ['06-costume-foundation.sql','07-costume-price-100.sql','08-costume-integration.sql','09-open-costume-shop.sql','10-auction-foundation.sql','11-economy-command-gateway.sql'])await db.exec(await readFile(new URL('../supabase/'+name,import.meta.url),'utf8'));
 await db.query('insert into auth.users values($1)',[u]);await db.query('insert into auth.sessions(id,user_id) values($1,$2)',[sid,u]);await db.query("select set_config('test.uid',$1,false),set_config('test.sid',$2,false)",[u,sid]);await db.query("select public.ringu_account('activate')");
 const snapshot=async nonce=>(await db.query('select public.ringu_economy_snapshot($1) s',[nonce||null])).rows[0].s;
 assert.equal((await snapshot()).ready,false);await db.exec('update ringu_private.auction_release set economy_ready=true');
 let snap=await snapshot();await db.query('select public.ringu_economy_enroll($1,$2,$3)',[u,sid,JSON.stringify(initialState(snap.now))]);snap=await snapshot();assert.equal(snap.enrolled,true);
 const nonce=randomUUID(),fp={command:'daily',args:{}},result=execute(snap.state,'daily',{}, {...snap,random:()=>0,uuid:randomUUID});
 const commit=()=>db.query('select public.ringu_economy_commit($1,$2,$3,$4,$5,$6,$7) r',[u,sid,snap.revision,nonce,JSON.stringify(fp),JSON.stringify(result.state),JSON.stringify({events:result.events})]);
 await db.exec('set role authenticated');await assert.rejects(commit,/permission denied/);await db.exec('reset role');
 await commit();await commit();assert.equal((await snapshot()).state.essence,10);
 await assert.rejects(()=>db.query('select public.ringu_economy_commit($1,$2,$3,$4,$5,$6,$7)',[u,sid,snap.revision,nonce,JSON.stringify({command:'daily',args:{extra:1}}),JSON.stringify(result.state),'{}']),/REQUEST_ID_REUSED/);
 const latest=await snapshot();await assert.rejects(()=>db.query('select public.ringu_save_costume($1,$2,0)',[JSON.stringify({...latest.state,essence:999999}),latest.revision]),/CLIENT_UPDATE_REQUIRED/);
 await assert.rejects(()=>db.query('select public.ringu_economy_commit($1,$2,$3,$4,$5,$6,$7)',[u,sid,snap.revision,randomUUID(),JSON.stringify(fp),JSON.stringify(result.state),'{}']),/SAVE_CONFLICT/);
 await db.exec(await readFile(new URL('../supabase/16-economy-differential-commit.sql',import.meta.url),'utf8'));
 const apply=async state=>{const current=await snapshot();return db.query('select public.ringu_economy_commit($1,$2,$3,$4,$5,$6,$7)',[u,sid,current.revision,randomUUID(),JSON.stringify({command:'sync',args:{}}),JSON.stringify(state),'{}']);};
 const large=structuredClone(latest.state);large.inventory=Array.from({length:2400},(_,i)=>({...balance.gear[0],id:50000+i,auctionUid:randomUUID(),enhance:0,transcend:0}));await apply(large);
 await db.exec('create table item_write_probe(n int);insert into item_write_probe values(0);create function count_item_writes() returns trigger language plpgsql as $$begin update public.item_write_probe set n=n+1;return new;end$$;create trigger probe after insert or update on ringu_private.auction_items for each row execute function count_item_writes();');
 large.gold++;await apply(large);assert.equal((await db.query('select n from item_write_probe')).rows[0].n,0);
 large.inventory[0].enhance=1;await apply(large);assert.equal((await db.query('select n from item_write_probe')).rows[0].n,1);
 large.inventory.shift();await apply(large);assert.equal((await db.query('select n from item_write_probe')).rows[0].n,2);
 console.log('2400-item differential commit: unchanged inventory 0 row writes; one enhancement 1 write; one removal 1 tombstone.');
 // SG1: exact large-sale debit and item tombstones with receipt replay.
 const saleSeed=structuredClone((await snapshot()).state);saleSeed.autoBattle=false;
 saleSeed.inventory=Array.from({length:1137},(_,i)=>({...balance.gear[0],id:Number.MAX_SAFE_INTEGER-i,auctionUid:randomUUID(),enhance:i%16,transcend:0,optionRolls:[1,1],locked:i===0}));
 saleSeed.equipped={'무기':saleSeed.inventory[1].id};await apply(saleSeed);
 const saleSnap=await snapshot(),ids=saleSnap.state.inventory.slice(2).map(it=>it.id),saleNonce=randomUUID();
 const gain=saleSnap.state.inventory.slice(2).reduce((n,it)=>n+balance.sellPrices[it.rarity][it.enhance],0);
 const saleResult=execute(saleSnap.state,'sell',{ids},{...saleSnap,random:()=>.5,uuid:randomUUID});
 const sellCommit=()=>db.query('select public.ringu_economy_commit($1,$2,$3,$4,$5,$6,$7)',[u,sid,saleSnap.revision,saleNonce,JSON.stringify({command:'sell',args:{ids}}),JSON.stringify(saleResult.state),JSON.stringify({events:saleResult.events})]);
 await sellCommit();await sellCommit();const paid=(await snapshot()).state;
 assert.equal(paid.gold,saleSnap.state.gold);assert.deepEqual(paid.inventory,saleSnap.state.inventory.slice(0,2));
 assert.equal((await db.query('select count(*)::int n from ringu_private.auction_items where id=any($1::bigint[]) and owner_id is null',[ids])).rows[0].n,1135);
 console.log('PASS SG1 actual SQL: 1,137-item inventory, 1,135-item atomic dismantle, protected equipment retained, zero gold and every removed item tombstoned.');
 await db.exec('update ringu_private.auction_release set economy_ready=false');await assert.rejects(()=>db.query('select public.ringu_save_costume($1,$2,0)',[JSON.stringify(latest.state),latest.revision]),/CLIENT_UPDATE_REQUIRED/);
 console.log('Economy gateway: private commit permissions, enrollment, receipt replay, fingerprint mismatch, stale CAS and disabled-release legacy-save rejection passed.');
}finally{await db.close();}
