import {test} from 'node:test';import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {randomUUID} from 'node:crypto';
import {execute,initialState,itemAttack,options,balance,stats} from '../supabase/functions/_shared/economy.mjs';
import vm from 'node:vm';
let id=1000000000000000;
const context=(random=()=>.5,now=Date.UTC(2026,8,9))=>({random,now,itemIds:Array.from({length:10},()=>++id),uuid:randomUUID,adminFloor:0,costumePercent:0});
const run=(s,command,args={},random=()=>.5,now)=>execute(s,command,args,context(random,now));
test('current renderer attack parity and unchanged option snapshots',()=>{
 const path=new URL('fixtures/attack-parity.json',import.meta.url);assert.ok(existsSync(path));const snapshot=JSON.parse(readFileSync(path));assert.ok(snapshot.length>500);
 // The item fixtures predate the released enhancement rebalance. Compare the
 // independent production renderer, not stale pre-patch attack expectations.
 const lines=readFileSync(new URL('../index.html',import.meta.url),'utf8').split('\n');
 const source=lines.filter(line=>line.startsWith('function transcendEquipmentRate(')||line.startsWith('function enhanceMultiplier(')||line.startsWith('function enhancedBaseAtk(')).join('\n')+'\n'+lines.filter(line=>line.startsWith('itemAtk=function(')).at(-1);assert.ok(source);
 const lookup=(slot,rarity,index)=>balance.gear.find(it=>it.slot===slot&&it.rarity===rarity&&it.index===index);
 const client=vm.createContext({itemIndex:it=>it.index,itemName:(slot,r,i)=>lookup(slot,r,i)?.name,fixedBaseAtk:(slot,r,i)=>lookup(slot,r,i)?.baseAtk});vm.runInContext(source,client);
 for(const x of snapshot){assert.equal(itemAttack(x.item),client.itemAtk(x.item));assert.deepEqual(options({...x.item,transcend:0}),x.item.transcend?x.options.slice(0,-1):x.options);}
});
test('daily existing midnight claim key, server RNG and one-per-day',()=>{const s=initialState(context().now),result=run(s,'daily',{},()=>0);assert.equal(result.state.essence,10);assert.ok(result.state.dailyRewardClaims['midnight-v2:2026-09-09']);assert.equal(s.essence,0);assert.throws(()=>run(result.state,'daily'),/ALREADY_CLAIMED/);assert.equal(run(s,'daily',{},()=>.999).state.essence,15);});
test('summon spends actual gold, server generates items, rejects injected results',()=>{const s=initialState(context().now);s.gold=2500;const result=run(s,'summon',{group:'weapon',count:10});assert.equal(result.state.gold,0);assert.equal(result.state.inventory.length,10);assert.equal(new Set(result.state.inventory.map(x=>x.id)).size,10);assert.throws(()=>run(s,'summon',{group:'weapon',count:10,rarity:5}),/INVALID_ARGUMENTS/);assert.throws(()=>run(result.state,'summon',{group:'weapon',count:1}),/INSUFFICIENT/);});
test('enhance success/failure/protection and unchanged cost tables',()=>{const s=initialState(context().now);s.gold=10000000;s.downgradeProtect=1;s.inventory=[{...balance.gear[0],id:1,enhance:5,transcend:0,optionRolls:[1,1]}];let r=run(s,'enhance',{id:1,protect:false},()=>0);assert.equal(r.state.inventory[0].enhance,6);assert.equal(r.state.gold,s.gold-balance.enhanceCosts[0][5]);r=run(s,'enhance',{id:1,protect:false},()=>.999);assert.equal(r.state.inventory[0].enhance,4);r=run(s,'enhance',{id:1,protect:true},()=>.999);assert.equal(r.state.inventory[0].enhance,5);assert.equal(r.state.downgradeProtect,0);});
test('only owned unlocked equipment dismantles, failed batch is atomic',()=>{const s=initialState(context().now);s.inventory=[{...balance.gear[0],id:1,enhance:5,locked:true}];const raw=JSON.stringify(s);assert.throws(()=>run(s,'sell',{ids:[1]}),/LOCKED/);assert.equal(JSON.stringify(s),raw);s.inventory[0].locked=false;assert.equal(run(s,'sell',{ids:[1]}).state.gold,0);assert.throws(()=>run(s,'sell',{ids:[1,2]}),/ITEM_NOT_OWNED/);});
test('pets auto-stack and sold max re-enters pool under server commands',()=>{let s=initialState(context().now);s.petStone=10000;s=run(s,'petSummon',{count:10},()=>0).state;assert.equal(s.ownedPets.length,1);assert.equal(s.ownedPets[0].copies,10);s=run(s,'petSummon',{count:10},()=>0).state;assert.equal(s.ownedPets[0].level>=1,true);const max=s.ownedPets.find(p=>p.level===5),before=s.petStone;s=run(s,'petSell',{uid:max.uid}).state;assert.equal(s.petStone,before+12);s=run(s,'petSummon',{count:1},()=>0).state;assert.ok(s.ownedPets.some(p=>p.petId===max.petId));});
test('server stats include owned aura, equipped pet and costume ownership',()=>{const s=initialState(context().now);assert.equal(stats(s).attack,50);s.ownedAuras=[0];assert.equal(stats(s,5).attack,Math.floor(Math.floor(50*(1+balance.auras[0].attackPercent/100))*1.05));});
test('combat uses server seconds; repeated sync cannot mint hits or rewards',()=>{const now=context().now;let s=initialState(now);s=run(s,'sync',{},()=>.5,now).state;let r=run(s,'sync',{},()=>.5,now);assert.equal(r.events.length,0);r=run(s,'sync',{},()=>.5,now+12000);assert.ok(r.events.some(e=>e.type==='kill'));assert.equal(r.state.gold,balance.bossRegions[0].bosses[0].reward);const again=run(r.state,'sync',{},()=>.5,now+12000);assert.equal(again.state.gold,r.state.gold);assert.equal(again.events.length,0);assert.throws(()=>run(s,'sync',{damage:999999}),/INVALID_ARGUMENTS/);});
test('offline reward is server-timed and capped to twelve hours',()=>{const now=context().now,s=initialState(now),a=run(s,'sync',{},()=>.5,now+43200000),b=run(s,'sync',{},()=>.5,now+86400000);assert.equal(a.state.gold,b.state.gold);assert.ok(a.events.some(e=>e.type==='offline'));});
test('short background interval receives the existing offline gold rule without essence rolls',()=>{const now=context().now;const s=run(initialState(now),'background').state;const r=run(s,'sync',{},()=>0,now+12000);assert.ok(r.events.some(e=>e.type==='offline'));assert.equal(r.state.essence,0);assert.equal(r.state.serverBackgroundAt,null);assert.equal(run(r.state,'sync',{},()=>0,now+12000).state.gold,r.state.gold);});
test('best gear uses enhanced attack and preserves equal-power current item',()=>{const s=initialState(context().now);s.inventory=[{...balance.gear[0],id:1,enhance:15},{...balance.gear[1],id:2,enhance:0}];const r=run(s,'equipBest');assert.equal(r.state.equipped['무기'],1);assert.equal(r.state.remodelProfile.equipment[0].a,itemAttack(s.inventory[0]));assert.equal(r.state.remodelProfile.power,stats(r.state).attack);});
test('administrator identity comes only from trusted context, preserves currency floor and level 15',()=>{const s=initialState(context().now);s.playerUid='HBMYG32WHJ';assert.equal(run(s,'sync').state.gold,0);const c=context();c.adminFloor=99999999999;const r=execute(s,'summon',{group:'weapon',count:1},c);assert.equal(r.state.gold,c.adminFloor);assert.equal(r.state.essence,c.adminFloor);assert.equal(r.state.summons.weapon.level,15);assert.ok(r.state.rankingHidden);});
test('mail resolves nested legacy rewards and aura tickets exactly once',()=>{const s=initialState(context().now);s.autoBattle=false;s.mailbox=[{id:'reward-1',reward:{reward:{rewardType:'essence',amount:12},auraDrawTickets:1}}];const r=run(s,'mail',{id:'reward-1'});assert.equal(r.state.essence,12);assert.equal(r.state.auraDrawTickets,1);assert.equal(r.state.mailbox.length,0);assert.throws(()=>run(r.state,'mail',{id:'reward-1'}),/MAIL_NOT_FOUND/);});
test('pet dungeon success consumes entry once; timeout and cancel consume none',()=>{const now=context().now,s=initialState(now);s.autoBattle=false;s.inventory=[{...balance.gear[0],id:1,baseAtk:10000,enhance:0}];s.equipped['무기']=1;let r=run(s,'startDungeon',{type:'pet',stage:1});r=run(r.state,'sync',{},()=>.5,now+1000);assert.equal(r.state.petStone,10);assert.equal(r.state.dungeons.petEntries,1);assert.equal(run(r.state,'sync',{},()=>.5,now+1000).state.petStone,10);const low=initialState(now);low.autoBattle=false;let attempt=run(low,'startDungeon',{type:'pet',stage:1});assert.equal(run(attempt.state,'cancelBattle').state.dungeons.petEntries,2);attempt=run(attempt.state,'sync',{},()=>.5,now+15000);assert.equal(attempt.state.serverBattle,null);assert.equal(attempt.state.dungeons.petEntries,2);assert.equal(attempt.state.petStone,0);assert.throws(()=>execute(low,'startDungeon',{type:'pet',stage:1},{...context(),partyBusy:true}),/BATTLE_IN_PROGRESS/);});

test('PS2 prices at every level, all groups and batch sizes',()=>{
 const prices=[250,250,250,500,500,500,1000,1000,1000,2500,7500,7500,18000,18000,18000];
 for(const group of ['weapon','armor','accessory'])for(let level=1;level<=15;level++)for(const count of [1,5,10,50]){
 const s=initialState(context().now);s.autoBattle=false;s.gold=10000000;s.summons[group]={exp:balance.levelReq[level-1],level};const c=context();c.itemIds=Array.from({length:count},()=>++id);
 const result=execute(s,'summon',{group,count},c);assert.equal(result.state.gold,s.gold-prices[level-1]*count);
 }
});
test('PS2 ten pulls crossing max level only sell subsequent duplicates and persist XP',()=>{
 const s=initialState(context().now);s.autoBattle=false;s.petStone=100;s.petSummonExp=0;const petId=Object.keys(balance.pets)[0];s.ownedPets=[{uid:'held',petId,level:4,copies:11,locked:true}];s.equippedPet='held';
 const r=run(s,'petSummon',{count:10},()=>0);assert.equal(r.state.petStone,9);assert.equal(r.state.petSummonExp,10);assert.equal(r.state.ownedPets[0].copies,12);assert.equal(r.state.ownedPets[0].level,5);assert.equal(r.state.ownedPets[0].locked,true);assert.equal(r.state.equippedPet,'held');assert.equal(r.events[0].results.filter(p=>p.autoSold).length,9);
 const reloaded=run(JSON.parse(JSON.stringify(r.state)),'sync').state;assert.equal(reloaded.petStone,9);assert.equal(reloaded.ownedPets.length,1);
});
