import {chromium} from 'playwright';
import {createServer} from 'node:http';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
import {once} from 'node:events';
import assert from 'node:assert/strict';
const server=createServer(async(req,res)=>{try{const path=new URL(req.url,'http://localhost').pathname;if(path.includes('..'))throw Error();if(path==='/'){res.setHeader('Content-Type','text/html');return res.end('<body style="margin:0;background:#080b0e"><canvas id="stage"></canvas><script src="/linsa-rpg/field-visuals.js"></script></body>');}const file=path.replace('/linsa-rpg/','');res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':'image/webp');res.end(await readFile(new URL('../'+file,import.meta.url)));}catch{res.writeHead(404);res.end();}});
server.listen(0,'127.0.0.1');await once(server,'listening');const browser=await chromium.launch({headless:true});const page=await browser.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400)errors.push(r.url());});
try{await mkdir('test-output/field',{recursive:true});await page.goto('http://127.0.0.1:'+server.address().port);await page.waitForFunction(()=>window.RinguFieldVisual);await page.evaluate(()=>{for(let i=0;i<6;i++)RinguFieldVisual.load(i);});await page.waitForFunction(()=>Array.from({length:36},(_,i)=>RinguFieldVisual.frame(i)).every(Boolean));
const all=await page.evaluate(()=>{const c=stage.getContext('2d');stage.width=390;stage.height=510;return Array.from({length:36},(_,i)=>{const bounds=RinguFieldVisual.draw(c,i,390,510);return {bounds,pixels:stage.toDataURL()};});});assert.equal(new Set(all.map(x=>x.pixels)).size,36);assert.ok(all.every(x=>x.bounds.centerX===195));
for(const width of [320,390,768]){await page.setViewportSize({width,height:600});for(let i=0;i<6;i++){await page.evaluate(({width,i})=>{stage.width=width;stage.height=510;stage.style.width=width+'px';stage.style.height='510px';RinguFieldVisual.draw(stage.getContext('2d'),i*6,width,510);},{width,i});await page.screenshot({path:`test-output/field/region-${i}-${width}.png`});}}
const effect=await page.evaluate(()=>{stage.width=390;stage.height=510;const c=stage.getContext('2d');const snap=(age,crit=false,reduced=false)=>{RinguFieldVisual.draw(c,2,390,510,age,crit,reduced);return stage.toDataURL();};const idle=snap(Infinity),hit=snap(30),crit=snap(30,true),finished=snap(500),reduced=snap(30,false,true);return {hit:hit!==idle,critical:crit!==hit,cleared:finished===idle,reduced:reduced!==idle};});assert.ok(Object.values(effect).every(Boolean));await page.evaluate(()=>RinguFieldVisual.draw(stage.getContext('2d'),2,390,510,30,true));await page.screenshot({path:'test-output/field/critical.png'});assert.deepEqual(errors,[]);await writeFile('test-output/field/report.json',JSON.stringify({monsters:36,viewports:3,effect,errors},null,2));console.log('PASS 36 front-facing encounters, center alignment, normal/critical impact, no stale effects, three viewports');
}finally{await browser.close();server.close();}
