import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const html=readFileSync('index.html','utf8'),lines=html.split('\n');
const controls={sortSelect:{value:'default'},slotFilter:{value:''}};
const ctx={$:id=>controls[id],isItemEquipped:it=>it.id===1,itemAtk:it=>it.atk};
vm.createContext(ctx);vm.runInContext(lines.find(l=>l.startsWith('function sortInventoryItems(')),ctx);
const items=[{id:6,enhance:14,rarity:5,atk:200},{id:5,enhance:14,rarity:5,atk:100},{id:4,enhance:14,rarity:6,atk:1},{id:3,enhance:15,rarity:0,atk:1},{id:2,locked:true,enhance:0,rarity:0,atk:1},{id:1,enhance:0,rarity:0,atk:1}];
assert.deepEqual(ctx.sortInventoryItems([...items]).map(x=>x.id),[1,2,3,4,6,5]);
assert.ok(readFileSync('remodel.js','utf8').includes('f.sortInventoryItems=old.sortInventoryItems;'));
const start=html.indexOf('function inventoryPageRows('),end=html.indexOf('function renderInventory()',start);
vm.runInContext('const INVENTORY_PAGE_SIZE=40;let inventoryPage=2,inventorySort=null;'+html.slice(start,end),ctx);
const all=Array.from({length:100},(_,id)=>({id}));ctx.all=all;
assert.equal(vm.runInContext('inventoryPageRows(all)[0].id',ctx),0);
vm.runInContext('inventoryPage=2',ctx);controls.slotFilter.value='투구';assert.equal(vm.runInContext('inventoryPageRows(all)[0].id',ctx),0);
for(const slot of ['무기','투구','갑옷','바지','신발','반지','귀걸이'])assert.ok(html.includes('<option value="'+slot+'">'+slot+'</option>'));
assert.ok(html.includes("(state.inventory||[]).filter(it=>!slot||it.slot===slot)"));
assert.ok(html.includes("$('slotFilter').onchange=renderInventory;"));
console.log('PASS INV2 priority, final override, filter options, and page reset.');
