/* Original procedural score and layered Foley. Separate buses, no remote audio. */
window.installRinguAudio=function(g){
 const f=g.fn;let ac,sfx,music,master,timer,bar=0,unlocked=false;const voices=new Set(),events=[];
 const volume=(key,fallback)=>Number.isFinite(g.state?.[key])?Math.max(0,Math.min(1,g.state[key])):fallback;
 function mix(){if(!ac)return;for(const [bus,value,fade]of [[sfx,g.state.sfxOn?volume('sfxVolume',.65):0,.03],[music,g.state.bgmOn?volume('bgmVolume',.35):0,.15]]){bus.gain.cancelScheduledValues(ac.currentTime);if(value===0)bus.gain.setValueAtTime(0,ac.currentTime);else bus.gain.setTargetAtTime(value,ac.currentTime,fade)}}
 function init(){if(!unlocked||window.RinguSession.active===false)return;if(!ac){const C=window.AudioContext||window.webkitAudioContext;if(!C)return;ac=new C();master=ac.createDynamicsCompressor();master.threshold.value=-18;master.ratio.value=5;master.connect(ac.destination);sfx=ac.createGain();music=ac.createGain();sfx.connect(master);music.connect(master)}if(ac.state==='suspended')void ac.resume().catch(()=>{});mix();start()}
 function note(freq,dur,gain,delay=0,bus='sfx',type='sine',end=freq){if(!ac||voices.size>96)return;const t=ac.currentTime+delay,o=ac.createOscillator(),v=ac.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);o.frequency.exponentialRampToValueAtTime(Math.max(20,end),t+dur);v.gain.setValueAtTime(.00001,t);v.gain.exponentialRampToValueAtTime(Math.max(.00002,gain),t+Math.min(.035,dur/4));v.gain.exponentialRampToValueAtTime(.00001,t+dur);o.connect(v).connect(bus==='bgm'?music:sfx);voices.add(o);o.onended=()=>{voices.delete(o);o.disconnect();v.disconnect()};o.start(t);o.stop(t+dur+.02)}
 let noiseBuffer;function noise(dur,cutoff,gain,delay=0){if(!ac||voices.size>96)return;if(!noiseBuffer){noiseBuffer=ac.createBuffer(1,ac.sampleRate,ac.sampleRate);const d=noiseBuffer.getChannelData(0);let seed=711;for(let i=0;i<d.length;i++){seed=(Math.imul(seed,1664525)+1013904223)>>>0;d[i]=seed/2147483648-1}}const t=ac.currentTime+delay,n=ac.createBufferSource(),filter=ac.createBiquadFilter(),v=ac.createGain();n.buffer=noiseBuffer;filter.type='bandpass';filter.frequency.value=cutoff;filter.Q.value=.7;v.gain.setValueAtTime(gain,t);v.gain.exponentialRampToValueAtTime(.00001,t+dur);n.connect(filter).connect(v).connect(sfx);voices.add(n);n.onended=()=>{voices.delete(n);n.disconnect();filter.disconnect();v.disconnect()};n.start(t);n.stop(t+dur)}
 function effect(kind,value=0){if(window.RinguSession.active===false)return;init();if(!ac||!g.state.sfxOn||document.hidden)return;events.push(kind);if(events.length>40)events.shift();
  if(kind==='reveal-charge'){const dur=value>=5?3:value===4?2.1:1.2;note(65.4,dur,.07,0,'sfx','sine',196);for(let i=0;i<(value>=5?12:6);i++){note(196*2**(i/12),.32,.022,i*(dur/14),'sfx','triangle');}noise(.8,500,.04);}
  else if(kind==='reveal-impact'){note(65.4,.95,.13,0,'sfx','sine',32);noise(.45,1600,.07);const root=value>=5?261.63:value===4?220:196;[1,1.25,1.5,2,2.5,3].slice(0,value>=5?6:value===4?5:4).forEach((r,i)=>{note(root*r,1.5,.035,i*.065);note(root*r*2,.85,.008,.12+i*.09);});}
  else if(kind==='hit'||kind==='critical'){noise(.13,1900,.14);note(125,.14,.13,0,'sfx','triangle',52);if(kind==='critical'){noise(.22,4200,.15);note(940,.3,.035,.04);note(1410,.22,.025,.07)}}
  else if(kind==='forge'){noise(.17,2700,.22);[620,1033,1671].forEach((n,i)=>note(n,.45,.035,.015*i));noise(.18,2500,.18,.24)}
  else if(kind==='success'||kind==='reward'||kind==='draw'){const root=kind==='draw'&&value>=4?392:330;[1,1.25,1.5,2,2.5].forEach((r,i)=>{note(root*r,.65,.045,i*.10);note(root*r*2,.26,.008,i*.10)})}
  else if(kind==='failure'){note(196,.24,.07);note(155.56,.45,.055,.18);noise(.2,350,.06,.08)}
  else if(kind==='box'){noise(.14,650,.2);noise(.09,2300,.08,.14);note(880,.45,.035,.2);note(1320,.4,.02,.29)}
  else if(kind==='equip'){noise(.065,3200,.1);note(740,.16,.028,.03)}
  else if(kind==='purchase'){[880,1174,1568].forEach((n,i)=>note(n,.24,.025,i*.05))}
  else if(kind==='swing'){noise(.19,1100,.12)}
  else{note(620,.055,.017,0,'sfx','sine',430)}
 }
 function score(){if(!ac||document.hidden||!g.state.bgmOn)return;const region=Math.max(0,Math.min(5,g.state.regionIndex||0)),roots=[146.83,130.81,164.81,110,196,98],root=roots[region]*[1,.8,.667,.9][bar%4],melodies=[[0,4,7,11,7,4,2,7],[0,3,7,10,7,3,2,5],[12,7,11,4,7,2,4,0],[0,0,7,3,0,10,7,3],[7,11,14,12,11,7,4,2],[0,1,7,3,1,10,7,0]],line=melodies[region];note(root/2,4.8,.085,0,'bgm');[1,1.25,1.5].forEach((r,i)=>note(root*r,4.7,.018,i*.05,'bgm'));
  line.forEach((semitone,i)=>{const n=root*2**(semitone/12);note(n*2,1.25,.028,i*.6,'bgm','triangle');note(n*4,.62,.007,i*.6,'bgm');if(region===3||region===5)note(65,.16,.06,i*.6,'bgm','sine',32)});bar++
 }
 function start(){if(!ac||timer||!g.state.bgmOn||document.hidden||window.RinguSession.active===false)return;score();timer=setInterval(score,4800)}
 function stop(){clearInterval(timer);timer=null;if(music&&ac)music.gain.setTargetAtTime(0,ac.currentTime,.05)}
 f.initAudio=init;f.startBgm=start;f.stopBgm=stop;
 f.playHitSound=crit=>effect(crit?'critical':'hit');f.playDefeatSound=()=>effect('reward');f.playForgeSound=()=>effect('forge');f.playDrawSound=r=>effect('draw',r);f.playBoxOpenSound=()=>effect('box');f.playMythicBoom=()=>effect('draw',6);
 f.toggleSfx=()=>{g.state.sfxOn=!g.state.sfxOn;init();mix();f.renderAudioSettings();f.queueSave()};f.toggleBgm=()=>{g.state.bgmOn=!g.state.bgmOn;init();if(!g.state.bgmOn)stop();mix();f.renderAudioSettings();f.queueSave()};
 const render=f.renderAudioSettings;f.renderAudioSettings=()=>{render();const modal=document.querySelector('#settingsModal .modal');if(!modal)return;if(!document.getElementById('rmAudioMixer')){const section=document.createElement('section');section.id='rmAudioMixer';section.innerHTML='<h4>음향 믹서</h4>'+[['sfxVolume','효과음'],['bgmVolume','배경음']].map(([key,label])=>'<label>'+label+' <output id="'+key+'Value"></output><input aria-label="'+label+' 볼륨" data-volume="'+key+'" type="range" min="0" max="100"></label>').join('')+'<button type="button" id="rmSoundTest">타격 / 치명타 / 보상음 들어보기</button>';modal.append(section);section.querySelectorAll('input').forEach(input=>input.oninput=()=>{g.state[input.dataset.volume]=Number(input.value)/100;init();mix();f.renderAudioSettings();f.queueSave()});document.getElementById('rmSoundTest').onclick=()=>{effect('hit');setTimeout(()=>effect('critical'),350);setTimeout(()=>effect('reward'),850)}}for(const [key,def]of [['sfxVolume',.65],['bgmVolume',.35]]){const n=Math.round(volume(key,def)*100);document.querySelector('[data-volume="'+key+'"]').value=n;document.getElementById(key+'Value').textContent=n+'%'}};
 const unlock=()=>{unlocked=true;init()};window.addEventListener('pointerdown',unlock,{once:true});window.addEventListener('keydown',unlock,{once:true});document.addEventListener('click',e=>{if(e.target.closest('button'))effect('click')});document.addEventListener('visibilitychange',()=>{if(document.hidden){stop();void ac?.suspend()}else if(unlocked)init()});window.RinguSession.onEnded?.(()=>{stop();void ac?.suspend()});
 window.RinguAudio={effect,mix,get diagnostics(){return{context:ac?.state,time:ac?.currentTime,voices:voices.size,events:[...events],sfxGain:sfx?.gain.value,musicGain:music?.gain.value}}};
};
(()=>{const s=document.createElement('script');s.src='/linsa-rpg/safe-patches.js?v=20260909-reveal-10';s.async=true;document.head.append(s)})();
(()=>{const s=document.createElement('script');s.src='/linsa-rpg/visual-polish-v3.js?v=20260909-2';s.async=true;s.onload=()=>{const w=document.createElement('script');w.src='/linsa-rpg/weapon-pose-fix-v4.js?v=20260909-grip-5';w.async=true;document.head.append(w)};document.head.append(s)})();
