/* DW2: server-selected daily wheel and receipt-backed mail box reveals. */
(()=>{'use strict';
 const prizes=[['전설 장비 상자','1개','0.5%','#b98127'],['에픽 장비 상자','1개','2.5%','#633c87'],['하락방지권','1개','12%','#355980'],['초월석','2개','15%','#267d85'],['펫스톤','3개','15%','#716148'],['정수','5개','20%','#773b8e'],['골드','1,000,000','30%','#9a7432'],['꽝','보상 없음','4.9%','#293544'],['신화 장비 상자','1개','0.1%','#984c61']];
 const chest='/linsa-rpg/art/ui-royal/wheel-chest.png',chests={3:'/linsa-rpg/art/ui-royal/wheel-chest-epic.png',4:chest,5:'/linsa-rpg/art/ui-royal/wheel-chest-mythic.png'};
 function install(){
  const g=window.RinguCore,economy=window.RinguEconomy;if(!g||!economy||window.RinguDailyWheel)return;
  const f=g.fn,esc=s=>f.escapeHtml(String(s??''));let spinning=false,rotation=0,boxId=null,boxTimer=null,boxBusy=false,alive=true;
  const style=document.createElement('style');style.textContent=`
  #dailyWheel,#wheelBox{position:fixed;inset:0;z-index:1200;display:flex;align-items:center;justify-content:center;padding:14px;background:#030911e8;backdrop-filter:blur(7px);box-sizing:border-box;color:#eadfc7;font-family:inherit}#dailyWheel[hidden],#wheelBox[hidden]{display:none!important}
  #dailyWheel .dw-panel,#wheelBox .dw-panel{width:min(470px,100%);max-height:calc(100dvh - 28px);overflow:auto;box-sizing:border-box;border:1px solid #aa8b52;border-radius:18px;background:radial-gradient(ellipse at top,#243347,#08111e 75%);box-shadow:inset 0 0 0 4px #091420,inset 0 0 0 5px #75623a,0 25px 80px #000a;padding:20px;text-align:center}
  .dw-panel h2{font-size:25px;margin:2px 0 7px;color:#f0d495;letter-spacing:2px}.dw-caption{font-size:12px;color:#b7bdc7;margin:0 0 10px}.dw-count{font-size:16px;color:#f4dc9e;margin:10px}.dw-stage{position:relative;width:100%;aspect-ratio:1;margin:12px auto 18px;isolation:isolate}.dw-disc{position:absolute;inset:6px;border-radius:50%;border:8px solid #b99a53;box-sizing:border-box;box-shadow:0 0 0 3px #302617,inset 0 0 0 3px #efd49a,inset 0 0 35px #0008;will-change:transform}.dw-disc:after{content:'';position:absolute;inset:0;border-radius:50%;background:repeating-conic-gradient(from 0deg,transparent 0deg 39.4deg,#edd299 39.4deg 40deg);pointer-events:none}
  .dw-label{position:absolute;transform:translate(-50%,-50%);width:27%;text-align:center;z-index:1;font-size:clamp(9px,2.8vw,12px);line-height:1.35;color:#fff4d7;text-shadow:0 1px 3px #000;font-weight:bold}.dw-label span{display:block;font-size:.85em;margin-top:3px}.dw-pointer{position:absolute;left:50%;top:0;transform:translateX(-50%);z-index:4;width:26px;height:34px;background:linear-gradient(90deg,#b18331,#fff0aa,#c79641);clip-path:polygon(0 0,100% 0,50% 100%);filter:drop-shadow(0 3px 3px #000)}.dw-hub{position:absolute;left:50%;top:50%;transform:translate(-50%,-50%);display:grid;place-items:center;width:20%;aspect-ratio:1;border-radius:50%;z-index:3;border:3px solid #d6b96e;background:radial-gradient(circle,#44506a,#111d2c);box-shadow:0 3px 15px #0008;color:#f3d38d;font-size:clamp(11px,4vw,18px);font-weight:bold;letter-spacing:1px}
  .dw-panel button{font:inherit;cursor:pointer;min-height:46px;border-radius:8px;border:1px solid #9e8656;background:#1b2b3c;color:#ece4d4;padding:10px 15px}.dw-panel button:disabled{opacity:.5;cursor:default}.dw-panel .dw-primary{width:100%;background:linear-gradient(#e6c876,#a77c29);color:#181610;font-weight:bold;font-size:17px;border:1px solid #ffe4a2}.dw-result{min-height:42px;margin:10px 0;color:#f0d497;font-size:15px;line-height:1.6}.dw-actions{display:flex;gap:8px}.dw-actions button{flex:1}.dw-odds{margin-top:14px;text-align:left;font-size:12px;color:#aebccc}.dw-odds table{width:100%;border-collapse:collapse;margin-top:8px}.dw-odds td{padding:5px;border-bottom:1px solid #334155}.dw-odds td:last-child{text-align:right}.dw-odds p{line-height:1.5}
  #wheelBox{z-index:1300}.wb-chest{position:relative;height:220px;perspective:550px;margin:10px auto}.wb-chest img{position:absolute;width:220px;height:220px;object-fit:contain;left:50%;top:0;margin-left:-110px}.wb-base{clip-path:inset(52% 0 0 0)}.wb-lid{clip-path:inset(0 0 48% 0);transform-origin:50% 52%;transition:transform 1.1s ease,filter 1.1s}.wb-chest.open .wb-lid{transform:translateY(-24px) rotateX(-65deg);filter:brightness(1.7)}.wb-light{position:absolute;inset:15%;background:radial-gradient(ellipse,#fff8c8,#edbe5470 30%,transparent 70%);opacity:0;transform:scale(.1);transition:1.2s}.wb-chest.open .wb-light{opacity:1;transform:scale(1.6)}.wb-item{min-height:180px;animation:wb-reveal .5s ease-out}.wb-item .rm-item-art,.wb-item .gear-icon{margin:0 auto!important;width:112px!important;height:112px!important}.wb-item h3{font-size:18px;margin:8px 0}.wb-item p{font-size:13px;line-height:1.6}#wheelBox [hidden]{display:none!important}@keyframes wb-reveal{from{opacity:0;transform:translateY(15px) scale(.85)}to{opacity:1;transform:none}}
  `;document.head.append(style);
  const modal=document.createElement('div');modal.id='dailyWheel';modal.hidden=true;modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','행운의 돌림판');
  modal.innerHTML='<section class="dw-panel"><h2>행운의 돌림판</h2><p class="dw-caption">매일 찾아오는 세 번의 행운</p><p class="dw-count" id="dwCount"></p><div class="dw-stage"><div class="dw-pointer"></div><div class="dw-disc"></div><div class="dw-hub">RINGU</div></div><button class="dw-primary" id="dwSpin">돌리기</button><p class="dw-result" id="dwResult" role="status" aria-live="polite">보상은 우편함으로 도착합니다.</p><div class="dw-actions"><button id="dwMail">우편함</button><button id="dwClose">닫기</button></div><details class="dw-odds"><summary>보상 안내</summary><table>'+prizes.map(p=>'<tr><td>'+p[0]+'</td><td>'+p[1]+'</td></tr>').join('')+'</table><p>하루 3회 · 한국시간 자정 초기화<br>장비 상자는 7부위 중 무작위 장비 1개, 부옵션 최소값으로 지급됩니다.</p></details></section>';document.body.append(modal);
  const $=id=>document.getElementById(id),disc=modal.querySelector('.dw-disc');disc.style.background='conic-gradient('+prizes.map((p,i)=>p[3]+' '+i*40+'deg '+(i+1)*40+'deg').join(',')+')';
  disc.innerHTML=prizes.map((p,i)=>{const a=(i*40+20)*Math.PI/180;return '<div class="dw-label" style="left:'+(50+34*Math.sin(a))+'%;top:'+(50-34*Math.cos(a))+'%">'+p[0]+'<span>'+p[1]+'</span></div>';}).join('');
  function refresh(){const day=new Date(Date.now()+9*3600000).toISOString().slice(0,10),used=g.state.dailyWheel?.day===day?g.state.dailyWheel.used:0;$('dwCount').textContent='오늘 남은 횟수 '+Math.max(0,3-used)+' / 3';$('dwSpin').disabled=spinning||used>=3;$('dwClose').disabled=spinning;$('dwMail').disabled=spinning;}
  const menu=document.createElement('button');menu.id='dailyWheelMenu';menu.textContent='행운의 돌림판';menu.onclick=()=>{modal.hidden=false;refresh();$('dwSpin').focus();};document.querySelector('#rmFeatureNav nav')?.append(menu);
  $('dwClose').onclick=()=>{if(!spinning){modal.hidden=true;menu.focus();}};$('dwMail').onclick=()=>{if(!spinning){modal.hidden=true;(f.openMailbox||window.openMailbox)?.();}};
  $('dwSpin').onclick=async()=>{
   if(spinning)return;spinning=true;refresh();$('dwResult').textContent='행운을 추첨하고 있어요…';
   const result=await economy.command('wheelSpin',{version:2});if(!alive)return;const outcome=result?.result?.events?.find(e=>e.type==='wheelSpin');
   if(!outcome){spinning=false;refresh();$('dwResult').textContent='추첨을 완료하지 못했습니다. 남은 횟수와 우편함을 확인해 주세요.';return;}
   const target=((360-(outcome.index*40+20))%360+360)%360,from=rotation;rotation=from+(360-(from%360))+360*5+target;
   $('dwResult').textContent='돌림판이 돌아갑니다…';const animation=disc.animate([{transform:'rotate('+from+'deg)'},{transform:'rotate('+rotation+'deg)'}],{duration:4000,easing:'cubic-bezier(.12,.60,.12,1)',fill:'forwards'});
   try{await animation.finished;}catch{}if(!alive)return;disc.style.transform='rotate('+rotation+'deg)';animation.cancel();spinning=false;refresh();$('dwResult').textContent=outcome.label+(outcome.index===7?' · 결과가 우편함에 도착했어요.':' 당첨! 우편함에서 받아 주세요.');
  };
  const box=document.createElement('div');box.id='wheelBox';box.hidden=true;box.setAttribute('role','dialog');box.setAttribute('aria-modal','true');box.setAttribute('aria-label','장비 상자 개봉');box.innerHTML='<section class="dw-panel"><h2 id="wbTitle"></h2><div class="wb-chest"><div class="wb-light"></div><img class="wb-base" src="'+chest+'" alt=""><img class="wb-lid" src="'+chest+'" alt="장비 상자"></div><div class="wb-item" hidden></div><p id="wbStatus" role="status">상자를 여는 중…</p><button id="wbConfirm" class="dw-primary" disabled>확인</button></section>';document.body.append(box);
  function reveal(){const data=g.state.wheelBoxReveal;if(!data||boxId===data.mailId||!alive)return;boxId=data.mailId;box.hidden=false;const scene=box.querySelector('.wb-chest'),item=box.querySelector('.wb-item');scene.hidden=false;scene.className='wb-chest';scene.querySelectorAll('img').forEach(img=>img.src=chests[data.rarity]||chest);item.hidden=true;$('wbConfirm').disabled=true;$('wbTitle').textContent=data.rarity===5?'신화 장비 상자':data.rarity===4?'전설 장비 상자':'에픽 장비 상자';$('wbStatus').textContent='상자를 여는 중…';requestAnimationFrame(()=>requestAnimationFrame(()=>scene.classList.add('open')));clearTimeout(boxTimer);boxTimer=setTimeout(()=>{if(!alive||boxId!==data.mailId)return;scene.hidden=true;item.innerHTML=f.gearIcon(data.item)+'<h3 style="color:'+esc(g.rarityColors[data.rarity])+'">'+f.itemTitleHtml(data.item,false)+'</h3><p>'+esc(data.item.slot)+' · 공격력 '+f.itemAttackText(data.item)+'</p><p>'+f.optionText(data.item,true)+'</p>';item.hidden=false;$('wbStatus').textContent='장비가 가방에 지급되었습니다.';$('wbConfirm').disabled=false;$('wbConfirm').focus();},1800);}
  $('wbConfirm').onclick=async()=>{if(boxBusy||!boxId)return;boxBusy=true;$('wbConfirm').disabled=true;const result=await economy.command('wheelBoxAck',{id:boxId});boxBusy=false;if(result){box.hidden=true;boxId=null;reveal();}else{$('wbConfirm').disabled=false;$('wbStatus').textContent='확인 처리를 다시 눌러 주세요. 장비는 이미 지급되었습니다.';}};
  function decorateMail(){document.querySelectorAll('[data-clean-mail-claim]').forEach(btn=>{const id=btn.getAttribute('data-clean-mail-claim');if(!id.startsWith('daily-wheel:'))return;const index=Number(id.split(':').at(-1)),p=prizes[index];if(!p)return;const label=btn.parentElement.querySelector('strong');if(label)label.textContent=p[0]+' · '+p[1];btn.textContent=(index<2||index===8)?'상자 열기':index===7?'확인':'받기';});}
  let queued=false;const observer=new MutationObserver(records=>{if(queued||!records.some(r=>r.target.nodeType===1&&(r.target.closest('#mailList,#mailboxModal')||[...r.addedNodes].some(n=>n.nodeType===1&&(n.id==='mailboxModal'||n.querySelector('#mailList'))))))return;queued=true;queueMicrotask(()=>{queued=false;observer.disconnect();decorateMail();observer.observe(document.body,{childList:true,subtree:true});});});observer.observe(document.body,{childList:true,subtree:true});
  const claimed=f.claimMail;f.claimMail=async function(...args){if(boxId){box.hidden=false;return false;}const result=await claimed.apply(this,args);reveal();return result;};
  function stateChanged(){refresh();reveal();}window.addEventListener('ringu:economy-state',stateChanged);
  for(const el of [modal,box])for(const type of ['keydown','keyup','pointerdown','pointerup'])el.addEventListener(type,event=>event.stopPropagation());
  window.RinguDailyWheel={open:()=>menu.click()};refresh();decorateMail();reveal();window.RinguSession.onEnded(()=>{alive=false;clearTimeout(boxTimer);disc.getAnimations().forEach(a=>a.cancel());observer.disconnect();window.removeEventListener('ringu:economy-state',stateChanged);modal.remove();box.remove();menu.remove();});
 }
 window.addEventListener('ringu-ready',install,{once:true});install();
})();

