/* PV2: mobile-first lobby + presentation-only visual unification. */
(()=>{'use strict';
 const $=id=>document.getElementById(id);let installed=false,home=null,baseShowPage=null;
 const svg={
  home:'<svg viewBox="0 0 48 48"><path d="M7 23 24 8l17 15v17H29V29H19v11H7z"/></svg>',
  hunt:'<svg viewBox="0 0 48 48"><path d="M8 7l13 12-5 5L4 11zM40 7 27 19l5 5 12-13zM14 28l6 6-8 8-6-6zM34 28l-6 6 8 8 6-6z"/></svg>',
  character:'<svg viewBox="0 0 48 48"><circle cx="24" cy="15" r="8"/><path d="M10 41c2-11 8-17 14-17s12 6 14 17"/></svg>',
  gear:'<svg viewBox="0 0 48 48"><path d="M9 7l13 12-5 5L5 11zM39 7 26 19l5 5 12-13zM16 27l5 5-9 9-5-5zM32 27l-5 5 9 9 5-5z"/></svg>',
  summon:'<svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="15"/><path d="M24 5l4 14 15 5-15 5-4 14-4-14-15-5 15-5z"/></svg>',
  bag:'<svg viewBox="0 0 48 48"><path d="M13 17h22l4 25H9z"/><path d="M17 17c0-7 3-11 7-11s7 4 7 11M16 27h16"/></svg>',
  auction:'<svg viewBox="0 0 48 48"><path d="M24 7v33M10 13h28M8 14l-6 12h12zm32 0-6 12h12M15 41h18"/></svg>',
  black:'<svg viewBox="0 0 48 48"><path d="M8 36h32l-5-20H13z"/><path d="M17 16V9h14v7M16 28h16M20 36v-8M28 36v-8"/></svg>',
  rank:'<svg viewBox="0 0 48 48"><path d="M15 7h18v8c0 8-4 13-9 13s-9-5-9-13z"/><path d="M15 11H8c0 9 4 13 10 13M33 11h7c0 9-4 13-10 13M24 28v8M16 41h16"/></svg>',
  mail:'<svg viewBox="0 0 48 48"><path d="M7 14h34v25H7z"/><path d="M8 15l16 13 16-13M18 31l6 5 6-5"/><circle cx="35" cy="11" r="5"/></svg>',
  settings:'<svg viewBox="0 0 48 48"><path d="M24 5l5 5 7-1 3 7 6 4-3 7 1 7-7 3-4 6-8-3-7 2-3-7-6-4 3-7-1-7 7-3z"/><circle cx="24" cy="24" r="7"/></svg>',
  gold:'<svg viewBox="0 0 48 48"><circle cx="24" cy="24" r="18"/><circle cx="24" cy="24" r="13"/><path d="M24 14l3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z"/></svg>',
  essence:'<svg viewBox="0 0 48 48"><path d="M24 5c9 9 15 16 15 24 0 8-6 14-15 14S9 37 9 29c0-8 6-15 15-24z"/><path d="M24 15c5 5 8 9 8 14a8 8 0 1 1-16 0c0-5 3-9 8-14z"/><path d="M12 28c6 1 10-2 12-8 2 6 6 9 12 8M24 7v34"/></svg>',
  stone:'<svg viewBox="0 0 48 48"><path d="M24 4 38 17l-6 25H16L10 17z"/><path d="M10 17h28M24 4v38M16 42l8-25 8 25"/></svg>',
  pet:'<svg viewBox="0 0 48 48"><ellipse cx="24" cy="31" rx="11" ry="9"/><circle cx="13" cy="20" r="5"/><circle cx="23" cy="16" r="5"/><circle cx="35" cy="20" r="5"/><circle cx="38" cy="30" r="4"/></svg>',
  power:'<svg viewBox="0 0 48 48"><path d="M8 7l13 12-5 5L4 11zM40 7 27 19l5 5 12-13zM14 28l6 6-8 8-6-6zM34 28l-6 6 8 8 6-6z"/></svg>'
 };
 const icon=(name,cls='')=>'<span class="pv-icon pv-'+name+' '+cls+'" aria-hidden="true">'+svg[name]+'</span>';
 const materialArt=type=>type==='stone'?'<span class="pv-material pv-material-stone" aria-hidden="true"><i></i><b></b></span>':'<span class="pv-material pv-material-protect" aria-hidden="true"><i></i><b></b></span>';
 function replaceHeaderIcons(){const top=document.querySelector('.topbar');if(!top)return;const rank=top.querySelector('.profile-button'),mail=top.querySelector('.mail-button'),settings=top.querySelector('.settings-button');if(rank){const name=$('playerNameTop')?.textContent||'';rank.innerHTML=icon('rank','pv-action')+'<b>랭킹</b><span id="playerNameTop">'+name+'</span>';}if(mail){const badge=$('mailBadge')?.textContent||'0';mail.innerHTML=icon('mail','pv-action')+'<b>우편</b><i class="mail-badge" id="mailBadge">'+badge+'</i>';}if(settings)settings.innerHTML=icon('settings','pv-action')+'<b>설정</b>';const defs=[['gold','gold'],['essence','essence'],['transcendStone','stone'],['petStone','pet'],['power','power'],['summonTop','summon']];for(const [id,key] of defs){const value=$(id),box=value?.closest('.stat');if(!box)continue;box.querySelector('.hud-icon,.pv-icon')?.remove();box.insertAdjacentHTML('afterbegin',icon(key));}}
 function featureButton(name){return [...document.querySelectorAll('#rmFeatureNav button')].find(b=>b.textContent.includes(name));}
 function openFeature(name){if(name==='auction'){featureButton('경매장')?.click();return}if(name==='black'){window.RinguBlackMarket?.open?.();return}if(name==='rank'){window.RinguCore?.fn?.openProfile?.();return}if(name==='bag'){window.openItemInventory?.();return}if(name==='character'||name==='gear'||name==='summon'||name==='hunt'){const page=name==='gear'?'inventory':name;show(page);}}
 function card(name,label,sub,iconName){return '<button type="button" class="pv-home-card pv-card-'+name+'" data-pv-action="'+name+'"><span class="pv-card-art">'+icon(iconName||name)+'</span><strong>'+label+'</strong><small>'+sub+'</small></button>';}
 function makeHome(){if(home)return home;const layout=document.querySelector('.layout');if(!layout)return null;home=document.createElement('section');home.id='pvHome';home.className='pv-home';home.dataset.page='home';home.innerHTML='<div class="pv-home-title"><span>메인 카테고리</span><small>원하는 콘텐츠를 바로 선택하세요.</small></div><div class="pv-home-grid">'+card('character','캐릭터','능력치와 장착 상태','character')+card('gear','장비','강화와 장비 관리','gear')+card('summon','소환','장비 소환과 성장','summon')+card('bag','가방','오라와 소모품','bag')+card('auction','경매장','유저 간 장비 거래','auction')+card('black','암시장','공통 진열 특별 상점','black')+card('rank','랭킹','공격력과 시련의 탑','rank')+'</div><div class="pv-hunt-title"><span>'+icon('hunt')+'사냥</span><small>현재 지역에서 자동 전투를 계속합니다.</small></div><button type="button" class="pv-hunt-card" data-pv-action="hunt"><div><small>THE WORLD OF RINGU</small><strong id="pvHuntName">모험 지역</strong><span id="pvHuntState">AUTO HUNT</span></div><b>사냥 화면 열기 →</b></button>';layout.prepend(home);home.addEventListener('click',e=>{const b=e.target.closest('[data-pv-action]');if(b)openFeature(b.dataset.pvAction)});return home;}
 function renderHome(){if(!home||!window.RinguCore)return;const f=RinguCore.fn,b=f.currentBoss?.(),s=RinguCore.state;const name=$('pvHuntName'),state=$('pvHuntState');if(name)name.textContent=b?.name||'모험 지역';if(state)state.textContent=(s?.autoBattle?'AUTO HUNT':'PAUSED')+' · 공격력 '+Number(f.getPower?.()||0).toLocaleString('ko-KR');}
 function show(page){if(!home)makeHome();if(page==='home'){document.body.dataset.page='home';document.querySelectorAll('[data-page]').forEach(el=>{if(el!==document.body)el.hidden=el!==home});document.querySelectorAll('.rm-bottom-nav button').forEach(b=>{const on=b.dataset.target==='home';b.classList.toggle('active',on);if(on)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});window.scrollTo({top:0,behavior:'instant'});renderHome();return}home.hidden=true;baseShowPage?.(page);}
 function navSetup(){const nav=document.querySelector('.rm-bottom-nav');if(!nav)return false;if(nav.dataset.pv2==='1')return !!baseShowPage;const buttons=[...nav.querySelectorAll('button')];if(buttons.length<5||!window.RinguPortrait?.showPage)return false;baseShowPage=window.RinguPortrait.showPage.bind(window.RinguPortrait);const defs=[['home','메인','home'],['hunt','사냥','hunt'],['character','캐릭터','character'],['summon','소환','summon'],['menu','메뉴','settings']];buttons.slice(0,5).forEach((b,i)=>{const [target,label,key]=defs[i];b.dataset.target=target;b.innerHTML=icon(key)+'<strong>'+label+'</strong>';});nav.dataset.pv2='1';window.RinguPortrait.showPage=show;nav.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.target==='home'){e.preventDefault();e.stopImmediatePropagation();show('home');}else home&&(home.hidden=true);},true);show('home');return true;}
 function ensureNavSetup(){let attempts=0;const tick=()=>{if(navSetup()||attempts++>=80)return;setTimeout(tick,100)};tick();}
 function decorateMaterials(root=document){root.querySelectorAll?.('.utility-card,.shop-card,.bm-offer,.auction-card').forEach(card=>{const text=card.textContent||'',type=text.includes('초월석')?'stone':text.includes('하락방지권')?'protect':null;if(!type)return;const target=card.querySelector('.utility-icon,.bm-consumable-icon,.auction-art');if(target&&!target.dataset.pvMaterial){target.dataset.pvMaterial=type;target.innerHTML=materialArt(type);target.classList.add('pv-material-host');}});}
 function decorateAuction(root=document){root.querySelectorAll?.('.auction-price').forEach(el=>{if(el.dataset.pvPrice)return;const m=el.textContent.match(/[\d,]+/);if(m&&window.RinguHUD){el.innerHTML=RinguHUD.priceHTML(Number(m[0].replaceAll(',','')));el.dataset.pvPrice='1';}});const bal=root.querySelector?.('#auctionBalance');if(bal&&!bal.dataset.pvPrice){const m=bal.textContent.match(/[\d,]+/);if(m&&window.RinguHUD){bal.innerHTML='보유 '+RinguHUD.priceHTML(Number(m[0].replaceAll(',','')));bal.dataset.pvPrice='1';}}}
 function scan(root=document){decorateMaterials(root);decorateAuction(root);}
 function install(){if(installed)return;if(!window.RinguCore||!document.querySelector('.topbar'))return setTimeout(install,100);installed=true;replaceHeaderIcons();makeHome();ensureNavSetup();scan();renderHome();const mo=new MutationObserver(ms=>{for(const m of ms)for(const n of m.addedNodes)if(n.nodeType===1)scan(n)});mo.observe(document.body,{childList:true,subtree:true});window.addEventListener('ringu:economy-state',()=>{renderHome();replaceHeaderIcons();scan();});setInterval(()=>{if(home&&!home.hidden)renderHome()},1500);window.RinguPremium=Object.freeze({version:'PV2',icon,materialArt,showHome:()=>show('home'),scan});}
 window.addEventListener('ringu-ready',install,{once:true});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();