(()=>{'use strict';
window.installRinguRemodel=function(g){
 const $=id=>document.getElementById(id),f=g.fn,old=Object.fromEntries(Object.getOwnPropertyNames(f).map(k=>[k,f[k]])),esc=s=>f.escapeHtml(String(s??'')),fmt=n=>Math.floor(Number(n)||0).toLocaleString('ko-KR'),art=window.RinguArt;
 const state=()=>g.state,active=()=>window.RinguSession.active!==false;
 const equipMap=()=>Object.fromEntries(g.slots.map(slot=>[slot,state().inventory.find(it=>String(it.id)===String(state().equipped[slot]))]));
 const changed=()=>{f.renderAll();f.save(false)};
 const noop=()=>Promise.resolve(false);
 let attackTimer=null,attackMotion=null;
 const cancelAttack=()=>{clearTimeout(attackTimer);attackTimer=null;attackMotion=null};
 const originalAttack=f.attack;
 f.attack=()=>{if(!active())return;if(g.activeTower||g.activeDungeon)return originalAttack();if(!state().autoBattle||attackTimer!==null||g.combat.hp<=0)return;const owner=state(),region=owner.regionIndex,boss=owner.bossIndex;window.RinguAudio?.effect('swing');attackMotion={started:performance.now(),hit:false};attackTimer=setTimeout(()=>{attackTimer=null;if(!active()||state()!==owner||!owner.autoBattle||owner.regionIndex!==region||owner.bossIndex!==boss||g.activeTower||g.activeDungeon)return cancelAttack();attackMotion.hit=true;originalAttack();},460);};
 for(const name of ['selectRegion','selectBoss','toggleAutoBattle']){const before=f[name];f[name]=(...args)=>{cancelAttack();return before(...args)}}
 window.RinguSession.onEnded?.(cancelAttack);
 const originalResetCombat=f.resetCombat;f.resetCombat=(...args)=>{const result=originalResetCombat(...args);if(state())f.renderBattle();return result};
 for(const name of ['initCloudSync','pullCloudState','uploadCloudState','syncMailboxReceipts'])f[name]=noop;
 f.getCloudSession=()=>null;f.checkTargetMail=()=>false;f.scheduleCloudSave=()=>{};
 f.ensureCloudFreshForAction=async()=>active();f.saveChanceAction=()=>f.save(false);
 f.save=()=>{if(!state()||!active())return;state().lastSeen=Date.now();state().savedAt=Date.now();state().remodelProfile=f.ownProfile();try{localStorage.setItem('swordEnhanceRPG_balance_20260617_v5',JSON.stringify(state()))}catch(e){f.toast('브라우저 임시 저장 공간이 부족합니다. 서버 저장 상태를 확인하세요.')}window.RinguSession.save(state());};
 let saveTimer;f.queueSave=()=>{clearTimeout(saveTimer);saveTimer=setTimeout(()=>f.save(false),150)};
 f.spendGold=cost=>{cost=Number(cost);if(!active()||!Number.isFinite(cost)||cost<0||state().gold<cost)return false;state().gold-=cost;return true};
 f.load=()=>{old.load();const s=state();s.uid=Math.max(Number(s.uid)||1,...s.inventory.map(i=>(Number(i.id)||0)+1));s.regionIndex=Math.max(0,Math.min(g.bossRegions.length-1,s.regionIndex||0));
  s.remodelStarted=true;setupLayout();f.renderAll();f.save(false);
 };
 f.gearIcon=it=>art.icon(it,f.itemIndex(it));f.ringuResultIcon=f.gearIcon;
 window.openItemDetail=id=>{const it=state().inventory.find(item=>String(item.id)===String(id));if(!it)return;let modal=$('rmItemDetail');if(!modal){modal=document.createElement('div');modal.id='rmItemDetail';modal.className='modal-bg';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','장비 상세');document.body.append(modal);}modal.innerHTML='<section class="modal"><h3>'+esc(it.name)+'</h3><div class="rm-detail-art">'+f.gearIcon(it)+'</div><p>'+g.rarityNames[it.rarity]+' · '+esc(it.slot)+' · '+(f.isItemEquipped(it)?'✓ 장착 중':'미장착')+'</p><h3>⚔ '+fmt(f.itemAtk(it))+'</h3><p>'+f.optionText(it)+'</p><p>강화 +'+it.enhance+'　초월 '+(it.transcend||0)+'　'+(it.locked?'🔒 잠금':'')+'</p><button id="rmDetailEnhance">강화 / 초월</button><button id="rmDetailClose">닫기</button></section>';$('rmDetailEnhance').onclick=()=>{modal.classList.remove('show');f.openEnhance(it.id)};$('rmDetailClose').onclick=()=>modal.classList.remove('show');modal.classList.add('show');$('rmDetailClose').focus();};
 f.sortInventoryItems=list=>list.sort((a,b)=>Number(f.isItemEquipped(b))-Number(f.isItemEquipped(a))||($('sortSelect')?.value==='rarity'?b.rarity-a.rarity:0)||f.itemAtk(b)-f.itemAtk(a));
 f.renderEquipment=()=>{const s=state(),map=equipMap(),signature=JSON.stringify([s.equipped,s.inventory.filter(it=>map[it.slot]===it).map(it=>[it.id,it.enhance,it.transcend]),s.playerGender,s.playerName,s.equippedAura,s.equippedPet]);if($('equipGrid').dataset.signature===signature)return;$('equipGrid').dataset.signature=signature;
  $('equipGrid').innerHTML='<div class="rm-character-stage"><canvas id="heroCanvas" width="640" height="780" aria-label="장착 무기가 반영된 캐릭터"></canvas><div class="rm-character-caption"><small>ADVENTURER</small><strong>'+esc(s.playerName)+'</strong><span>무기만 외형에 반영 · 방어구 능력치 적용</span></div></div><div class="rm-equipped-list">'+g.slots.map(slot=>{const it=map[slot];return '<button class="rm-equipped-slot" '+(it?'onclick="openEnhance('+it.id+')"':'onclick="scrollToId(\'inventoryPanel\')"')+' style="--rarity:'+(it?g.rarityColors[it.rarity]:'#697178')+'">'+(it?f.gearIcon(it):'<span class="rm-empty-slot">＋</span>')+'<span><small>'+slot+'</small><strong>'+esc(it?it.name:'미장착')+'</strong><em>'+(it?'⚔ '+fmt(f.itemAtk(it))+'　+'+it.enhance+' '+('★'.repeat(it.transcend||0)):'가방에서 장비 선택')+'</em></span></button>'}).join('')+'</div>';$('equipAtk').textContent='⚔ '+fmt(f.getPower());
 };
 f.renderBosses=()=>{const s=state();$('regionTabs').innerHTML=g.bossRegions.map((r,i)=>'<button class="region-tab '+(i===s.regionIndex?'active':'')+'" onclick="selectRegion('+i+')">'+['초원','사막','설원','화산','천공','심연'][i]+'</button>').join('');$('bossList').innerHTML=f.currentBosses().map((b,i)=>'<button class="boss-btn '+(i===s.bossIndex?'active':'')+'" onclick="selectBoss('+i+')"><span class="rm-monster-icon" style="background-position:'+((i)/5*100)+'% '+(s.regionIndex/5*100)+'%"></span><strong>'+esc(b.name)+'</strong><span>♥ '+fmt(b.hp)+'　◈ '+fmt(b.reward)+'</span></button>').join('');};
 f.renderBattle=()=>{const b=f.currentBoss(),s=state(),c=g.combat;$('bossName').textContent=b.name;$('hpText').textContent=fmt(c.hp)+' / '+fmt(b.hp);$('hpFill').style.width=Math.max(0,c.hp/b.hp*100)+'%';$('timerFill').style.width=Math.max(0,(15-c.elapsed)/15*100)+'%';$('battleToggle').textContent=s.autoBattle?'사냥 중지':'자동사냥 시작';$('battleToggle').classList.toggle('on',s.autoBattle);$('battleState').textContent=s.autoBattle?'AUTO HUNT · '+c.elapsed+' / 15초':'PAUSED · 전투 대기';};
 f.renderPlayerStats=()=>{const s=f.getPlayerStats();$('playerStats').innerHTML=[['⚔','공격력',fmt(s.attack)],['↑','공격력 보너스',s.atkPercent.toFixed(1)+'%'],['✦','치명타 확률',s.critChance.toFixed(1)+'%'],['ϟ','치명타 피해',s.critDamage.toFixed(1)+'%'],['◈','골드 보너스',s.goldBonus.toFixed(1)+'%'],['➶','공격속도','×'+(s.attackSpeed||1).toFixed(2)]].map(([icon,name,value])=>'<div class="player-stat"><span>'+icon+' '+name+'</span><b>'+value+'</b></div>').join('');};
 f.renderAll=()=>{if(!state())return;f.renderTop();f.renderBosses();f.renderBattle();f.renderEquipment();f.renderPlayerStats();f.renderSummon();f.renderInventory();window.renderMailboxBadge?.();f.renderDailyRewardBoxV1();paintPetIcons();};
 f.renderPetLayer=()=>'';
 function paintPetIcons(){document.querySelectorAll('.pet-card,.pet-result-card').forEach(card=>{const label=card.querySelector('strong')?.textContent||'',data=Object.values(g.PET_DATA).find(p=>label.includes(p.name));if(!data)return;const icon=card.querySelector('.pet-icon');if(icon){const i=Object.keys(g.PET_DATA).sort().indexOf(data.id);icon.textContent='';icon.classList.add('rm-pet-art');icon.style.backgroundPosition=(i%5/4*100)+'% '+(Math.floor(i/5)/4*100)+'%';}});}
 for(const name of ['renderPetCard','renderPetCollectionCard','renderPetSummonResult']){const prev=f[name];f[name]=function(...args){const r=prev(...args);queueMicrotask(paintPetIcons);return r};}
 f.claimMail=id=>{if(!active())return false;const s=state(),mail=s.mailbox.find(m=>m.id===String(id));if(!mail)return false;s.claimedMailReceipts??={};if(s.claimedMailReceipts[mail.id])return false;const before=structuredClone(s);try{s.claimedMailReceipts[mail.id]=Date.now();f.applyMailboxReward(mail.reward);s.mailbox=s.mailbox.filter(m=>m.id!==mail.id);changed();window.renderMailbox();f.toast('우편 보상을 수령했습니다.');return true}catch(e){g.state=before;throw e}};
 const rawDaily=f.claimDailyReward;f.claimDailyReward=()=>{if(!active())return false;const r=rawDaily();f.save(false);return r};
 let operation=null;
 f.openEnhance=id=>{if(operation)return f.toast('강화가 끝난 뒤 다른 장비를 선택하세요.');g.enhanceId=state().inventory.find(it=>String(it.id)===String(id))?.id??null;if(g.enhanceId===null)return;f.renderEnhance();$('enhanceModal').classList.add('show')};
 f.closeEnhance=()=>{if(operation)return f.toast('강화 결과를 확인한 뒤 닫을 수 있습니다.');$('enhanceModal').classList.remove('show');g.enhanceId=null;g.enhanceBusy=false};
 f.renderEnhance=()=>{const it=state().inventory.find(i=>String(i.id)===String(g.enhanceId));if(!it)return;const next=(it.transcend||0)+1;$('enhanceTitle').textContent=it.name;$('enhanceGear').innerHTML=f.gearIcon(it);$('enhanceDesc').innerHTML='⚔ '+fmt(f.itemAtk(it))+'　'+f.optionText(it);$('enhNow').textContent='+'+it.enhance+'　'+'★'.repeat(it.transcend||0);$('enhRate').textContent=it.enhance>=15?'MAX':f.successRate(it.enhance+1)+'%';$('enhCost').textContent=it.enhance>=15?'—':fmt(f.enhanceCost(it))+' G';$('enhanceBtn').disabled=!!operation||it.enhance>=15;$('enhanceBtn').textContent=operation?'진행 중…':'강화 시도';$('transcendBtn').disabled=!!operation||!f.canTranscend(it);$('transcendBtn').textContent=(it.transcend||0)>=3?'최대 초월 달성':next+'초월 시도';$('transcendInfo').textContent=f.canTranscend(it)?'초월석 '+f.transcendCost(it,next)+'개 · 성공률 '+f.transcendRate(next)+'%':'전설 이상, +15 강화 장비만 초월할 수 있습니다.';$('protectToggle').textContent='하락 방지 '+(state().useProtect?'ON':'OFF')+' · 보유 '+state().downgradeProtect+'장';};
 function forge(transcend){if(operation||!active())return false;const it=state().inventory.find(i=>String(i.id)===String(g.enhanceId));if(!it||(!transcend&&it.enhance>=15)||(transcend&&!f.canTranscend(it)))return false;const next=transcend?(it.transcend||0)+1:it.enhance+1,cost=transcend?f.transcendCost(it,next):f.enhanceCost(it);if(transcend?state().transcendStone<cost:state().gold<cost)return f.toast('재료가 부족합니다.'),false;
  // Resolve and persist the outcome synchronously; animation never owns currency or item state.
  if(transcend)state().transcendStone-=cost;else if(!f.spendGold(cost))return false;const success=Math.random()*100<(transcend?f.transcendRate(next):f.successRate(next));if(success){if(transcend)it.transcend=next;else it.enhance=next;}else if(!transcend&&next>=2){if(state().useProtect&&state().downgradeProtect>0)state().downgradeProtect--;else it.enhance=Math.max(0,it.enhance-1);}
  operation={id:it.id};g.enhanceBusy=true;f.save(false);f.renderEnhance();$('enhanceStage').className='enhance-stage forging';try{f.playForgeSound()}catch(e){}setTimeout(()=>{operation=null;g.enhanceBusy=false;if(!active())return;changed();f.renderEnhance();$('enhanceStage').className='enhance-stage '+(success?'success':'fail');$('enhanceResult').textContent=success?'성공':'실패';window.RinguAudio?.effect(success?'success':'failure');},600);return true;
 }
 f.tryEnhance=()=>forge(false);f.tryTranscend=()=>forge(true);
 for(const name of ['sellItem','bulkSell','toggleEquipItem']){const prev=f[name];f[name]=(...args)=>{if(operation||!active())return f.toast('진행 중인 작업이 끝난 뒤 이용하세요.');return prev(...args)}}
 const oldDraw=f.drawItems;f.drawItems=n=>{if(!active())return false;return oldDraw(n)};
 const rawTowerStart=f.startTower;f.startTower=n=>{if(g.activeTower)return f.toast('이미 탑 전투 중입니다.');return rawTowerStart(n)};
 const rawDungeonStart=f.startDungeonBattle;f.startDungeonBattle=(...args)=>{if(g.activeDungeon||g.activeTower)return f.toast('진행 중인 전투를 먼저 종료하세요.');return rawDungeonStart(...args)};
 const rawDungeonRender=f.renderDungeon;f.renderDungeon=()=>{rawDungeonRender();if(g.dungeonType==='stone'&&!g.activeDungeon){$('dungeonStageList').innerHTML='<p class="rm-note">초월석 던전 · 개인 도전 · 클리어 시 이용 횟수 차감</p>'+Array.from({length:6},(_,i)=>'<button class="rm-dungeon-entry" onclick="quickPartyEntry('+(i+1)+')">'+(i+1)+'단계 도전　→</button>').join('');}};
 f.syncRanking=async()=>{try{const res=await fetch('/api/ranking');if(!res.ok)return;const data=await res.json();const own={id:window.RinguSession.account?.id,name:state().playerName,power:f.getPower(),tower:state().towerCleared,gender:state().playerGender,equipment:f.ownProfile().equipment};const rows=(data.rows||[]).filter(r=>r.id!==own.id);rows.push(own);rows.sort((a,b)=>b.power-a.power);g.rankingProfiles=rows;$('rankStatus').textContent='동일 서버의 저장된 캐릭터 기록';$('rankList').innerHTML=rows.map((p,i)=>'<button class="rm-rank-row" onclick="openRankingCharacter('+i+')"><span>'+String(i+1).padStart(2,'0')+'</span><strong>'+esc(p.name)+'</strong><b>⚔ '+fmt(p.power)+'</b></button>').join('')}catch(e){$('rankStatus').textContent='랭킹 연결을 확인하세요.'}};
 f.openProfile=()=>{$('profileModal').classList.add('show');$('profileUid').textContent=state().playerUid;$('nicknameInput').value=state().playerName;f.syncRanking()};
 f.openRankingCharacter=i=>{const p=g.rankingProfiles[i];if(!p)return;$('playerEquipTitle').textContent=p.name+'의 장비';$('playerEquipStats').textContent='⚔ '+fmt(p.power)+'　시련의 탑 '+p.tower+'층';$('playerEquipGrid').innerHTML=(p.equipment||[]).map(v=>{const it={slot:v.s||v.slot,rarity:v.r??v.rarity,name:v.n||v.name};return '<div class="rm-rank-item">'+f.gearIcon(it)+'<span>'+esc(it.name)+'<small>+'+(v.e??v.enhance??0)+'　'+'★'.repeat(v.t??v.transcend??0)+'</small></span></div>'}).join('');$('playerEquipModal').classList.add('show')};
 function setupLayout(){
  const s=state();document.title='링구 RPG · REFORGED';document.querySelector('.brand').innerHTML='<b>RINGU</b><small>REFORGED</small>';document.querySelector('.pose-open-btn')?.remove();document.querySelector('.cloud-account')?.remove();document.querySelector('.settings-form')?.remove();$('hiddenStatus')?.remove();
  document.querySelector('#settingsModal .rank-note')?.remove();document.querySelector('#settingsModal .modal').insertAdjacentHTML('beforeend','<div class="rm-account-tools"><p>현재 로그인: <b id="rmAccountName"></b></p><button id="rmFxToggle">오라 애니메이션 '+(s.remodelFx===false?'OFF':'ON')+'</button><button id="rmExport">저장 파일 내보내기</button><button id="rmLogout">로그아웃</button></div>');$('rmAccountName').textContent=window.RinguSession.account?.username||'계정';$('rmLogout').onclick=()=>window.RinguSession.logout();$('rmExport').onclick=()=>window.RinguSession.exportSave?.();$('rmFxToggle').onclick=()=>{s.remodelFx=s.remodelFx===false;changed();$('rmFxToggle').textContent='오라 애니메이션 '+(s.remodelFx?'ON':'OFF')};
  document.querySelector('main.app').insertAdjacentHTML('afterbegin','<aside class="rm-sidebar"><div class="rm-seal">R</div><span class="rm-nav-caption">YOUR ADVENTURE</span><button onclick="scrollToId(\'arena\')">✧　모험 / 사냥</button><button onclick="scrollToId(\'equipGrid\')">♙　캐릭터 / 장비</button><button onclick="scrollToId(\'summonPanel\')">✦　장비 소환</button><button onclick="scrollToId(\'inventoryPanel\')">▣　인벤토리</button><hr><nav id="rmFeatureNav"></nav><div class="rm-session"><i></i><span id="rmSaveStatus">서버 연결됨</span><small>한 계정 · 한 접속</small></div></aside>');const quick=document.querySelector('nav.quick');$('rmFeatureNav').appendChild(quick);quick.className='rm-feature-nav';
  $('arena').insertAdjacentHTML('afterbegin','<canvas id="combatCanvas" width="1400" height="900" aria-label="캐릭터와 몬스터 전투"></canvas><span class="rm-location">THE WORLD OF RINGU</span>');$('bossArt').style.display='none';
  for(const n of ['enhanceBtn','transcendBtn'])$(n).onclick=n==='enhanceBtn'?f.tryEnhance:f.tryTranscend;
  document.querySelectorAll('[onclick^="drawItems("]').forEach(btn=>{const n=Number(btn.getAttribute('onclick').match(/\d+/)[0]);btn.onclick=()=>f.drawItems(n)});
  document.querySelectorAll('.modal-bg').forEach(el=>{el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');});
  let lastFocus=null;document.addEventListener('keydown',e=>{const modal=[...document.querySelectorAll('.modal-bg.show')].at(-1);if(e.key==='Escape'&&modal){if(modal.id==='enhanceModal')f.closeEnhance();else if(modal.id==='dungeonModal')f.closeDungeon();else if(modal.id==='towerModal')f.closeTower();else{modal.classList.remove('show');modal.style.removeProperty('display')}lastFocus?.focus();e.preventDefault();}else if(e.key==='Tab'&&modal){const list=[...modal.querySelectorAll('button:not(:disabled),input,select,[tabindex="0"]')].filter(el=>el.offsetParent!==null);if(list.length){const i=list.indexOf(document.activeElement),next=e.shiftKey?(i<=0?list.length-1:i-1):(i+1)%list.length;list[next].focus();e.preventDefault();}}});document.addEventListener('click',e=>{if(!e.target.closest('.modal-bg'))lastFocus=e.target});
  const oldSettings=f.openSettings;f.openSettings=()=>{try{oldSettings()}catch(e){$('settingsModal').classList.add('show');f.renderAudioSettings()}};
  if(window.RinguSession.subscribe)window.RinguSession.subscribe(status=>{if($('rmSaveStatus'))$('rmSaveStatus').textContent=typeof status==='string'?status:status.message});
  window.RinguSession.onEnded?.(()=>{clearTimeout(saveTimer);try{f.stopBgm()}catch(e){}g.coreFixes?.cancelBattles()});
  setupPortrait();
  art.ready.then(()=>requestAnimationFrame(draw));
 }
 function setupPortrait(){
  document.querySelector('.topbar .stats').id='rmCurrencyStats';
  const pages={hunt:['.boss-panel','.battle-panel'],character:['.equip-panel','.stats-panel'],summon:['.summon-panel'],inventory:['.inventory']};
  for(const [page,selectors]of Object.entries(pages))for(const selector of selectors)document.querySelector(selector).dataset.page=page;
  const sidebar=document.querySelector('.rm-sidebar');sidebar.dataset.page='menu';sidebar.setAttribute('aria-label','전체 메뉴');
  sidebar.querySelectorAll(':scope > button').forEach(button=>button.remove());sidebar.querySelector('.rm-nav-caption').textContent='모험 메뉴';
  const features=$('rmFeatureNav');if(typeof window.openPetPanel==='function'){const button=document.createElement('button');button.textContent='펫 / 동료';button.onclick=()=>window.openPetPanel();features.querySelector('nav').append(button);}
  const nav=document.createElement('nav');nav.className='rm-bottom-nav';nav.setAttribute('aria-label','게임 주요 메뉴');
  nav.innerHTML=[['hunt','✧','사냥'],['character','♙','캐릭터'],['summon','✦','소환'],['inventory','▣','장비'],['menu','☰','메뉴']].map(([page,icon,label])=>'<button type="button" data-target="'+page+'"><span aria-hidden="true">'+icon+'</span><strong>'+label+'</strong></button>').join('');document.body.append(nav);
  const desktop=window.matchMedia('(min-width:1100px)');
  function showPage(page){if(!pages[page]&&page!=='menu')return;document.body.dataset.page=page;document.querySelectorAll('[data-page]').forEach(el=>{if(el!==document.body)el.hidden=!desktop.matches&&el.dataset.page!==page});nav.querySelectorAll('button').forEach(button=>{const selected=button.dataset.target===page;button.classList.toggle('active',selected);if(selected)button.setAttribute('aria-current','page');else button.removeAttribute('aria-current')});if(desktop.matches){const target=page==='menu'?sidebar:document.querySelector(pages[page][0]);target?.scrollIntoView({block:'start',behavior:'smooth'});}else window.scrollTo({top:0,behavior:'instant'});}
  desktop.addEventListener('change',()=>showPage(document.body.dataset.page||'hunt'));
  nav.addEventListener('click',event=>{const button=event.target.closest('button');if(button)showPage(button.dataset.target)});
  window.scrollToId=id=>showPage(id==='equipGrid'?'character':id==='summonPanel'?'summon':id==='inventoryPanel'?'inventory':'hunt');
  window.RinguPortrait={showPage};showPage('hunt');
  const previewButton=document.createElement('button');previewButton.textContent='오라 미리보기';previewButton.onclick=openAuraPreview;features.querySelector('nav').append(previewButton);
 }
 function openAuraPreview(){
  let modal=$('rmAuraPreview');if(!modal){modal=document.createElement('div');modal.id='rmAuraPreview';modal.className='modal-bg';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','rmAuraTitle');modal.innerHTML='<section class="modal"><h3 id="rmAuraTitle">캐릭터 오라</h3><p>캐릭터 뒤에서 실시간으로 움직이는 효과입니다. 미리보기는 장비·재화·보유 오라를 변경하지 않습니다.</p><canvas id="rmAuraCanvas" width="640" height="820" aria-label="캐릭터 뒤 오라 애니메이션 미리보기"></canvas><label for="rmAuraSelect">오라 선택</label><select id="rmAuraSelect">'+g.auraShopItems.map(([name],i)=>'<option value="'+i+'">'+esc(name)+'</option>').join('')+'</select><button id="rmAuraClose">닫기</button></section>';document.body.append(modal);$('rmAuraClose').onclick=()=>modal.classList.remove('show');}
  $('rmAuraSelect').value=String(Math.max(0,state().equippedAura));modal.classList.add('show');$('rmAuraSelect').focus();
 }
 let lastPaint=0;
 function draw(time){requestAnimationFrame(draw);if(time-lastPaint<16||document.hidden||!active()||!state())return;lastPaint=time;const s=state(),map=equipMap(),ix=it=>f.itemIndex(it),hc=$('heroCanvas');if(hc?.clientWidth){const c=hc.getContext('2d');c.clearRect(0,0,hc.width,hc.height);art.hero(c,s,map,ix,time,320,710,640);}
  const preview=$('rmAuraCanvas');if(preview&&$('rmAuraPreview').classList.contains('show')){const c=preview.getContext('2d');c.clearRect(0,0,640,820);art.hero(c,{...s,equippedAura:Number($('rmAuraSelect').value),remodelFx:true},map,ix,time,320,735,620);}
  const canvas=$('combatCanvas');if(canvas&&canvas.clientWidth){const scale=Math.min(window.devicePixelRatio||1,2),cw=Math.round(canvas.clientWidth*scale),ch=Math.round(canvas.clientHeight*scale);if(canvas.width!==cw||canvas.height!==ch){canvas.width=cw;canvas.height=ch}const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height;art.sprite(c,'worlds',s.regionIndex,3,2,0,0,w,h);const shade=c.createLinearGradient(0,0,0,h);shade.addColorStop(0,'#080c12a8');shade.addColorStop(.45,'#080c1210');shade.addColorStop(1,'#080c12ee');c.fillStyle=shade;c.fillRect(0,0,w,h);
   const age=attackMotion&&s.autoBattle?time-attackMotion.started:2000,reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
   const pose=age<150?1:age<280?2:age<430?3:age<560?4:age<700?5:age<840?2:age<960?1:0;
   const step=age<280?Math.sin(age/280*Math.PI/2):age<700?1:age<960?Math.cos((age-700)/260*Math.PI/2):0;
   const size=Math.min(w*.44,h*.40),impact=attackMotion?.hit&&age>=460&&age<650?Math.sin((age-460)/190*Math.PI):0;
   art.sprite(c,'monsters-facing',s.regionIndex*6+s.bossIndex,6,6,w*.58+impact*w*.016,h*.79-size*(1-impact*.04),size*(1+impact*.045),size*(1-impact*.04));
   const grip=art.battleHero(c,s,map,ix,time,w*(.25+(reduced?0:step*.13)),h*.79,Math.min(h*.52,w*.65),{pose:reduced?0:pose});canvas.dataset.pose=String(reduced?0:pose);canvas.dataset.facing='right';canvas.dataset.monsterFacing='left';canvas.dataset.attacking=String(age<960);if(grip){canvas.dataset.handX=String(grip.handX);canvas.dataset.handY=String(grip.handY)}
  }
  for(const [id,name,index,cols,rows]of [['towerArt','tower',Math.max(0,(g.activeTower?.data.floor||1)-1),6,5],['dungeonBossArt','monsters',g.activeDungeon?.type==='gold'?7:g.activeDungeon?.type==='pet'?5:31,6,6]]){const el=$(id);if(el){el.classList.add('rm-enemy-art');el.style.backgroundImage='url(/linsa-rpg/art/'+name+'.png)';el.style.backgroundSize=(cols*100)+'% '+(rows*100)+'%';el.style.backgroundPosition=(index%cols/(cols-1)*100)+'% '+(Math.floor(index/cols)/(rows-1)*100)+'%';}}
 }
 window.RinguRemodel={changed,equipMap,paintPetIcons};
};
})();
