(()=>{'use strict';
let installed=false,hiddenAt=0,wasAuto=false,rankMode='power';
const G=()=>window.RinguCore,F=()=>G()?.fn,S=()=>G()?.state;
const style=document.createElement('style');
style.textContent=`
#ringu-session-status{position:fixed!important;top:max(10px,env(safe-area-inset-top))!important;bottom:auto!important;left:10px!important;right:auto!important;max-width:min(290px,calc(100vw - 20px))!important;pointer-events:none!important;z-index:2147483645!important}
.ringu-monster-locked{position:relative!important;filter:grayscale(.9) brightness(.42)!important;cursor:not-allowed!important;border-color:#343b42!important}.ringu-monster-locked .rm-monster-icon{opacity:.28!important}.ringu-lock-tag{display:block!important;margin-top:5px!important;color:#d0c0a3!important;font-size:8px!important;white-space:nowrap!important}.ringu-region-locked{opacity:.38!important;cursor:not-allowed!important}.ringu-stat-icon{display:inline-flex;align-items:center;justify-content:center;width:1.15em;margin-right:.25em}.stat-label.ringu-labeled{display:flex!important;align-items:center!important;white-space:nowrap!important}
#drawResultGrid{width:100%!important;box-sizing:border-box!important;justify-items:stretch!important;align-items:stretch!important}#drawResultGrid .draw-card{box-sizing:border-box!important;min-width:0!important;max-width:100%!important;overflow:hidden!important;text-align:center!important}#drawResultGrid .draw-card .rm-item-art{display:block!important;width:min(72px,82%)!important;height:72px!important;max-width:100%!important;margin:0 auto 6px!important;background-position:center!important;background-size:contain!important;background-repeat:no-repeat!important}.ringu-result-icon{max-width:100%!important;margin-left:auto!important;margin-right:auto!important}
#dungeonBossArt{position:relative!important;overflow:visible!important}#dungeonBossArt .dungeon-pop{position:absolute!important;left:50%!important;top:44%!important;z-index:30!important;transform:translate(-50%,-50%)!important;font-size:18px!important;font-weight:1000!important;color:#fff!important;text-shadow:0 2px #000,0 0 10px #fff!important;pointer-events:none!important;white-space:nowrap!important;animation:damage .75s forwards!important}
@media(max-width:520px){#drawResultModal .modal{width:calc(100vw - 14px)!important;max-width:calc(100vw - 14px)!important;padding:12px!important}#drawResultGrid{grid-template-columns:repeat(3,minmax(0,1fr))!important;gap:5px!important;padding:3px!important}#drawResultGrid .draw-card{padding:7px 3px!important;min-height:136px!important}#drawResultGrid .draw-card .rm-item-art{width:60px!important;height:60px!important}#drawResultGrid .draw-card strong{font-size:9px!important;line-height:12px!important;word-break:break-word!important}#drawResultGrid .draw-card small{font-size:7px!important;line-height:10px!important}.ringu-result-icon{width:52px!important;height:52px!important}}
`;
document.head.append(style);

function counts(){return (G()?.bossRegions||[]).map(r=>Array.isArray(r?.bosses)?r.bosses.length:0)}
function total(){return counts().reduce((a,b)=>a+b,0)}
function flat(region,boss){const c=counts();let n=0;for(let i=0;i<region;i++)n+=c[i]||0;return n+(Number(boss)||0)}
function locate(step){const c=counts();let n=Math.max(0,Number(step)||0);for(let r=0;r<c.length;r++){if(n<c[r])return{region:r,boss:n};n-=c[r]}return null}
function initProgress(){const s=S(),f=F();if(!s)return 0;const max=Math.max(0,total()-1);if(s.monsterProgressionVersion!==3){s.monsterProgressionVersion=3;s.monsterUnlockStep=0;s.regionIndex=0;s.bossIndex=0;try{f?.resetCombat?.()}catch{};try{f?.save?.(false)}catch{}}s.monsterUnlockStep=Math.max(0,Math.min(max,Number.isSafeInteger(s.monsterUnlockStep)?s.monsterUnlockStep:0));return s.monsterUnlockStep}
function unlockStep(){const s=S();if(!s)return 0;return Math.max(0,Math.min(Math.max(0,total()-1),Number.isSafeInteger(s.monsterUnlockStep)?s.monsterUnlockStep:0))}
function isUnlocked(region,boss){return flat(region,boss)<=unlockStep()}
function decorateLocks(){const s=S();if(!s)return;document.querySelectorAll('#regionTabs .region-tab').forEach((b,i)=>{const lock=!isUnlocked(i,0);b.disabled=lock;b.classList.toggle('ringu-region-locked',lock);b.setAttribute('aria-disabled',String(lock));b.textContent=(lock?'🔒 ':'')+b.textContent.replace(/^🔒\s*/,'')});document.querySelectorAll('#bossList .boss-btn').forEach((b,i)=>{const lock=!isUnlocked(Number(s.regionIndex)||0,i);b.disabled=lock;b.classList.toggle('ringu-monster-locked',lock);b.setAttribute('aria-disabled',String(lock));let tag=b.querySelector('.ringu-lock-tag');if(lock&&!tag){tag=document.createElement('span');tag.className='ringu-lock-tag';tag.textContent='🔒 이전 몬스터 처치 시 해금';b.append(tag)}else if(!lock&&tag)tag.remove()})}
function unlockNext(region,boss){const f=F(),s=S(),g=G();if(!f||!s||!g)return;const here=flat(region,boss),step=unlockStep();if(here!==step||step>=total()-1)return;s.monsterUnlockStep=step+1;const next=locate(step+1),name=next?g.bossRegions?.[next.region]?.bosses?.[next.boss]?.name:null;try{f.save?.(false)}catch{};try{f.renderBosses?.()}catch{};decorateLocks();try{f.toast?.('🔓 '+(name||'다음 몬스터')+' 해금!')}catch{}}

const labels=[[/보유\s*골드|^골드$/i,'🪙','골드'],[/^정수$/,'💎','정수'],[/초월석/,'🔷','초월석'],[/펫\s*스톤|펫스톤/,'🐾','펫스톤'],[/^공격력$/,'⚔️','공격력'],[/소환\s*Lv|소환\s*레벨|^소환$/i,'✦','소환']];
function decorateTop(){document.querySelectorAll('.stat-label').forEach(el=>{if(el.dataset.ringuLabeled)return;const text=(el.textContent||'').trim(),m=labels.find(([re])=>re.test(text));if(!m)return;el.dataset.ringuLabeled='1';el.classList.add('ringu-labeled');el.innerHTML='<span class="ringu-stat-icon" aria-hidden="true">'+m[1]+'</span><span>'+m[2]+'</span>'})}

function rankRows(){const g=G();return Array.isArray(g?.rankingProfiles)?[...g.rankingProfiles]:[]}
function renderRank(){const list=document.getElementById('rankList'),title=document.getElementById('rankingTitle'),note=document.getElementById('rankingNote'),p=document.getElementById('powerRankTab'),t=document.getElementById('towerRankTab');if(!list)return;let rows=rankRows();p?.classList.toggle('on',rankMode==='power');t?.classList.toggle('on',rankMode==='tower');if(title)title.textContent=rankMode==='tower'?'시련의 탑 랭킹':'전체 공격력 랭킹';if(note)note.textContent=rankMode==='tower'?'1층 이상 클리어한 플레이어만 최고 클리어 층 기준으로 등록됩니다.':'게임 접속 시 자동 등록되며, 기록은 60초마다 갱신됩니다.';if(rankMode==='tower')rows=rows.filter(x=>(Number(x.tower)||0)>=1).sort((a,b)=>(Number(b.tower)||0)-(Number(a.tower)||0)||(Number(b.power)||0)-(Number(a.power)||0));else rows.sort((a,b)=>(Number(b.power)||0)-(Number(a.power)||0));list.innerHTML=rows.length?rows.map((x,i)=>'<button class="rm-rank-row" onclick="openRankingCharacter('+i+')"><span>'+String(i+1).padStart(2,'0')+'</span><strong>'+String(x.name||'모험가').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))+'</strong><b>'+(rankMode==='tower'?'🏰 '+(Number(x.tower)||0)+'층':'⚔ '+Math.floor(Number(x.power)||0).toLocaleString('ko-KR'))+'</b></button>').join(''):'<p class="rm-note">표시할 랭킹 기록이 없습니다.</p>'}

function offlineBoss(){const f=F(),g=G(),s=S();try{const b=f?.offlineFarmBoss?.();if(b)return b}catch{}try{const b=f?.currentBoss?.();if(b)return b}catch{}return g?.bossRegions?.[Number(s?.regionIndex)||0]?.bosses?.[Number(s?.bossIndex)||0]||null}
function grantAway(){if(!hiddenAt)return;const f=F(),s=S();const left=hiddenAt;hiddenAt=0;if(!f||!s||!wasAuto)return;const away=Math.max(0,Math.min(43200,(Date.now()-left)/1000)),b=offlineBoss();if(away<1||!b)return;let power=1,bonus=0;try{power=Math.max(1,Number(f.getPower?.())||1)}catch{}try{bonus=Math.max(0,Number(f.getPlayerStats?.()?.goldBonus)||0)}catch{}const hits=Math.ceil((Number(b.hp)||0)/power);if(hits>15)return;const cycle=Math.max(1,Math.min(15,hits)),reward=Math.floor(Math.floor(away/cycle)*(Number(b.reward)||0)*(1+bonus/100));if(reward<=0)return;s.gold=(Number(s.gold)||0)+reward;try{f.resetCombat?.();f.renderAll?.();f.save?.(false)}catch{}const amount=document.getElementById('offlineGold'),modal=document.getElementById('offlineModal');if(amount)amount.textContent='+'+reward.toLocaleString('ko-KR')+' 골드';if(modal)modal.classList.add('show');else try{f.toast?.('오프라인 보상 +'+reward.toLocaleString('ko-KR')+' 골드')}catch{}}
function markAway(){if(hiddenAt)return;hiddenAt=Date.now();wasAuto=!!S()?.autoBattle;try{F()?.save?.(false)}catch{}}

function installDungeonDamage(){window.showDungeonDamage=function(damage){const host=document.getElementById('dungeonBossArt')||document.getElementById('dungeonBattle');if(!host)return;const el=document.createElement('div');el.className='dungeon-pop';el.textContent='-'+Math.floor(Number(damage)||0).toLocaleString('ko-KR');host.appendChild(el);setTimeout(()=>el.remove(),800)}}

function install(){if(installed||!G()||!F()||!S())return false;installed=true;const f=F(),g=G();initProgress();decorateLocks();decorateTop();installDungeonDamage();
 const rb=f.renderBosses;f.renderBosses=function(...args){const out=rb?.apply(this,args);decorateLocks();return out};
 const sr=f.selectRegion;f.selectRegion=function(i,...args){i=Number(i)||0;if(!isUnlocked(i,0)){f.toast?.('이전 지역의 마지막 몬스터를 먼저 처치하세요.');return false}return sr?.call(this,i,...args)};
 const sb=f.selectBoss;f.selectBoss=function(i,...args){i=Number(i)||0;if(!isUnlocked(Number(S()?.regionIndex)||0,i)){f.toast?.('이전 몬스터를 먼저 처치하세요.');return false}return sb?.call(this,i,...args)};
 const atk=f.attack;f.attack=function(...args){const s=S();if(document.hidden||hiddenAt)return false;if(!s||!isUnlocked(Number(s.regionIndex)||0,Number(s.bossIndex)||0)){f.toast?.('잠긴 몬스터는 공격할 수 없습니다.');return false}const region=Number(s.regionIndex)||0,boss=Number(s.bossIndex)||0,r=atk?.apply(this,args);for(const ms of [500,570,660])setTimeout(()=>{if(Number(g.combat?.hp)<=0)unlockNext(region,boss)},ms);return r};
 const top=f.renderTop;f.renderTop=function(...args){const r=top?.apply(this,args);decorateTop();return r};
 const sync=f.syncRanking;f.syncRanking=async function(...args){const r=await sync?.apply(this,args);renderRank();return r};
 window.switchRanking=function(mode){rankMode=mode==='tower'?'tower':'power';renderRank();return false};
 document.addEventListener('visibilitychange',()=>{if(document.hidden)markAway();else grantAway()},{capture:true});window.addEventListener('pagehide',markAway,{capture:true});window.addEventListener('pageshow',()=>{if(!document.hidden)grantAway()},{capture:true});
 try{f.renderBosses?.()}catch{};decorateLocks();return true}
window.addEventListener('ringu-ready',install,{once:true});setTimeout(install,0);setTimeout(install,1500);setTimeout(install,4000);
})();