import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
import assert from 'node:assert/strict';
import {investmentView} from './investment-ui.mjs';
import {adminPositionsView} from './admin-positions.mjs';
const db=new PGlite();
const admin='11111111-1111-4111-8111-111111111111',user='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,raw_app_meta_data jsonb);insert into auth.users values('${admin}','{"ringu_admin":true}'),('${user}','{}');create schema rebirth_private;grant usage on schema rebirth_private to authenticated;create table rebirth_private.players(id uuid primary key,state jsonb);insert into rebirth_private.players values('${admin}','{"name":"관리자","level":10}'),('${user}','{"name":"일반유저","level":20}');create table rebirth_private.coin_market(id integer,name text,price numeric);insert into rebirth_private.coin_market values(0,'도현코인',120);create table rebirth_private.coin_positions(id uuid,user_id uuid,coin integer,side text,amount numeric,entry numeric,quantity numeric,opened_at timestamptz,status text);insert into rebirth_private.coin_positions values(gen_random_uuid(),'${user}',0,'short',1000,100,10,now(),'open'),(gen_random_uuid(),'${user}',0,'long',1000,100,10,now(),'sold');create function rebirth_private.session_user() returns uuid language sql as $$select current_setting('test.actor')::uuid$$;create function rebirth_private.coin_tick() returns void language plpgsql as $$begin return;end $$;`);
await db.exec(readFileSync(new URL('./admin-positions.sql',import.meta.url),'utf8'));
await db.exec(`select set_config('test.actor','${user}',false);set role authenticated;`);
await assert.rejects(()=>db.query('select public.rebirth_admin_positions()'),/BETA_DISABLED/);
await db.exec(`reset role;select set_config('test.actor','${admin}',false);set role authenticated;`);
const data=(await db.query('select public.rebirth_admin_positions() d')).rows[0].d;
assert.equal(data.users.length,2);const ordinary=data.users.find(u=>u.id===user);assert.equal(ordinary.positions.length,1);assert.equal(ordinary.positions[0].side,'short');assert.equal(data.users.find(u=>u.id===admin).positions.length,0);
const html=adminPositionsView(data);assert.ok(html.includes('일반유저'));assert.ok(html.includes('-200 G'));assert.ok(!investmentView({},null).includes('data-action="adminPositions"'));assert.ok(investmentView({isAdmin:true},null).includes('data-action="adminPositions"'));
await db.exec(`reset role;update auth.users set raw_app_meta_data='{}' where id='${admin}';set role authenticated;`);await assert.rejects(()=>db.query('select public.rebirth_admin_positions()'),/BETA_DISABLED/);
await db.exec('reset role;set role anon;');await assert.rejects(()=>db.query('select public.rebirth_admin_positions()'),/permission denied/);
console.log('PASS admin-only read, ordinary/anonymous/revoked admin blocked, all users, open positions only, side and PnL, hidden ordinary button');
await db.close();
