import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';
import {investmentView} from './investment-ui.mjs';
const db=new PGlite(),u='11111111-1111-4111-8111-111111111111';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key,raw_app_meta_data jsonb);insert into auth.users values('${u}','{}');create schema rebirth_private;grant usage on schema rebirth_private to authenticated;create table rebirth_private.players(id uuid primary key,state jsonb,revision bigint default 0,updated_at timestamptz);create table rebirth_private.receipts(user_id uuid,request_id uuid,fingerprint jsonb,result jsonb);create function rebirth_private.session_user() returns uuid language sql as $$select '${u}'::uuid$$;`);
const source=fs.readFileSync(new URL('./investment.sql',import.meta.url),'utf8');await db.exec(source.split('select cron.schedule')[0]);await db.exec(fs.readFileSync(new URL('./investment-news.sql',import.meta.url),'utf8'));await db.exec(fs.readFileSync(new URL('./admin-coin-direction.sql',import.meta.url),'utf8'));
const tick=source.slice(source.indexOf('create or replace function rebirth_private.coin_tick()'),source.indexOf('revoke all on function rebirth_private.coin_tick()')).replace('clock_timestamp()',"current_setting('test.coin_now')::timestamptz");await db.exec(tick);
await db.exec(`create or replace function rebirth_private.coin_news_schedule(p_day date,p_from integer default 0) returns void language plpgsql as $$begin return;end $$;select set_config('test.coin_now','2026-10-04 03:01:00+00',false);update rebirth_private.coin_market set price=1000,day_base=1000,day_key='2026-10-04',tick_at='2026-10-04 03:00:00+00';`);
await db.exec('set role authenticated');await assert.rejects(()=>db.query("select public.rebirth_admin_coin_direction(0,'long')"),/BETA_DISABLED/);await db.exec(`reset role;update auth.users set raw_app_meta_data='{"ringu_admin":true}';set role authenticated;`);
await assert.rejects(()=>db.query("select public.rebirth_admin_coin_direction(8,'long')"),/INVALID_COIN_DIRECTION/);
await db.query("select public.rebirth_admin_coin_direction(0,'short')");await db.query("select public.rebirth_admin_coin_direction(0,'long')");await db.query("select public.rebirth_admin_coin_direction(1,'short')");await db.exec('reset role');
assert.equal((await db.query('select count(*) n from rebirth_private.coin_next_direction')).rows[0].n,2);
// An intervening news event must not consume the next normal candle override.
await db.exec(`insert into rebirth_private.coin_news_days values('2026-10-04');insert into rebirth_private.coin_news(day,coin,catalog,published_at,expires_at,boost) values('2026-10-04',0,1,'2026-10-04 03:10:00+00','2026-10-04 11:10:00+00',.1);select set_config('test.coin_now','2026-10-04 03:10:00+00',false);select rebirth_private.coin_tick();`);
assert.equal((await db.query('select count(*) n from rebirth_private.coin_next_direction')).rows[0].n,2);const newsPrice=Number((await db.query('select price from rebirth_private.coin_market where id=0')).rows[0].price);
await db.exec("select set_config('test.coin_now','2026-10-04 03:30:00+00',false);select rebirth_private.coin_tick();");const coins=(await db.query('select * from rebirth_private.coin_market order by id')).rows;assert.ok(Number(coins[0].price)>newsPrice);assert.ok(Number(coins[1].price)<1000);assert.equal((await db.query('select count(*) n from rebirth_private.coin_next_direction')).rows[0].n,0);await db.exec('select rebirth_private.coin_tick()');assert.deepEqual((await db.query('select price from rebirth_private.coin_market order by id')).rows,coins.map(c=>({price:c.price})));
await db.exec("update rebirth_private.coin_market set price=1300 where id=0;set role authenticated;");await assert.rejects(()=>db.query("select public.rebirth_admin_coin_direction(0,'long')"),/COIN_DAILY_LIMIT/);await db.exec('reset role;set role anon;');await assert.rejects(()=>db.query("select public.rebirth_admin_coin_direction(0,'long')"),/permission denied/);await db.exec('reset role');
const model={coins:Array.from({length:8},(_,id)=>({id,name:'코인',price:1000,dayBase:1000,candles:[]})),positions:[]};assert.ok(!investmentView({},model).includes('adminCoinDirection'));assert.equal((investmentView({isAdmin:true},model).match(/data-action="adminCoinDirection"/g)||[]).length,16);
console.log('PASS trusted admin permission, hidden buttons, 8 coin controls, latest selection wins, news does not consume, next candle up/down, once only, daily cap and anonymous denial');await db.close();
