import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
import {initialState,execute,power} from './engine.mjs';
import {newTowerBattle,canOpenChest} from './tower-model.mjs';
import {BOSSES} from './data.mjs';
const ctx={now:1000,random:()=>.99,uuid:()=> 'chest-test'};
function seed(){
 const s=initialState('warrior','상자테스트',ctx),boss=BOSSES.find(b=>b.weekly);
 s.hunting=false;s.battle=newTowerBattle(boss.region+1,'warrior',power(s),0,'run',1,true);
 Object.assign(s.battle,{weeklyBossId:boss.id,won:true,ended:true,enemyHp:0,chest:{x:1600,y:1500}});
 Object.assign(s.battle.player,{x:1850,y:1500});return s;
}
const state=seed(),frames=Array.from({length:6},()=>[-1,0,0]),args={runId:'run',from:0,frames};
assert.equal(canOpenChest(state.battle),false);
const moved=execute(state,'towerInput',args,ctx).state;
assert.equal(canOpenChest(moved.battle),true);
const old=execute(moved,'towerOpen',{runId:'run'},ctx);
const combined=execute(state,'towerOpen',args,ctx);
assert.deepEqual(combined,old,'one request preserves movement, range checks and rewards');
assert.equal(combined.state.battle,null);
assert.equal(execute(combined.state,'towerOpen',args,ctx).events.length,0,'retry cannot grant rewards twice');
assert.throws(()=>execute(state,'towerOpen',{...args,runId:'other'},ctx),/INVALID_TOWER_RUN/);
assert.throws(()=>execute(state,'towerOpen',{...args,frames:[[2,0,0]]},ctx),/INVALID_TOWER_INPUT/);
assert.throws(()=>execute(state,'towerOpen',{...args,frames:Array(31).fill([0,0,0])},ctx),/INVALID_TOWER_INPUT/);
assert.throws(()=>execute(state,'towerOpen',{...args,frames:[]},ctx),/ITEM_CHEST_TOO_FAR/);
assert.throws(()=>execute(state,'towerOpen',args,{...ctx,now:0}),/ITEM_CHEST_TOO_FAR/,'future movement cannot open an out-of-range chest');
const fighting=seed();Object.assign(fighting.battle,{won:false,ended:false,enemyHp:1});delete fighting.battle.chest;
Object.assign(fighting.battle.player,{x:1600,y:1680});
const killed=execute(fighting,'towerOpen',{runId:'run',from:0,frames:[[0,0,1],[0,0,1],[0,0,1],[0,-1,0],[0,-1,0],[0,-1,0]]},ctx);
assert.equal(killed.state.battle,null,'unacknowledged final hit and chest claim settle together');
const source=readFileSync(new URL('./tower-controller.mjs',import.meta.url),'utf8').replace(/^import .*;\n/gm,'').replace(/^export /gm,'');
const Controller=vm.runInNewContext(source+'\nTowerController;',{performance,canOpenChest,Promise,Math});
let resolveInput,resolveClaim,calls=0;
const c=Object.assign(Object.create(Controller.prototype),{b:moved.battle,frames:[],serverTick:6,failures:0,retryAfter:0,pending:true,inputDone:new Promise(r=>{resolveInput=r;}),send:async(command,args)=>{assert.equal(command,'towerOpen');assert.equal(args.from,6);calls++;await new Promise(r=>{resolveClaim=r;});return {state:{battle:null}};}});
const opening=c.openChest();assert.equal(typeof c.b.chest.openAt,'number','animation begins immediately, even with input in flight');assert.equal(calls,0);
resolveInput();await new Promise(setImmediate);assert.equal(calls,1,'claim goes out directly after pending input, without a timer or extra flush');
await c.openChest();assert.equal(calls,1,'repeat clicks cannot send concurrent claims');
resolveClaim();await opening;assert.equal(c.openingRequest,false);
console.log('PASS: combined final hit/movement/claim, range and clock validation, duplicate rewards, immediate animation and one queued claim.');
