import assert from 'node:assert/strict';
import {performance} from 'node:perf_hooks';
import {startCoop,advanceCoop,advanceCoopRaw,coopClientView,predictCoopStep} from './coop-model.mjs';
import {EXPLORATIONS,explorationStats,explorationFloor,explorationProgress} from './exploration-data.mjs';
import {grantExplorationChest} from './exploration-rewards.mjs';
const build={attack:49108,hp:67525,defense:1373,crit:.41,critDamage:1.6,boss:3.2,cadence:1,advancement:4,firstJob:true,level:200,combatPower:206123};
const create=(tier=0,count=1)=>{const w=startCoop({mode:'exploration',tier,status:'waiting',owner:'p0',id:'room',members:Array.from({length:count},(_,i)=>({id:'p'+i,name:'테스트'+i,classId:['warrior','mage','archer','priest'][i],power:structuredClone(build),advanced:true,ready:true,left:false}))},0);w.entryWaiting=false;return w;};
assert.deepEqual(EXPLORATIONS.map(x=>x.floors),[10,11,12]);
for(const tier of [1,2]){const a=explorationStats(tier-1,EXPLORATIONS[tier-1].floors,1,true),b=explorationStats(tier,EXPLORATIONS[tier].floors,1,true);assert.equal(b.hp/a.hp,1.5);assert.ok(Math.abs(b.attack/a.attack-1.5)<.0001);}
for(const n of [1,2,3,4]){const w=create(0,n);assert.equal(w.population,n);if(n>1)assert.ok(w.monsters[0].hp>create(0,n-1).monsters[0].hp);w.members[n-1].left=true;const frozen=w.population;explorationFloor(w);assert.equal(w.population,frozen);}
assert.throws(()=>create(0,5),/PLAYERS/);
for(const tier of [0,1,2]){const w=create(tier);for(let f=1;f<=EXPLORATIONS[tier].floors;f++){assert.equal(w.floor,f);assert.equal(w.monsters.some(e=>e.boss),f===EXPLORATIONS[tier].floors);const last=w.monsters.at(-1);w.monsters=[last];explorationProgress(w);assert.equal(w.exitOpen,false);last.hp=0;w.monsters=[];w.tick+=123;const t=w.tick;explorationProgress(w);assert.equal(w.cleared,f);if(f<EXPLORATIONS[tier].floors){assert.equal(w.floor,f);w.members[0].x=w.exit.x;w.members[0].y=w.exit.y;explorationProgress(w);assert.equal(w.floor,f+1);assert.equal(w.tick,t);assert.ok(w.monsters.length);assert.equal(w.exitOpen,false);}else assert.equal(w.status,'won');}const me=w.members[0];const x=me.x;advanceCoopRaw(w,me.id,[1,0,0],w.tick*100+100,[],true);advanceCoopRaw(w,me.id,[1,0,0],w.tick*100+200,[],true);assert.ok(me.x>x,'winner can walk to chest');const result=grantExplorationChest({gold:0,materials:{}},w,{now:0});assert.equal(result.state.gold,EXPLORATIONS[tier].gold);assert.deepEqual(result.state.exploration.cleared,[tier]);}
const timeout=create();timeout.floorDeadline=0;explorationProgress(timeout);assert.equal(timeout.status,'lost');assert.equal(timeout.reason,'floorTimeout');
const w=create(0,4);for(const m of w.members)m.immune=1e8;let world=w;const before=performance.now();for(let tick=0;tick<1200;tick++){const frames=world.members.map((m,i)=>({user:m.id,tick,input:[Math.sin(tick/80+i)*.3,Math.cos(tick/90+i)*.3,123]}));world=advanceCoopRaw(world,null,null,(tick+1)*100,frames,true);if(world.status!=='fighting')break;}const elapsed=performance.now()-before;assert.ok(world.tick>900,'multiple floors not capped at legacy 90 sec');assert.ok(world.effects.length<=100);assert.ok(world.numbers.length<=100);assert.ok(world.monsters.length<=11);assert.ok(elapsed<4000);
// Late frame replay converges, retaining all four players' inputs.
const timeline=create(0,4);const frames=[];for(let tick=0;tick<15;tick++)frames.push({tick,input:[.2,0,1]});const early=advanceCoop(timeline,'p0',{frames},1500);const late=advanceCoop(advanceCoop(timeline,'p0',{frames:[]},1500),'p0',{frames},1500);assert.equal(late.members[0].x,early.members[0].x);assert.equal(late.members[0].damage,early.members[0].damage);const view=coopClientView({...late,me:'p0'},2);assert.ok(view.predictionBase?view.protocol===2:view.tick===15);
console.log('PASS exploration: 10/11/12 floors, all-kill gate, monotonic timeline, boss-only bonuses, population frozen, 50% theme progression, timeout, chest/reward, delayed replay, bounded 4-player simulation '+elapsed.toFixed(1)+'ms/1200 ticks');
