// Shared with the authenticated server. Fish use gold; bait bundles use diamonds. Weight is grams.
export const FISHING_VERSION=1;
export const RARITIES=[{name:'일반',color:'#d8e7d1',gate:1,price:300},{name:'희귀',color:'#8de6ad',gate:1,price:1200},{name:'레어',color:'#74caff',gate:10,price:4000},{name:'에픽',color:'#cf9cff',gate:20,price:15000},{name:'전설',color:'#ffd477',gate:35,price:65000},{name:'신화',color:'#ff95c8',gate:45,price:300000}];
export const SPOTS=[
 {id:'brook',name:'숲속 여울',level:1,subtitle:'햇살이 머무는 작은 숲',accent:'#a6edac'},
 {id:'moon',name:'달빛 호수',level:10,subtitle:'달의 조각이 잠든 물결',accent:'#a4cbff'},
 {id:'canyon',name:'단풍 협곡',level:20,subtitle:'붉은 잎 사이 흐르는 비밀',accent:'#ffc891'},
 {id:'coral',name:'산호 해안',level:30,subtitle:'노을빛 바다의 보물',accent:'#8cf0e7'},
 {id:'abyss',name:'천상의 심해',level:40,subtitle:'별과 바다가 만나는 끝',accent:'#d8a6ff'},
];
const rows=[
 ['brook','풀잎 피라미',0,80,300,'leaf green minnow with gold fins'],['brook','은빛 송사리',0,20,120,'tiny silver ricefish with pale green fins'],['brook','조약돌 망둑어',0,100,450,'round speckled stone goby'],['brook','햇살 붕어',0,250,1500,'warm golden crucian carp'],['brook','산들 메기',0,400,2500,'cute moss grey catfish with flowing whiskers'],['brook','꽃잎 잉어',0,300,2000,'pink white koi with petal shaped fins'],['brook','이끼 비늘어',1,400,2500,'emerald moss scaled fish'],['brook','청금 송어',1,700,3500,'turquoise trout with golden flecks'],['brook','반딧불 버들치',1,120,800,'willow minnow with luminous yellow speckles'],['brook','수련 베타',1,100,600,'jade pink betta with lotus petal fins'],
 ['moon','달그림자 빙어',0,50,350,'silver blue smelt'],['moon','푸른 지느러미어',0,200,1100,'blue fin lake perch'],['moon','물방울 정어리',0,80,500,'rounded pale blue sardine'],['moon','밤안개 장어',0,400,2200,'deep blue eel with silver stripe'],['moon','유리 비늘어',1,150,1000,'translucent glass scaled blue fish'],['moon','초승달 붕어',1,600,3000,'navy silver crescent marked carp'],['moon','진주 가시어',1,200,1200,'pearl white fish with violet spines'],['moon','달꽃 구라미',1,250,1800,'lavender gourami with moonflower fins'],['moon','월광 나비어',2,600,3500,'luminous sapphire butterfly fish'],['moon','별무늬 철갑어',2,2000,14000,'silver sturgeon with constellation specks'],
 ['canyon','단풍 피라미',0,100,500,'orange red minnow'],['canyon','노을 농어',0,500,3000,'amber sunset perch'],['canyon','황토 메기',1,800,5000,'rust brown gold catfish'],['canyon','호박빛 잉어',1,700,4000,'amber gemstone scaled koi'],['canyon','홍엽 송어',1,600,3500,'crimson trout with leaf shaped fins'],['canyon','협곡 칼날어',2,1000,6500,'copper fish with sharp blade shaped dorsal fin'],['canyon','비단 리본어',2,700,4500,'red gold ribbon fish with flowing silk fins'],['canyon','불씨 복어',2,300,1600,'round orange puffer with glowing ember freckles'],['canyon','백금 연어',2,1500,9000,'platinum salmon with red accents'],['canyon','홍련 용어',3,3000,18000,'small crimson dragon fish with flowing golden horns'],
 ['coral','산호 앵무어',2,800,5000,'vivid coral pink turquoise parrotfish'],['coral','파도 돛새치',2,4000,24000,'teal sailfish with ocean blue sail'],['coral','자수정 해마',2,100,650,'amethyst purple jeweled seahorse'],['coral','오팔 가오리',2,1500,10000,'opal rainbow spotted stingray'],['coral','태양 산호어',3,1500,9000,'golden solar fish with coral branching fins'],['coral','청옥 만타',3,5000,35000,'jade turquoise manta ray'],['coral','인어의 진주어',3,1200,7500,'iridescent pearl fish with long flowing white fins'],['coral','폭풍 창꼬치',3,3000,20000,'dark turquoise barracuda with electric gold fins'],['coral','무지개 해룡',3,2000,14000,'iridescent rainbow sea dragon'],['coral','황금 왕관고래',4,12000,90000,'majestic small gold whale with coral crown'],
 ['abyss','별빛 아귀',3,1500,10000,'indigo anglerfish with glowing star lure'],['abyss','오로라 유령어',3,1000,7000,'translucent violet aurora fish'],['abyss','공허 문어',3,3000,24000,'cute cosmic purple octopus with star markings'],['abyss','천공 수정어',3,2000,16000,'icy celestial crystal scaled fish'],['abyss','달의 수호룡',4,10000,65000,'silver blue moon guardian sea dragon'],['abyss','태고의 황제어',4,9000,60000,'ancient imperial indigo fish with gold armor scales'],['abyss','성운 날개가오리',4,8000,55000,'nebula violet manta with angel wing fins'],['abyss','심연의 왕관상어',4,14000,100000,'deep purple shark with luminous crystalline crown'],['abyss','천해의 별고래',5,35000,240000,'mythical celestial star whale, sapphire gold, galaxy wings'],['abyss','영원의 백룡',5,25000,180000,'mythical elegant white sea dragon, luminous pink gold flowing fins'],
];
export const FISH=rows.map(([spot,name,rarity,min,max,art],i)=>({id:'fish-'+String(i+1).padStart(2,'0'),spot,name,rarity,min,max,art,level:Math.max(SPOTS.find(s=>s.id===spot).level,RARITIES[rarity].gate)}));
export const BAITS=[{id:'worm',name:'숲 지렁이',pack:50,diamonds:1,level:1,luck:0},{id:'shrimp',name:'반짝 새우',pack:40,diamonds:1,level:10,luck:.25},{id:'pearl',name:'진주 미끼',pack:30,diamonds:1,level:25,luck:.65},{id:'star',name:'별가루 미끼',pack:20,diamonds:1,level:40,luck:1}];
export const baitDiamondCost=(bait,count)=>bait.diamonds*count/bait.pack;
export const FISHING_QUESTS=[{id:'catch',name:'물고기 10마리 잡기',goal:10,diamonds:3},{id:'rare',name:'희귀 이상 물고기 3마리',goal:3,diamonds:2},{id:'sell',name:'물고기 5마리 판매',goal:5,diamonds:2}];
export const REWARD_RATES=[{id:'fish',name:'물고기',chance:.94},{id:'diamondChest',name:'다이아 상자',chance:.015},{id:'cube',name:'레드 큐브',chance:.020},{id:'scroll',name:'잠재 해금 주문서',chance:.010},{id:'potentialLock',name:'잠재 잠금석',chance:.010},{id:'dungeonKey',name:'던전 열쇠',chance:.005}];
export const rodGoldCost=level=>Math.round(20000*1.17**(level-1)/100)*100;
export const rodDiamondCost=level=>2+Math.floor(level/5);
export const fishPrice=fish=>{const d=FISH.find(x=>x.id===fish.species);return d?Math.round(RARITIES[d.rarity].price*(.55+1.45*fish.weight/d.max)):0;};
export const fishYield=fish=>Math.max(1,Math.floor(fishPrice(fish)*.015)); // gold/hour, 12-hour offline cap
export const fishWeight=grams=>grams>=1000?(grams/1000).toFixed(2)+' kg':grams+' g';
export const resourceName=id=>({diamond:'다이아',diamondChest:'다이아 상자',potentialLock:'잠재 잠금석',dungeonKey:'던전 열쇠',cube:'레드 큐브',scroll:'잠재 해금 주문서'}[id]||id);
