import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {initialState,execute,makeItem,power} from './engine.mjs';import {CUBE_UP,HIGH_CUBE_UP,CUBE_DROP,FRAGMENT_DROP,SCROLL_DROP,STAGES,gearAttributes,OPTION_WEIGHTS,FLAT_HP_RANGES,optionRange,rollEquipmentLevel,equipmentKey,equipmentIdentity} from './data.mjs';
const ctx={now:0,random:()=>.5,uuid:randomUUID};
assert.equal(CUBE_DROP,.008/3);assert.equal(FRAGMENT_DROP,.035);assert.equal(SCROLL_DROP,.0007);assert.deepEqual(CUBE_UP,[.2,.02,.002,.0002,.00002,0]);assert.deepEqual(HIGH_CUBE_UP,CUBE_UP.map(p=>p*2));assert.equal(Object.values(OPTION_WEIGHTS).reduce((a,b)=>a+b,0),100);for(const st of STAGES)assert.equal(st.gold,(20+st.region*35)*.3);
for(const [base,min,max]of [[1,1,19],[40,40,59],[120,120,139],[180,180,199],[200,190,200]]){const levels=new Set();for(let i=0;i<10000;i++)levels.add(rollEquipmentLevel(base,()=>i/10000));assert.deepEqual([...levels],Array.from({length:max-min+1},(_,i)=>min+i));}
for(const lv of [12,45,123,196])for(const boss of [false,true]){const it=makeItem(lv,'warrior',1,boss,ctx);assert.equal(equipmentKey(it),equipmentKey({...it,level:Math.max(1,Math.floor(lv/20)*20)}));assert.ok(equipmentIdentity(it).name);const before=gearAttributes(it),after=gearAttributes({...it,stars:1});assert.equal(after.hp-before.hp,Math.max(2,Math.ceil(lv*.35)));}
for(const slot of [0,6,7,8]){const it=makeItem(123,'mage',slot,false,ctx);assert.equal(gearAttributes({...it,stars:10}).hp,gearAttributes(it).hp);}
let s=initialState('mage','체력검증',ctx);s.hunting=false;const it=s.items[0];it.lines=[{key:'flatHP',grade:2,value:100},{key:'hp',grade:2,value:10}];const expected=Math.floor((100+22+4+100)*1.1);assert.equal(power(s).hp,expected);for(let g=0;g<6;g++)assert.deepEqual(optionRange('flatHP',g),{min:FLAT_HP_RANGES[g][0],max:FLAT_HP_RANGES[g][1],step:1});
const armor=makeItem(45,'mage',1,false,ctx);s.items.push(armor);s.gold=100000;s.materials.fragment=0;let r=execute(s,'star',{id:armor.id},{...ctx,random:()=>0});assert.equal(r.events.find(x=>x.type==='star').gains.hp,16);r=execute(s,'salvage',{ids:[armor.id]},ctx);assert.deepEqual(r.events.find(x=>x.type==='salvage'),{type:'salvage',count:1,fragments:3});assert.equal(r.state.materials.fragment,3);
const broken=makeItem(45,'mage',1,false,ctx),material=makeItem(59,'mage',1,false,ctx);broken.broken=true;s.items.push(broken,material);r=execute(s,'restore',{id:broken.id,materialId:material.id},ctx);assert.equal(r.state.items.find(x=>x.id===broken.id).level,45);assert.equal(r.state.items.find(x=>x.id===broken.id).stars,12);
const crafter=initialState('mage','제작검증',ctx);crafter.hunting=false;crafter.cleared=[0];crafter.gold=10000;crafter.materials.fragment=60;crafter.bossMaterials[0]=24;
const crafted=execute(crafter,'craft',{region:0,slot:1},ctx);const craftedId=crafted.events.find(e=>e.type==='craft').id;assert.equal(crafted.state.items.find(i=>i.id===craftedId).level,25);
console.log('PASS flexible levels, lower field economy with unchanged cube ranks, fixed/% HP, armor HP per star, salvage receipt, random-level crafting and level-band restoration');
