import {PGlite} from '@electric-sql/pglite';import fs from 'node:fs';import assert from 'node:assert/strict';
const db=new PGlite();const u='11111111-1111-4111-8111-111111111111',other='22222222-2222-4222-8222-222222222222';
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);insert into auth.users values('${u}'),('${other}');create schema rebirth_private;create table rebirth_private.players(id uuid primary key,state jsonb,revision bigint default 0,updated_at timestamptz);create table rebirth_private.receipts(user_id uuid,request_id uuid,fingerprint jsonb,result jsonb,primary key(user_id,request_id));create function rebirth_private.session_user() returns uuid language sql as $$select '${u}'::uuid$$;insert into rebirth_private.players values('${u}','{"gold":100000,"battle":null}',0,now());`);
await db.exec(fs.readFileSync(new URL('./investment.sql',import.meta.url),'utf8').split("select cron.schedule")[0]);
async function trade(action,args={},request=crypto.randomUUID()){return (await db.query('select rebirth_private.investment($1,$2::jsonb,$3::uuid) r',[action,JSON.stringify(args),request])).rows[0].r;}
let r=await trade('list');assert.equal(r.investment.coins.length,8);const tick=r.investment.coins[0].tickAt;
const request=crypto.randomUUID(),args={coin:0,side:'long',quantity:10,tickAt:tick};r=await trade('buy',args,request);assert.equal(r.state.gold,90000);const id=r.investment.positions[0].id;r=await trade('buy',args,request);assert.equal(r.state.gold,90000);assert.equal(r.investment.positions.length,1);
await db.exec('update rebirth_private.coin_market set price=1100 where id=0');r=await trade('sell',{position:id,tickAt:tick});assert.equal(r.state.gold,100890);assert.equal(r.result.events[0].fee,110);await assert.rejects(()=>trade('sell',{position:id,tickAt:tick}));
r=await trade('buy',{coin:0,side:'short',quantity:10,tickAt:tick});const short=r.investment.positions[0].id;await db.exec('update rebirth_private.coin_market set price=990 where id=0');r=await trade('sell',{position:short,tickAt:tick});assert.equal(r.state.gold,101869);
await assert.rejects(()=>trade('buy',{coin:0,side:'long',quantity:-1,tickAt:tick}));await assert.rejects(()=>trade('buy',{coin:0,side:'long',quantity:999999999,tickAt:tick}));await assert.rejects(()=>trade('buy',{coin:0,side:'long',quantity:1,tickAt:'2020-01-01'}));
await db.exec(`insert into rebirth_private.coin_positions(user_id,coin,side,amount,entry) values('${other}',0,'long',10,1000)`);const foreign=(await db.query(`select id from rebirth_private.coin_positions where user_id='${other}'`)).rows[0].id;await assert.rejects(()=>trade('sell',{position:foreign,tickAt:tick}));
await db.exec(`update rebirth_private.coin_market set tick_at=date_trunc('hour',now())-interval '72 hours',day_key=(now()-interval '72 hours')::date,price=1000,day_base=1000;select rebirth_private.coin_tick();`);
await assert.rejects(()=>trade('buy',{coin:0,side:'long',quantity:1.5,tickAt:tick}));
const rows=(await db.query('select * from rebirth_private.coin_candles order by coin,at')).rows;assert.equal(rows.length,576);for(const x of rows)assert.ok(Math.abs(Number(x.close)/Number(x.open)-1)<=.050001);
const groups=new Map();for(const x of rows){const day=new Date(new Date(x.at).getTime()+9*3600000).toISOString().slice(0,10),key=x.coin+day;if(!groups.has(key))groups.set(key,Number(x.open));const base=groups.get(key);assert.ok(Number(x.close)>=base*.7-.00001&&Number(x.close)<=base*1.3+.00001);}
await db.exec(`insert into rebirth_private.coin_positions(user_id,coin,side,amount,entry) values('${u}',0,'short',1000,1);update rebirth_private.coin_market set tick_at=tick_at-interval '1 hour';select rebirth_private.coin_tick();`);assert.equal((await db.query('select status from rebirth_private.coin_positions where entry=1')).rows[0].status,'liquidated');
console.log('PASS: long/short settlement, 1% fee, idempotency, ownership, insufficient gold, stale quote, 72-hour limits and liquidation');await db.close();
