-- Shared secret daily schedules. Only published headlines leave the server.
create table if not exists rebirth_private.coin_news_catalog(id integer primary key,kind text not null check(kind in ('good','bad')),headline text not null);
create table if not exists rebirth_private.coin_news_days(day date primary key);
create table if not exists rebirth_private.coin_news(id uuid primary key default gen_random_uuid(),day date not null references rebirth_private.coin_news_days(day),coin integer not null references rebirth_private.coin_market(id),catalog integer not null references rebirth_private.coin_news_catalog(id),published_at timestamptz not null,expires_at timestamptz not null,applied_at timestamptz,instant_change numeric,boost numeric not null check(boost between .10 and .30),unique(day,published_at),check(expires_at=published_at+interval '8 hours'));
create index if not exists coin_news_time on rebirth_private.coin_news(coin,published_at,expires_at);
create index if not exists coin_news_unapplied on rebirth_private.coin_news(coin,published_at) where applied_at is null;
alter table rebirth_private.coin_news_catalog enable row level security;
alter table rebirth_private.coin_news_days enable row level security;
alter table rebirth_private.coin_news enable row level security;
revoke all on rebirth_private.coin_news_catalog,rebirth_private.coin_news_days,rebirth_private.coin_news from public,anon,authenticated;
insert into rebirth_private.coin_news_catalog(id,kind,headline) values
(1,'good','국왕이 몰래 샀다가 왕실 단톡방에 걸림'),
(2,'good','드래곤이 보물 대신 코인 모으기 시작'),
(3,'good','고블린도 적금 깨고 매수 대기'),
(4,'good','개발자 출근 확인… 투자자들 기립박수'),
(5,'good','운영진이 비밀번호 기억해 냄'),
(6,'good','왕실 재무관 “이거 느낌이 온다”'),
(7,'good','상인 길드 회장이 집문서 들고 등장'),
(8,'good','마왕이 숏 팔고 롱으로 갈아탐'),
(9,'good','예언자가 수정구슬 대신 매수 버튼 누름'),
(10,'good','직원이 실수로 좋은 소식 공개'),
(11,'good','용사가 보상 골드 전부 투자했다는 소문'),
(12,'good','대장장이가 망치 내려놓고 차트 보기 시작'),
(13,'good','드래곤 보물창고에서 대규모 매수 주문 발견'),
(14,'good','왕비의 비상금 유입 정황 포착'),
(15,'good','고블린 투자 설명회에 오크까지 참석'),
(16,'good','운영진 회식비 아껴서 개발비 확보'),
(17,'good','마법사가 오류를 진짜 마법으로 고침'),
(18,'good','신규 서버에 성수 뿌린 뒤 속도 개선'),
(19,'good','사제가 축복하다가 매수 주문까지 넣음'),
(20,'good','왕실 결제 채택… 세금도 코인으로 받는다'),
(21,'good','드래곤 “내 둥지에서도 결제 가능”'),
(22,'good','마왕성 매점에서 최초 결제 성공'),
(23,'good','포션값 결제 지원… 모험가들 지갑 개방'),
(24,'good','여관 주인 “외상 말고 코인 받습니다”'),
(25,'good','던전 입장료 채택… 해골도 관심'),
(26,'good','순간이동 결제 지원… 걸을 이유 사라져'),
(27,'good','대장간 결제 도입… 망치질보다 거래량 폭발'),
(28,'good','펫 간식 결제 지원… 주인보다 펫이 좋아함'),
(29,'good','길드 회비 통화로 선정… 총무 웃음 못 숨겨'),
(30,'good','왕실 식당 채택… 국왕 디저트 추가 주문'),
(31,'good','대륙 최대 상단 “일단 사고 생각하겠다”'),
(32,'good','거물 투자자 지갑 열리자 경첩 소리 울려'),
(33,'good','고래 등장… 어부들은 진짜 고래인 줄 착각'),
(34,'good','매도벽 사라져… 철거 길드 공로 인정'),
(35,'good','기관 투자자 입장에 의자부터 부족'),
(36,'good','장기 투자자 “비밀번호 까먹어서 못 판다”'),
(37,'good','매수 주문 너무 많아 접수 번호표 배부'),
(38,'good','투자 설명회 앞줄에 드래곤 세 마리 착석'),
(39,'good','은행장이 퇴근 후 개인 계정으로 접속'),
(40,'good','왕실 금고지기 “오늘은 문 열어둡니다”'),
(41,'good','광산에서 금맥 발견… 광부 사표 찢어'),
(42,'good','마법석 주문 폭주… 마법사 야근 확정'),
(43,'good','무역선 만선 귀환… 선장 웃다가 턱 빠져'),
(44,'good','신규 사업 대박… 회계사 계산기에서 연기'),
(45,'good','매출 신기록에 장부 한 권 추가 구매'),
(46,'good','적자 탈출… 회계사가 처음으로 점심 먹음'),
(47,'good','부채 상환 완료… 채권자도 박수'),
(48,'good','준비금 확충… 금고 닫다가 골드 끼임'),
(49,'good','투자 유치 성공… 대표 말투 갑자기 정중해져'),
(50,'good','실적 발표 후 회식 메뉴 죽에서 고기로 변경'),
(51,'good','보안 감사 통과… 도둑 길드 공식 항의'),
(52,'good','해커 침입 실패 후 고객센터에 문의'),
(53,'good','거래 속도 개선… 비둘기보다 빠르다'),
(54,'good','서버 증설… 선풍기 두 대 추가'),
(55,'good','개발자 커피 확보로 업데이트 정상화'),
(56,'good','버그 수정 완료… 버그가 퇴사 처리됨'),
(57,'good','지갑 복구 성공… 이용자 기억력까지 회복'),
(58,'good','거래 오류 해결… 새로고침 담당자 휴가'),
(59,'good','기술 특허 획득… 마법사 협회 눈치 보기 시작'),
(60,'good','새 기능 공개… 운영진도 사용법 알고 있어'),
(61,'good','국왕 연설에서 이름 세 번 언급'),
(62,'good','유명 용사 추천… 검보다 지갑 먼저 꺼냄'),
(63,'good','마왕 “적이지만 사업은 인정”'),
(64,'good','엘프 투자단 합류… 최소 보유 기간 300년'),
(65,'good','드워프 은행 승인… 도장 찍다 책상 부서져'),
(66,'good','오크 길드 공동 매수… 설명은 못 알아들었다'),
(67,'good','사제단 축복 승인… 성수 리필 요청'),
(68,'good','왕실 행사 후원… 현수막 크기 성벽급'),
(69,'good','대륙 신문 1면 장식… 마왕 기사 밀려나'),
(70,'good','인기 투표 1위… 운영진 가족도 놀람'),
(71,'good','해외 왕국 진출… 통역사부터 매수'),
(72,'good','북부 시장 개방… 얼어 있던 지갑도 녹아'),
(73,'good','남부 항구 입점… 해적들도 정상 결제'),
(74,'good','동부 상단 계약… 계약서 길이만 30미터'),
(75,'good','서부 은행 제휴… 은행장 모자 날아가'),
(76,'good','국경 송금 성공… 골드보다 소문이 먼저 도착'),
(77,'good','신규 가맹점 증가… 지도 찍다 잉크 소진'),
(78,'good','대륙 결제망 합류… 운영진 명함 새로 주문'),
(79,'good','무역 관세 인하… 상인들 갑자기 애국자 됨'),
(80,'good','사업 허가 승인… 담당 공무원도 한 개 매수'),
(81,'good','소각 성공… 소방 길드는 오해하고 출동'),
(82,'good','운영진 물량 잠금… 열쇠를 드래곤이 삼킴'),
(83,'good','공급 축소 발표… 상인들 창고부터 확인'),
(84,'good','대형 매도자 잠들어… 시장에 평화 찾아와'),
(85,'good','경쟁 코인 대표 휴가… 이용자 대거 유입'),
(86,'good','거래소 추가 상장… 축하 화환 입구 막아'),
(87,'good','투자 펀드 편입… 펀드보다 코인이 유명'),
(88,'good','휴면 이용자 복귀… 비밀번호 찾기 서버 비상'),
(89,'good','잃어버린 준비금 발견… 대표 책상 밑이었다'),
(90,'good','도난 골드 회수… 도둑이 투자자로 전향'),
(91,'good','계약 분쟁 해결… 양쪽 변호사만 아쉬워'),
(92,'good','소송 승소… 판사가 기사 제목까지 추천'),
(93,'good','공급망 복구… 짐꾼 허리만 남은 과제'),
(94,'good','사업 재개… 창고 먼지가 첫 매출보다 많아'),
(95,'good','신규 대표 취임… 첫날부터 출근해 화제'),
(96,'good','이용자 보상 완료… 고객센터에 감사 전화 도착'),
(97,'good','대형 계약 체결… 대표 도장에 쥐 남'),
(98,'good','목표 초과 달성… 목표 정한 직원 승진'),
(99,'good','예언서에 상승 기록… 마지막 장은 비공개'),
(100,'good','마왕 토벌보다 수익성이 좋다는 소문 확산'),
(101,'bad','국왕이 비밀번호 잊어 왕실 회의 소집'),
(102,'bad','드래곤이 보물창고 들고 야반도주'),
(103,'bad','고블린 투자단 전원 점심값 필요해 매도'),
(104,'bad','개발자 출근 예정… 예정만 세 번째'),
(105,'bad','운영진 비밀번호가 ‘1234’로 밝혀져'),
(106,'bad','왕실 재무관 “그 느낌이 아니었다”'),
(107,'bad','상인 길드 회장 집문서 돌려달라 요청'),
(108,'bad','마왕이 롱 정리하고 숏으로 갈아탐'),
(109,'bad','예언자 수정구슬 고장… 전망 철회'),
(110,'bad','직원이 실수로 내부 단톡방 공개'),
(111,'bad','용사가 포션 사야 한다며 전량 매도'),
(112,'bad','대장장이 “코인보다 망치가 확실하다”'),
(113,'bad','드래곤 금고 열었더니 먼지만 발견'),
(114,'bad','왕비 비상금 회수… 국왕은 모르는 일 주장'),
(115,'bad','투자 설명회 참석자보다 도시락이 많아'),
(116,'bad','운영진 회식비가 개발비 추월'),
(117,'bad','마법사가 버그를 몬스터로 잘못 소환'),
(118,'bad','서버에 성수 뿌렸다가 합선'),
(119,'bad','사제 “이건 축복으로도 어렵다”'),
(120,'bad','왕실 결제 해지… 국왕 현금만 받겠다 선언'),
(121,'bad','드래곤 둥지 결제 중단… 단말기 먹어버려'),
(122,'bad','마왕성 매점 폐업… 미납 장부만 남아'),
(123,'bad','포션 상인 결제 거부… 골드 내놓으라 요구'),
(124,'bad','여관 주인 “코인 말고 숙박비 주세요”'),
(125,'bad','던전 결제 중단… 해골도 환불 요청'),
(126,'bad','포털 결제 오류… 이용자 옆방으로 이동'),
(127,'bad','대장간 계약 종료… 대표 명함만 녹여버려'),
(128,'bad','펫 간식 사업 철수… 펫들 단체 시위'),
(129,'bad','길드 회비 채택 취소… 총무 연락 두절'),
(130,'bad','왕실 식당 결제 거부… 대표 설거지 중'),
(131,'bad','대형 상단 “생각해 보니 안 사겠다”'),
(132,'bad','거물 투자자 지갑 닫다 손가락까지 끼임'),
(133,'bad','고래 이탈… 어부들만 출항'),
(134,'bad','매도벽 등장… 성벽보다 높다는 제보'),
(135,'bad','기관 투자자 퇴장… 의자까지 반납'),
(136,'bad','장기 투자자 비밀번호 찾아 전량 매도'),
(137,'bad','매도 주문 폭주… 번호표 기계 과열'),
(138,'bad','투자 설명회 앞줄 전원 운영진 가족'),
(139,'bad','은행장 “접속은 했지만 산 적 없다”'),
(140,'bad','왕실 금고 폐쇄… 열쇠 담당자 휴가'),
(141,'bad','광산 금맥인 줄 알았는데 노란 페인트'),
(142,'bad','마법석 반품 폭주… 전부 예쁜 돌이었다'),
(143,'bad','무역선 빈손 귀환… 선장 기념품만 구매'),
(144,'bad','신규 사업 참패… 계산기도 계산 거부'),
(145,'bad','매출 장부 실종… 마지막 목격 장소 회식장'),
(146,'bad','적자 확대… 회계사 웃음도 적자'),
(147,'bad','부채 상환 연기… 채권자 길드 결성'),
(148,'bad','준비금 공개… 금고 안에 영수증뿐'),
(149,'bad','투자 유치 실패… 대표 다시 반말 시작'),
(150,'bad','회식 메뉴 고기에서 물로 변경'),
(151,'bad','보안 감사 실패… 도둑 길드 최고점 부여'),
(152,'bad','해커가 너무 쉽게 들어와 오히려 의심'),
(153,'bad','거래 지연… 비둘기가 먼저 정산 완료'),
(154,'bad','서버 과열… 선풍기 담당자 퇴사'),
(155,'bad','개발자 커피 품절로 업데이트 중단'),
(156,'bad','버그 수정하다가 버그 세 마리 추가'),
(157,'bad','지갑 복구 실패… 상담원도 비밀번호 물어봄'),
(158,'bad','새로고침 100번 해도 해결 안 돼 충격'),
(159,'bad','기술 특허 거절… 이미 고블린이 발명'),
(160,'bad','새 기능 공개했지만 개발자도 사용법 모름'),
(161,'bad','국왕 연설에서 이름 틀리게 부름'),
(162,'bad','유명 용사 추천 철회… 광고비 미지급'),
(163,'bad','마왕 “나보다 더 악질” 혹평'),
(164,'bad','엘프 투자단 “300년 뒤에 다시 보겠다”'),
(165,'bad','드워프 은행 승인 거절… 도장도 안 꺼냄'),
(166,'bad','오크 길드 뒤늦게 설명 이해하고 매도'),
(167,'bad','사제단 성수 회수… 축복 계약 종료'),
(168,'bad','왕실 행사 후원 취소… 현수막만 도착'),
(169,'bad','신문 정정 보도… 좋은 소식은 오타였다'),
(170,'bad','인기 투표 꼴찌… 운영진 가족도 다른 코인 선택'),
(171,'bad','해외 진출 무산… 대표 여권 만료'),
(172,'bad','북부 시장 철수… 투자금도 얼어붙어'),
(173,'bad','남부 항구 사업 중단… 해적에게 통째로 털려'),
(174,'bad','동부 계약 파기… 계약서에 이름 틀림'),
(175,'bad','서부 은행 제휴 종료… 은행장 만나기도 실패'),
(176,'bad','국경 송금 실종… 비둘기만 돌아와'),
(177,'bad','가맹점 감소… 지도에서 지우는 게 더 빠름'),
(178,'bad','대륙 결제망 탈락… 신청서 누락'),
(179,'bad','관세 인상… 상인들 갑자기 이민 알아봄'),
(180,'bad','사업 허가 보류… 대표 도장 대신 지장 찍어'),
(181,'bad','소각 실패… 코인 대신 계약서 태워'),
(182,'bad','물량 잠금 해제… 자물쇠가 장난감이었다'),
(183,'bad','추가 발행 발표… 인쇄 담당자 야근'),
(184,'bad','대형 매도자 기상… 시장에 비상벨 울려'),
(185,'bad','경쟁 코인 무료 간식 행사에 이용자 이탈'),
(186,'bad','추가 상장 무산… 축하 화환 반품'),
(187,'bad','투자 펀드 제외… 담당자 이름도 기억 못 해'),
(188,'bad','휴면 이용자 복귀하자마자 전량 매도'),
(189,'bad','준비금 분실… 대표 “어제까진 있었다”'),
(190,'bad','도둑이 금고 털고 문 잠가주고 떠남'),
(191,'bad','계약 분쟁 장기화… 변호사만 신나'),
(192,'bad','소송 패소… 판사가 한숨부터 쉬어'),
(193,'bad','공급망 마비… 짐꾼이 길을 반대로 감'),
(194,'bad','사업 재개 하루 만에 다시 휴업'),
(195,'bad','신규 대표 취임 첫날 휴가 신청'),
(196,'bad','보상 지연… 사과문만 정시 발행'),
(197,'bad','대형 계약 무산… 도장이 감자였다'),
(198,'bad','실적 목표 미달… 목표 적은 종이부터 폐기'),
(199,'bad','예언서 마지막 장 공개… “아까 건 농담”'),
(200,'bad','마왕 토벌보다 원금 회수가 어렵다는 소문 확산')
on conflict(id) do update set kind=excluded.kind,headline=excluded.headline;
create or replace function rebirth_private.coin_news_schedule(p_day date,p_from integer default 0) returns void language plpgsql security definer set search_path='' as $$
declare n integer; minute integer; article integer; at_time timestamptz; first_minute integer; span integer; slot integer; lo integer; hi integer; margin integer;
begin
 perform pg_advisory_xact_lock(71823081);
 insert into rebirth_private.coin_news_days values(p_day) on conflict do nothing;
 if not found then return;end if;
 n:=3+floor(random()*4)::integer;first_minute:=greatest(0,least(1436,p_from));span:=1440-first_minute;
 for slot in 0..n-1 loop
  lo:=first_minute+floor(slot*span::numeric/n)::integer;hi:=first_minute+floor((slot+1)*span::numeric/n)::integer-1;
  margin:=least(60,greatest(0,(hi-lo)/2));lo:=lo+margin;hi:=hi-margin;
  minute:=lo+floor(random()*(hi-lo+1))::integer;
  at_time:=(p_day::timestamp at time zone 'Asia/Seoul')+minute*interval '1 minute';article:=1+floor(random()*200)::integer;
  insert into rebirth_private.coin_news(day,coin,catalog,published_at,expires_at,boost)
  values(p_day,floor(random()*8)::integer,article,at_time,at_time+interval '8 hours',(.10+floor(random()*21)*.01));
 end loop;
end $$;
revoke all on function rebirth_private.coin_news_schedule(date,integer) from public,anon,authenticated;
create or replace function rebirth_private.coin_up_chance(p_coin integer,p_at timestamptz) returns numeric language sql stable security definer set search_path='' as $$
 with latest as(select c.kind from rebirth_private.coin_news n join rebirth_private.coin_news_catalog c on c.id=n.catalog where n.coin=p_coin and n.published_at<=p_at order by n.published_at desc,n.id desc limit 1), cutoff as(select max(n.published_at) at from rebirth_private.coin_news n join rebirth_private.coin_news_catalog c on c.id=n.catalog where n.coin=p_coin and n.published_at<=p_at and c.kind<>(select kind from latest))
 select greatest(.05,least(.95,.5*(1+coalesce(sum(case when c.kind='good' then n.boost else -n.boost end),0))))
 from rebirth_private.coin_news n join rebirth_private.coin_news_catalog c on c.id=n.catalog
 where n.coin=p_coin and n.published_at<=p_at and n.expires_at>p_at and c.kind=(select kind from latest) and ((select at from cutoff) is null or n.published_at>(select at from cutoff))
$$;
revoke all on function rebirth_private.coin_up_chance(integer,timestamptz) from public,anon,authenticated;
