import {goldPurchaseIcon} from './currency-icons.mjs';
import {fantasyHeader,fantasyFooter} from './fantasy-ui.mjs?v=short-18';
const fmt=n=>Math.floor(n||0).toLocaleString('ko-KR');
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const date=v=>new Date(v).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul',month:'numeric',day:'numeric'});
const balls=n=>n.map(v=>`<span class="lotto-ball selected">${v}</span>`).join('');
export const lottoSelection=[];
export let lottoPanel='pick';
export function selectLottoNumber(n){const i=lottoSelection.indexOf(n);if(i>=0)lottoSelection.splice(i,1);else if(lottoSelection.length<2)lottoSelection.push(n);lottoSelection.sort((a,b)=>a-b);}
export function setLottoPanel(v){if(['pick','tickets','history'].includes(v))lottoPanel=v;}
export function autoLotto(lotto,random=Math.random){const used=new Set((lotto?.tickets||[]).map(t=>t.numbers.join(':'))),available=[];for(let a=1;a<=18;a++)for(let b=a+1;b<=18;b++)if(!used.has(a+':'+b))available.push([a,b]);if(available.length)lottoSelection.splice(0,2,...available[Math.min(available.length-1,Math.floor(random()*available.length))]);}
export function clearLotto(){lottoSelection.splice(0);lottoPanel='pick';}
export function lottoView(s,l){const ready=!!l,selected=lottoSelection.length===2,duplicate=selected&&l?.tickets.some(t=>t.numbers.join(':')===lottoSelection.join(':'));
 const blocked=!ready||!selected||duplicate||l.todayCount>=3||s.gold<1000;
 const tabs=[['pick','번호 선택'],['tickets','내 복권'],['history','지난 결과']].map(([k,label])=>`<button data-action="lottoPanel" data-arg="${k}" class="${lottoPanel===k?'active':''}" data-illustrated="1">${label}</button>`).join('');
 const ticketList=ready?(l.tickets.length?l.tickets.map(t=>`<article class="lotto-ticket">${balls(t.numbers)}<span>${date(t.boughtAt)} 구매</span><b>추첨 대기</b></article>`).join(''):'<p class="lotto-empty">이번 주 구매한 복권이 없습니다.</p>'):'<p class="lotto-empty">복권 정보를 불러오는 중…</p>';
 const history=ready?(l.history.length?l.history.map(h=>`<article class="lotto-history"><header><strong>${date(h.drawAt)} 추첨</strong><span>판매금 ×${h.multiplier}배</span></header><div class="lotto-result-balls">${balls(h.numbers)}</div><p>총상금 <b>${fmt(h.prize)} G</b> · 1등 ${h.winnerCount}장</p>${h.winnerCount?h.winners.map(w=>`<small>${esc(w.name)} · ${fmt(w.amount)} G</small>`).join(''):`<small>1등 없음 · ${fmt(h.carryOut)} G 이월</small>`}${h.myTickets?.length?`<details><summary>내 복권 ${h.myTickets.length}장 확인</summary>${h.myTickets.map(t=>`<p>${t.numbers.join(' · ')} — ${t.amount?fmt(t.amount)+' G 당첨':'미당첨'}</p>`).join('')}</details>`:''}</article>`).join(''):'<p class="lotto-empty">첫 추첨을 기다리고 있어요.</p>'):'<p class="lotto-empty">추첨 기록을 불러오는 중…</p>';
 return `<section class="lotto-screen" data-currency-label>${fantasyHeader(s,'event')}<div class="lotto-scroll"><nav class="lotto-event-switch"><button data-action="eventPage" data-arg="pet" data-illustrated="1">루미 소환</button><button class="active" data-action="eventPage" data-arg="lotto" data-illustrated="1">주간 로또</button></nav><main class="lotto-scene"><header class="lotto-heading"><h1>주간 로또</h1><p>매주 토요일 오후 9시 추첨</p></header><section class="lotto-prize"><span>이번 주 예상 총상금</span><strong>${ready?`${fmt(l.minPrize)} <i>~</i><br>${fmt(l.maxPrize)} G`:'불러오는 중…'}</strong><small>판매금 × 8~11배 · 추첨 시 배율 결정</small><small>이번 주 판매 ${fmt(l?.sales)} G${l?.carryIn?` · 이월 ${fmt(l.carryIn)} G`:''}</small></section><nav class="lotto-tabs">${tabs}</nav><section class="lotto-panel">${lottoPanel==='pick'?`<h2>1~18 중 번호 2개를 선택하세요</h2><p class="lotto-rule">순서와 관계없이 2개 일치하면 1등</p><div class="lotto-numbers">${Array.from({length:18},(_,i)=>i+1).map(n=>`<button data-action="lottoNumber" data-arg="${n}" data-illustrated="1" class="lotto-ball ${lottoSelection.includes(n)?'selected':''}" aria-pressed="${lottoSelection.includes(n)}" aria-label="번호 ${n}">${n}</button>`).join('')}</div><div class="lotto-selection"><b>선택 번호</b><div>${balls(lottoSelection)}${Array.from({length:2-lottoSelection.length},()=>'<span class="lotto-ball empty">?</span>').join('')}</div><button data-action="lottoAuto" data-illustrated="1">⇄ 자동 선택</button></div><div class="lotto-cost"><span>오늘 구매 ${l?.todayCount||0} / 3장</span><span>${goldPurchaseIcon()}1장 1,000 G</span></div><button class="lotto-buy" data-action="lottoBuy" data-write="1" data-illustrated="1" ${blocked?'disabled':''}>${duplicate?'이미 구매한 번호':ready&&l.todayCount>=3?'오늘 구매 완료':goldPurchaseIcon()+'1,000 G · 구매하기'}</button><p class="lotto-help">1등만 지급 · 당첨 표끼리 상금 균등 분배<br>1등이 없으면 다음 주 이월 · 같은 번호 중복 구매 불가</p>`:lottoPanel==='tickets'?`<h2>내 복권 · 이번 주 ${l?.tickets.length||0}장</h2><p class="lotto-rule">${l?date(l.drawAt):''} 토요일 오후 9시 추첨</p><div class="lotto-list">${ticketList}</div>`:`<h2>지난 추첨 결과</h2><p class="lotto-rule">당첨금은 우편함에서 수령하세요.</p><div class="lotto-list">${history}</div>`}</section></main></div>${fantasyFooter('event')}</section>`;
}
