import {PET_ID,PET_NAME,PET_EVENT,petProgress,petRates} from './pet-event.mjs?v=lumi-68';
import {currencyIconURL} from './currency-icons.mjs?v=lumi-68';
const fmt=n=>Math.floor(n||0).toLocaleString('ko-KR');
const art=key=>key==='pet'?'pets/lumi.png':key==='gear'?'tower/reward-chest.webp':currencyIconURL(key);
const rewardImage=key=>key==='gear'?'<span class="pet-chest" role="img" aria-label="보스 장비"></span>':`<img src="${art(key)}" alt="">`;
const names={pet:'루미',gear:'보스 장비',gold:'골드',fragment:'장비 파편',cube:'레드 큐브',highCube:'블랙 큐브',scroll:'잠재 해금'};
const button=(label,action,arg='',disabled=false)=>`<button class="pet-button" data-action="${action}" data-arg="${arg}" ${disabled?'disabled':''}>${label}</button>`;
export function petSlot(s){const owned=s.pets?.includes(PET_ID),equipped=s.equippedPet===PET_ID;return `<section class="panel pad pet-slot"><div class="pet-slot-image">${owned?'<img src="pets/lumi.png" alt="달빛 여우 루미">':'<span>펫</span>'}</div><div><small>펫 장착 · ${equipped?'1':'0'} / 1</small><h3>${owned?PET_NAME:'보유한 펫이 없습니다'}</h3><p>30초마다 주인 최대 체력의 8% 회복</p>${owned?button(equipped?'장착 해제':'루미 장착','petEquip',equipped?'':PET_ID):button('이벤트 보러 가기','tab','event')}</div></section>`;}
export function petInventory(s){return `<section class="pet-inventory"><h3>보유 펫 <span>${s.pets?.includes(PET_ID)?1:0}마리</span></h3><p class="note">펫은 영구 보유하며 한 마리만 장착할 수 있습니다.</p>${petSlot(s)}${s.pets?.includes(PET_ID)?'<p class="note">장착하면 캐릭터를 따라다니며 전투 중 체력을 회복해 줍니다.</p>':''}</section>`;}
export function petResult(r){return `<div class="pet-result" data-currency-label>${r.rewards.map(x=>`<div class="pet-result-card">${rewardImage(x.key)}<strong>${x.name}</strong><span>${fmt(x.amount)}${x.key==='gold'?'골드':x.key==='pet'?'마리':'개'}</span></div>`).join('')}</div><p>실제 사용 ${fmt(r.cost)}골드${r.unused?` · 미사용 ${fmt(r.unused)}골드는 차감하지 않았습니다.`:''}</p>`;}
export function petOdds(s){const p=petProgress(s);return `<div class="pet-odds" data-currency-label><p>계정당 루미 1마리 · 미획득 시 100회 확정</p><table><thead><tr><th>보상</th><th>1회 수량</th><th>확률</th><th>남음</th></tr></thead><tbody>${petRates(s).map(r=>`<tr><td>${rewardImage(r.key)}${names[r.key]}</td><td>${fmt(r.amount)}</td><td>${r.rate}%</td><td>${r.cap?Math.max(0,r.cap-(p.counts[r.key]||0)):'무제한'}</td></tr>`).join('')}</tbody></table><p>수량 한도는 계정별 누적 기준이며, 소진된 확률은 골드로 이전됩니다.</p><p>루미를 획득하면 소환이 종료됩니다. 5회 도중 획득하면 사용하지 않은 횟수의 골드는 차감하지 않습니다.</p><p>종료: ${new Date(PET_EVENT.end).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'})}</p>${p.lastResult?'<h3>최근 소환 결과</h3>'+petResult(p.lastResult):''}</div>`;}
export function petEventView(s){const p=petProgress(s),owned=s.pets?.includes(PET_ID),now=Date.now(),ended=now>=PET_EVENT.end,blocked=!s.isAdmin||owned||ended||now<PET_EVENT.start;return `<section class="pet-screen" data-currency-label aria-label="루미 한정 소환 이벤트"><header class="pet-screen-header"><strong>링구 RPG</strong><span><img src="${currencyIconURL('gold')}" alt="골드">${fmt(s.gold)}</span></header><nav class="pet-top-nav" aria-label="게임 메뉴">${[['character','캐릭터',3],['gear','가방',1],['hunt','사냥',2],['event','이벤트',10]].map(([key,label,i])=>`<button data-action="tab" data-arg="${key}" data-illustrated="1" class="${key==='event'?'active':''}" ${key==='event'?'aria-current="page"':''}><i class="menu-art" style="background-position:${i%4*100/3}% ${Math.floor(i/4)*100/3}%"></i>${label}</button>`).join('')}</nav><div class="pet-scene"><div class="pet-heading"><h1>${PET_NAME}</h1><div class="pet-badges"><span>한정 이벤트</span><span>관리자 테스트</span></div><p data-pet-countdown>7일 한정 소환</p></div><div class="pet-hero"><div class="lumi-pose pet-hero-pose" role="img" aria-label="손을 들어 인사하는 루미"></div></div><div class="pet-benefit"><span class="pet-heal-emblem" aria-hidden="true">♥</span><div><strong>30초마다 최대 체력 <em>8%</em> 회복</strong><small>펫은 한 마리만 장착할 수 있어요.</small></div></div><div class="pet-progress-row"><strong>소환 ${p.draws} / 100</strong><progress max="100" value="${p.draws}"></progress><small>${owned?'루미 획득 완료':'100회 이내 루미 확정'}</small></div><div class="pet-draw-buttons">${[1,5].map(n=>`<button data-action="petSummon" data-arg="${n}" class="pet-draw pet-draw-${n}" ${blocked?'disabled':''}><b>${n}회 소환</b><span><img src="${currencyIconURL('gold')}" alt="골드">${fmt(n*PET_EVENT.cost)}</span></button>`).join('')}</div><section class="pet-rewards"><header><h2>소환 보상</h2><button data-action="petOdds" data-illustrated="1">확률 보기 ›</button></header><div class="pet-reward-grid">${petRates(s).map(r=>`<div class="pet-reward"><div class="pet-reward-image">${rewardImage(r.key)}</div><strong>${names[r.key]}</strong><small>${fmt(r.amount)}${r.key==='gold'?'':r.key==='pet'?'마리':'개'}</small></div>`).join('')}</div><p class="pet-state">${owned?'루미 획득 완료 · 가방 → 펫에서 장착하세요.':ended?'소환 기간이 종료되었습니다.':!s.isAdmin?'현재 관리자 계정만 소환할 수 있습니다.':'펫 영구 보유 · 계정당 1마리'}</p></section></div></section>`;}
export function updatePetCountdown(){for(const el of document.querySelectorAll('[data-pet-countdown]')){const seconds=Math.max(0,Math.floor((PET_EVENT.end-Date.now())/1000));el.textContent=seconds?`7일 한정 소환 · ${Math.floor(seconds/86400)}일 ${String(Math.floor(seconds/3600)%24).padStart(2,'0')}:${String(Math.floor(seconds/60)%60).padStart(2,'0')} 남음`:'이벤트 종료';}}
// The server has already awarded the pet. This is presentation only: no timers grant rewards.
export async function playLumiReveal(onComplete){
 if(document.querySelector('.lumi-cinematic'))return;
 const previous=document.activeElement,dialog=document.createElement('dialog');dialog.className='lumi-cinematic';dialog.setAttribute('aria-label','달빛 여우 루미 획득');
 dialog.innerHTML=`<div class="lumi-film"><div class="lumi-film-forest"></div><div class="lumi-fireflies">${Array.from({length:18},(_,i)=>`<i style="--i:${i};left:${(i*37)%100}%;top:${(i*23)%90}%"></i>`).join('')}</div><div class="lumi-film-actor"><div class="lumi-pose"></div></div><div class="lumi-film-title"><small>새로운 친구를 만났어요</small><h2>${PET_NAME}</h2><p>30초마다 최대 체력 8% 회복</p></div><button class="lumi-film-confirm" disabled>루미와 함께하기</button></div>`;
 document.body.append(dialog);dialog.addEventListener('cancel',e=>e.preventDefault());dialog.showModal();
 const pose=dialog.querySelector('.lumi-pose'),film=dialog.querySelector('.lumi-film'),confirm=dialog.querySelector('button');
 // Preload before the four-second timeline so a slow phone never reveals an empty frame.
 await Promise.all(['pets/lumi-home-v2.webp','pets/lumi-reveal-v2.webp'].map(src=>new Promise(resolve=>{const im=new Image();im.onload=im.onerror=resolve;im.src=src;if(im.complete)resolve();})));
 if(!dialog.isConnected)return;film.classList.add('playing');const started=performance.now();let frame;
 const tick=now=>{const ms=Math.min(4000,now-started);const cell=ms<1050?0:ms<1300?1:ms<1600?2:ms<1850?3:ms<2250?4:ms<2700?5:ms<3050?6:7;pose.style.backgroundPosition=`${cell%4*100/3}% ${Math.floor(cell/4)*100}%`;if(ms<4000)frame=requestAnimationFrame(tick);else{film.classList.add('finished');confirm.disabled=false;confirm.focus();}};frame=requestAnimationFrame(tick);
 confirm.onclick=()=>{cancelAnimationFrame(frame);dialog.close();dialog.remove();previous?.focus?.();onComplete();};
}
