import {initialState,makeItem,power} from './engine.mjs?v=priest-support-62';
import {CLASSES,rollBaseStats} from './data.mjs?v=priest-support-62';
import {beginCombatSkill,stepCombatSkills} from './combat-skills.mjs?v=priest-support-62';
import {beginThird,stepThird} from './advancement.mjs?v=priest-support-62';
import {beginFourth,stepFourth} from './fourth-job.mjs?v=priest-support-62';
import {beginPriest,stepPriest,supportTick,holyDamage} from './priest.mjs?v=priest-support-62';
import {TOWER_CLASSES} from './tower-model.mjs?v=priest-support-62';
let serial=0;
export function fixture(classId,level=200,stars=25){const ctx={now:0,random:()=>.99999,uuid:()=>String(++serial)},cl=CLASSES.find(c=>c.id===classId),s=initialState(classId,'밸런스검증',ctx);Object.assign(s,{level,firstAdvancement:level>=30,advancement:level>=150?3:level>=100?2:level>=60?1:0,items:[],equipped:{}});s.stats[cl.stat]=4+(level-1)*5;for(let slot=0;slot<9;slot++){const i=makeItem(level,classId,slot,true,ctx,2);Object.assign(i,{design:2,stars,grade:5,potentialVersion:5,potentialUnlocked:true});i.baseStats=rollBaseStats(i,()=>.99999);s.items.push(i);s.equipped[slot]=i.id;}return s;}
export function setLines(s,counts){const lines=Object.entries(counts).flatMap(([key,n])=>Array.from({length:n},()=>({key,value:key==='boss'?40:12,grade:5})));s.items.forEach((i,n)=>i.lines=lines.slice(n*3,n*3+3));return s;}
export function rotation(s,seconds=180){const p=power(s),a={id:'me',classId:s.classId,power:p,hp:p.hp,x:0,y:0,advancement:s.advancement,advanced:true},target={id:'dummy',x:100,y:0};let total=0;for(let t=0;t<seconds*10;t++){a.tick=t;supportTick([a],t);const hit=(scale,extra=0)=>{const crit=Math.min(.95,p.crit+extra);total+=holyDamage(a,p.attack*scale*(1+crit*(p.critDamage-1)),t)*p.boss;};const c=TOWER_CLASSES[s.classId];if(t%c.cooldown===0)hit(c.cooldown/10*p.cadence);beginCombatSkill(a,target,t,1);beginCombatSkill(a,target,t,2);beginThird(a,target,t);beginFourth(a,target,t);if(s.classId==='priest'){beginPriest(a,target,t,5);stepPriest(a,[target],t,5,hit);}stepCombatSkills(a,[target],t,hit);stepThird(a,target,t,hit);stepFourth(a,target,t,hit);supportTick([a],t);}return total/seconds;}
export function bestOffense(classId){const s=fixture(classId),main=CLASSES.find(c=>c.id===classId).stat;let best={score:0};for(let attack=0;attack<=27;attack++)for(let mainCount=0;mainCount<=27-attack;mainCount++)for(let crit=0;crit<=27-attack-mainCount;crit++){const counts={attack,[main]:mainCount,crit,boss:27-attack-mainCount-crit};setLines(s,counts);const p=power(s),score=p.dps*p.boss;if(score>best.score)best={score,counts};}setLines(s,best.counts);return {classId,counts:best.counts,dps:rotation(s),attack:power(s).attack,hp:power(s).hp};}
if(process.argv[1]?.endsWith('priest-balance.mjs')){const others=CLASSES.filter(c=>c.id!=='priest').map(c=>({classId:c.id,dps:rotation(setLines(fixture(c.id),{[c.stat]:27}))})),average=others.reduce((n,r)=>n+r.dps,0)/others.length;const priest=['hp','attack','LUK','boss','crit'].map(key=>{const s=setLines(fixture('priest'),{[key]:27});return {build:key,dps:rotation(s),ratio:rotation(s)/average,hp:power(s).hp,attack:power(s).attack};});console.log(JSON.stringify({seconds:180,level:200,stars:25,otherJobs:others,average,priest},null,2));}
