import {PGlite} from '@electric-sql/pglite';
import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';import assert from 'node:assert/strict';
import {initialState,power} from './engine.mjs';import {RAID_BOSSES,CLASS_SKILLS,SECOND_SKILLS} from './data.mjs';
const db=new PGlite();try{
await db.exec(`create role anon;create role authenticated;create role service_role;create schema auth;create table auth.users(id uuid primary key);create table auth.sessions(id uuid primary key,user_id uuid references auth.users(id),created_at timestamptz default now());create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;create function auth.jwt() returns jsonb language sql as $$select jsonb_build_object('session_id',current_setting('test.sid',true))$$;`);
await db.exec(await readFile(new URL('schema.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('raid-v2.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('individual-gear.sql',import.meta.url),'utf8'));await db.exec(await readFile(new URL('individual-gear-party.sql',import.meta.url),'utf8'));await db.exec('update rebirth_private.release set enabled=true');
const users=Array.from({length:5},()=>({id:randomUUID(),sid:randomUUID()}));const auth=async u=>db.query("select set_config('test.uid',$1,false),set_config('test.sid',$2,false)",[u.id,u.sid]);const snap=async()=>(await db.query('select public.rebirth_snapshot($1) s',[randomUUID()])).rows[0].s;
for(const u of users){await db.query('insert into auth.users values($1)',[u.id]);await db.query('insert into auth.sessions(id,user_id) values($1,$2)',[u.sid,u.id]);await auth(u);const p=await snap();const s=initialState('warrior','검증',{now:Date.now(),uuid:randomUUID});s.hunting=false;s.advancement=1;await db.query('select public.rebirth_commit($1,$2,$3,$4,$5,$6,$7,$8)',[u.id,u.sid,p.epoch,p.revision,randomUUID(),'{}',JSON.stringify(s),'{}']);}
async function act(u,action,args={},rid=randomUUID()){await auth(u);const p=await snap();return(await db.query('select public.rebirth_party_action($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) r',[u.id,u.sid,p.epoch,p.revision,JSON.stringify(p.state),action,JSON.stringify(args),JSON.stringify({...power(p.state),skill:CLASS_SKILLS.warrior,secondSkill:SECOND_SKILLS.warrior}),rid,JSON.stringify({action,args})])).rows[0].r;}
const u=users[0],boss=RAID_BOSSES[0];let r=await act(u,'create',{boss});assert.equal(r.state.level,1);let room=r.room.id;r=await act(u,'start');assert.equal(r.room.maxHp,boss.hp);r=await act(u,'skill',{slot:2});assert.ok(r.room.hp<boss.hp);assert.equal(r.room.members[0].secondReady,28);await assert.rejects(()=>act(u,'skill',{slot:2}),/SKILL_COOLDOWN/);await db.query("update rebirth_private.party_rooms set started_at=now()-interval '1 second' where id=$1",[room]);r=await act(u,'sync');assert.equal(r.room.tick,1);assert.ok(r.room.members[0].damage>0);await act(u,'leave');
r=await act(u,'create',{boss});room=r.room.id;for(const v of users.slice(1,4))await act(v,'join',{room});await assert.rejects(()=>act(users[4],'join',{room}),/PARTY_FULL/);r=await act(u,'start');assert.equal(r.room.maxHp,boss.hp);
// Finish local-only battle with all 4 participants contributing; verify separate counters and exact replay.
await db.query("update rebirth_private.party_rooms set hp=0 where id=$1",[room]);await db.query('update rebirth_private.party_members set damage=100 where room=$1',[room]);const rid=randomUUID();r=await act(u,'sync',{},rid);assert.equal(r.state.raidClaims['100'].count,1);assert.deepEqual(r.state.bossClaims,{});assert.deepEqual(r.state.cleared,[]);const gold=r.state.gold;for(const v of users.slice(1,4)){await auth(v);assert.equal((await snap()).state.raidClaims['100'].count,1);}r=await act(u,'sync',{},rid);assert.equal(r.state.gold,gold);
r=await act(u,'create',{boss});room=r.room.id;await act(u,'start');await db.query('update rebirth_private.party_rooms set hp=0 where id=$1',[room]);await db.query('update rebirth_private.party_members set damage=100 where room=$1',[room]);r=await act(u,'sync');assert.equal(r.state.raidClaims['100'].count,2);await assert.rejects(()=>act(u,'create',{boss}),/RAID_LIMIT/);
r=await act(u,'create',{boss,practice:true});await act(u,'start');room=r.room.id;await db.query('update rebirth_private.party_rooms set hp=0 where id=$1',[room]);r=await act(u,'sync');assert.equal(r.state.raidClaims['100'].count,2);
await db.query("update rebirth_private.players set state=jsonb_set(state,'{raidClaims,100,day}','\"2000-01-01\"') where id=$1",[u.id]);r=await act(u,'create',{boss});assert.ok(r.room);await act(u,'leave');
await db.exec('set role authenticated');await assert.rejects(()=>db.query('select * from rebirth_private.party_rooms'),/permission denied/);await db.exec('reset role');
console.log('PASS raid SQL: Lv.1 solo, fixed four-player HP, capacity, second attack/cooldown, 4-player individual rewards, isolated daily two-clear limits, practice, day reset, no public writes');
}catch(e){console.error(e.message,e.where||'',e.position||'');process.exitCode=1;}finally{await db.close();}
