import {towerEncounter,TOWER_FLOORS} from './tower-model.mjs?v=enemy-interval-1';
import {CLASS_SKILLS,SECOND_SKILLS,FOURTH_SKILLS,THIRD_SKILLS,firstJobUnlocked} from './data.mjs?v=enemy-interval-1';
export {TowerController} from './tower-controller.mjs?v=enemy-interval-1';
const format=n=>Math.floor(n).toLocaleString('ko-KR');
const asset=name=>'tower/'+name+'.webp';
export function towerLobby(state){
 const cleared=state.tower?.cleared||[];
 return `<section class="tower-intro panel"><div><p class="eyebrow">TOWER OF TRIALS</p><h2>시련의 탑</h2><p>발걸음으로 피하고, 빈틈을 노려라.</p><span class="pill">${cleared.length} / 10층 정복</span></div></section><div class="panel pad tower-guide"><strong>직접 움직이는 1인 도전</strong><p>모바일: 이동 패드 + 공격·스킬·회피 버튼<br>PC: WASD / 방향키 이동 · J 공격 · K 1차 스킬 · L 2차 스킬 · I 3차 스킬 · O 4차 스킬 · Space 회피</p><p class="note">${state.advancement>=3?'1차·2차·3차·4차 스킬 사용 가능':state.advancement>=2?'1차·2차·3차 스킬 사용 가능':state.advancement?'1차·2차 스킬 사용 가능':firstJobUnlocked(state)?'1차 스킬 사용 가능 · 2차는 60레벨 전직 후':'1차 스킬은 30레벨 전직 보스 처치 후 해금'} · 층마다 1분 30초<br>전 층 입장 제한 없음<br>층별 최초 클리어 보상만 지급 · 재도전은 기록 도전<br>탑 전투 중 일반 사냥은 멈추며 종료 후 재개됩니다.</p></div><div class="tower-floor-list">${TOWER_FLOORS.map(f=>{const done=cleared.includes(f.floor),locked=false;return `<article class="tower-floor panel ${locked?'locked':''}"><div class="tower-portrait" style="background-image:url('${asset('boss-'+f.art)}')" role="img" aria-label="${f.name}"></div><div class="tower-floor-info"><small>${String(f.floor).padStart(2,'0')}F · 권장 Lv.${f.level}</small><h3>${f.name}</h3><p>${f.pattern}</p><small>HP ${format(f.hp)} · 공격력 ${format(f.attack)}</small><details><summary>공략 · 최초 보상</summary><p>${f.guide}</p><p>${format(f.reward.gold)} G<br>큐브 ${f.reward.cube}${f.reward.highCube?' · 상급 큐브 '+f.reward.highCube:''}</p></details><button data-action="towerStart" data-arg="${f.floor}" data-write ${locked?'disabled data-unavailable':''} class="${done?'':'gold'}">${locked?'레벨·이전 층 확인':done?'다시 도전':'도전하기'}</button>${state.tower?.best?.[f.floor]?`<small>최고 기록 ${state.tower.best[f.floor].toFixed(1)}초</small>`:''}</div></article>`;}).join('')}</div>`;
}
export function towerArena(b){
 const f=towerEncounter(b),first=CLASS_SKILLS[b.classId],second=SECOND_SKILLS[b.classId],third=THIRD_SKILLS[b.classId],fourth=FOURTH_SKILLS[b.classId],fourthReady=(b.power?.advancement||0)>=3,thirdReady=(b.power?.advancement||0)>=2||b.third;
 return `<section class="tower-play panel" data-class="${b.classId}" data-tower-run="${b.runId}">
 <header class="tower-hud"><div class="tower-title-row"><span class="tower-floor-tag">${b.advancementStage!==undefined?(b.advancementStage+1)+'차':String(b.floor).padStart(2,'0')+'F'}</span><div><small>${b.advancementStage!==undefined?"전직 보스 · "+(b.advancementStage+1)+"차":b.weeklyBossId!==undefined?"주간 보스":"시련의 탑"}</small><h3>${f.name}</h3></div><b id="tower-clock">${Math.floor(f.seconds/60)+':'+String(f.seconds%60).padStart(2,'0')}</b></div><div class="tower-boss-health"><div class="hp"><i id="tower-enemy-bar"></i></div><small id="tower-enemy-hp"></small></div></header>
 <div class="tower-stage"><div class="tower-canvas-wrap"><canvas id="tower-canvas" width="1000" height="1200" tabindex="0" aria-label="탑 전투장. WASD 또는 방향키 이동, J 공격, K 1차 스킬, L 2차 스킬 · I 3차 스킬, 스페이스 회피"></canvas><p id="tower-status" role="status">전투 준비 중…</p><small id="tower-connection" hidden></small></div></div>
 <div class="tower-player-hud"><span class="tower-player-label">내 체력</span><div class="hp player-health"><i id="tower-player-bar"></i></div><strong id="tower-player-hp"></strong><span id="tower-range">보스에게 접근</span></div>
 <div class="tower-controls"><div class="tower-movement"><div class="tower-stick" id="tower-stick" aria-label="드래그해서 이동"><span>이동</span><i id="tower-stick-knob"></i></div><small>WASD / 방향키</small></div>
 <div class="tower-buttons"><div class="tower-skill-bar" aria-label="전직 스킬 목록"><button data-tower-button="8" ${b.power?.firstJob===false?'disabled':''} class="tower-button support" title="${first.description}" aria-label="1차 스킬 ${first.name}: K"><i class="tower-action-art"></i><span>1차 · ${first.name}</span><small>${b.power?.firstJob===false?'30레벨 전직 후':'K · 1차 스킬'}</small><b></b></button><button data-tower-button="2" class="tower-button skill" ${b.advanced?'':'disabled title="60레벨 전직 후 사용 가능"'} aria-label="2차 스킬 ${second.name}: L"><i class="tower-action-art"></i><span>2차 · ${second.name}</span><small>${b.advanced?'L · 2차 스킬':'60레벨 전직 후'}</small><b></b></button><button data-tower-button="16" class="tower-button third-skill" ${thirdReady?'':'disabled'} title="${third.description}" aria-label="3차 스킬 ${third.name}: I"><i class="third-skill-art" style="--third-col:${third.art}"></i><span>3차 · ${third.name}</span><small>${thirdReady?'I · 공격 스킬':'100레벨 전직 후'}</small><b></b></button><button data-tower-button="32" class="tower-button fourth-skill" ${fourthReady?'':'disabled'} title="${fourth.description}" aria-label="4차 스킬 ${fourth.name}: O"><i class="fourth-skill-art" style="--fourth-color:${['#e5ca87','#db977d','#a4d6ac','#baa7d5','#86c8d3'][fourth.art]}">✦</i><span>4차 · ${fourth.name}</span><small>${fourthReady?'O · 지속 범위':'150레벨 전직 후'}</small><b></b></button></div><div class="tower-core-actions"><button data-tower-button="4" class="tower-button dodge" aria-label="회피: Space"><i class="tower-action-art"></i><span>회피</span><small>SPACE</small><b></b></button><button data-tower-button="1" class="tower-button attack" aria-label="공격: J, 길게 누르기"><i class="tower-action-art"></i><span>공격</span><small>J · 길게 누르기</small><b></b></button></div></div></div>
 <footer class="tower-footer"><button id="tower-chest" data-action="towerOpen" hidden>보상 상자 열고 나가기</button><button id="tower-auto" aria-pressed="false">연속 공격 꺼짐</button><span>이동하며 공격 · 붉은 영역 회피</span><button data-action="towerLeaveConfirm">나가기</button></footer></section>`;
}

