import {TOWER_FLOORS,TOWER_CLASSES,towerStep,TOWER_STEP} from './tower-model.mjs?v=tower-20';
const format=n=>Math.floor(n).toLocaleString('ko-KR');
const images=new Map();
function image(src){if(!images.has(src)){const im=new Image();im.src=src;images.set(src,im);}return images.get(src);}
const asset=name=>'tower/'+name+'.webp';
export function towerLobby(state){
 const cleared=state.tower?.cleared||[];
 return `<section class="tower-intro panel"><div><p class="eyebrow">THE FORGOTTEN SPIRE</p><h2>망각의 탑</h2><p>발걸음으로 피하고, 빈틈을 노려라.</p><span class="pill">${cleared.length} / 10층 정복</span></div></section><div class="panel pad tower-guide"><strong>직접 움직이는 1인 도전</strong><p>모바일: 이동 패드 + 공격·스킬·회피 버튼<br>PC: WASD / 방향키 이동 · J 공격 · K 스킬 · Space 회피 · L 가호</p><p class="note">현재 장비·잠재·직업 능력치 적용 · 층마다 3분<br>이전 층 클리어 후 다음 층 해금 · 입장 레벨 제한 없음<br>층별 최초 클리어 보상 1회 · 재도전 무제한<br>탑 전투 중 일반 사냥은 멈추며 종료 후 재개됩니다.</p></div><div class="tower-floor-list">${TOWER_FLOORS.map(f=>{const done=cleared.includes(f.floor),locked=f.floor>1&&!cleared.includes(f.floor-1);return `<article class="tower-floor panel ${locked?'locked':''}"><div class="tower-portrait" style="background-image:url('${asset('boss-'+f.art)}')" role="img" aria-label="${f.name}"></div><div class="tower-floor-info"><small>${String(f.floor).padStart(2,'0')}F · 권장 Lv.${f.level}</small><h3>${f.name}</h3><p>${f.pattern}</p><small>HP ${format(f.hp)} · 공격력 ${format(f.attack)}</small><details><summary>공략 · 최초 보상</summary><p>${f.guide}</p><p>${format(f.reward.gold)} G · 파편 ${f.reward.fragment}<br>큐브 ${f.reward.cube}${f.reward.highCube?' · 상급 큐브 '+f.reward.highCube:''}</p></details><button data-action="towerStart" data-arg="${f.floor}" data-write ${locked?'disabled data-unavailable':''} class="${done?'':'gold'}">${locked?'이전 층 클리어 필요':done?'다시 도전 · 보상 완료':'도전하기'}</button>${state.tower?.best?.[f.floor]?`<small>최고 기록 ${state.tower.best[f.floor].toFixed(1)}초</small>`:''}</div></article>`;}).join('')}</div>`;
}
export function towerArena(b){const f=TOWER_FLOORS[b.floor-1],c=TOWER_CLASSES[b.classId];return `<section class="tower-play panel" data-tower-run="${b.runId}"><div class="tower-hud"><div class="row spread"><small>${String(b.floor).padStart(2,'0')}F · 망각의 탑</small><b id="tower-clock">3:00</b></div><h3>${f.name}</h3><div class="hp"><i id="tower-enemy-bar"></i></div><small id="tower-enemy-hp"></small></div><div class="tower-canvas-wrap"><canvas id="tower-canvas" width="1000" height="1200" tabindex="0" aria-label="탑 전투장. WASD 또는 방향키 이동, J 공격, K 스킬, 스페이스 회피, L 가호"></canvas><p id="tower-status" role="status">전투 이미지를 불러오는 중…</p><div class="tower-player-hud"><span id="tower-player-hp"></span><div class="hp player-health"><i id="tower-player-bar"></i></div></div></div><div class="tower-controls"><div class="tower-stick" id="tower-stick" aria-label="드래그해서 이동"><span>이동</span><i id="tower-stick-knob"></i></div><div class="tower-buttons"><button data-tower-button="8" class="tower-button support"><span>가호</span><small>L · 보호·회복</small><b></b></button><button data-tower-button="2" class="tower-button skill"><span>${c.skill}</span><small>K · 직업 스킬</small><b></b></button><button data-tower-button="4" class="tower-button dodge"><span>회피</span><small>Space</small><b></b></button><button data-tower-button="1" class="tower-button attack"><span>공격</span><small>J · 길게 누르기</small><b></b></button></div></div><div class="tower-footer"><small>WASD / 방향키 이동 · 붉은 문양에서 벗어나세요.</small><button data-action="towerLeaveConfirm">나가기</button></div></section>`;}

export class TowerController {
 constructor(host,b,send,sound){this.host=host;this.send=send;this.sound=sound;this.b=structuredClone(b);this.visual={player:{...b.player},enemy:{...b.enemy}};this.serverTick=b.tick;this.frames=[];this.keys=new Set();this.buttonPointers=new Map();this.stick={x:0,y:0};this.abort=new AbortController();this.last=performance.now();this.acc=0;this.lastSend=0;this.pending=false;this.disposed=false;this.lastSound=0;this.canvas=host.querySelector('canvas');this.ctx=this.canvas.getContext('2d');this.loaded=false;
 this.required=[asset('arena'),asset('effects'),asset('boss-'+TOWER_FLOORS[b.floor-1].art),asset('hero-'+b.classId)];this.required.forEach(image);
 const options={signal:this.abort.signal};
 const controls=['w','a','s','d','arrowup','arrowdown','arrowleft','arrowright','j','k','l',' '];
 window.addEventListener('keydown',e=>{if(controls.includes(e.key.toLowerCase())&&!document.querySelector('dialog[open]')){e.preventDefault();this.keys.add(e.key.toLowerCase());}},options);
 window.addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()),options);
 window.addEventListener('blur',()=>this.resetInput(),options);
 document.addEventListener('visibilitychange',()=>{this.resetInput();this.last=performance.now();if(!document.hidden)this.flush(true);},options);
 for(const el of host.querySelectorAll('[data-tower-button]')){el.addEventListener('pointerdown',e=>{e.preventDefault();el.setPointerCapture(e.pointerId);this.buttonPointers.set(e.pointerId,Number(el.dataset.towerButton));el.classList.add('pressed');},options);for(const type of ['pointerup','pointercancel','lostpointercapture'])el.addEventListener(type,e=>{this.buttonPointers.delete(e.pointerId);el.classList.remove('pressed');},options);}
 const stick=host.querySelector('#tower-stick');let stickPointer=null;
 const move=e=>{const rect=stick.getBoundingClientRect(),radius=rect.width*.35;let x=(e.clientX-rect.left-rect.width/2)/radius,y=(e.clientY-rect.top-rect.height/2)/radius;const n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}this.stick={x,y};host.querySelector('#tower-stick-knob').style.transform=`translate(${x*radius}px,${y*radius}px)`;};
 stick.addEventListener('pointerdown',e=>{if(stickPointer!==null)return;e.preventDefault();stickPointer=e.pointerId;stick.setPointerCapture(e.pointerId);move(e);},options);stick.addEventListener('pointermove',e=>{if(e.pointerId===stickPointer)move(e);},options);for(const type of ['pointerup','pointercancel','lostpointercapture'])stick.addEventListener(type,e=>{if(e.pointerId!==stickPointer)return;stickPointer=null;this.stick={x:0,y:0};host.querySelector('#tower-stick-knob').style.transform='';},options);
 this.frame=requestAnimationFrame(t=>this.loop(t));this.canvas.focus({preventScroll:true});
 }
 resetInput(){this.keys.clear();this.buttonPointers.clear();this.stick={x:0,y:0};this.host.querySelector('#tower-stick-knob').style.transform='';}
 accept(b){if(b.runId!==this.b.runId)return;const drop=Math.max(0,b.tick-this.serverTick);this.frames.splice(0,drop);this.serverTick=b.tick;this.b=structuredClone(b);for(const input of this.frames)towerStep(this.b,input);}
 input(){const k=this.keys;let x=this.stick.x+Number(k.has('d')||k.has('arrowright'))-Number(k.has('a')||k.has('arrowleft')),y=this.stick.y+Number(k.has('s')||k.has('arrowdown'))-Number(k.has('w')||k.has('arrowup'));const n=Math.hypot(x,y);if(n>1){x/=n;y/=n;}let bits=(k.has('j')?1:0)|(k.has('k')?2:0)|(k.has(' ')?4:0)|(k.has('l')?8:0);for(const bit of this.buttonPointers.values())bits|=bit;return [Math.round(x*1000)/1000,Math.round(y*1000)/1000,bits];}
 async flush(force=false){if(this.pending||this.disposed||(!this.frames.length&&!force))return;this.pending=true;this.lastSend=performance.now();try{const r=await this.send('towerInput',{runId:this.b.runId,from:this.serverTick,frames:this.frames.slice(0,30)},true);if(r)this.error='';}catch{this.error='연결 재시도 중 · 입력을 보관하고 있어요';}finally{this.pending=false;}}
 loop(now){if(this.disposed)return;const dt=Math.min(200,now-this.last);this.last=now;this.loaded=this.required.every(src=>{const im=image(src);return im.complete&&im.naturalWidth;});
 if(!document.hidden&&this.loaded&&!document.querySelector('dialog[open]')){this.acc+=dt;while(this.acc>=TOWER_STEP&&this.frames.length<25&&!this.b.ended){const input=this.input();this.frames.push(input);towerStep(this.b,input);this.acc-=TOWER_STEP;}if(this.frames.length>=25||this.b.ended)this.acc=0;}
 if(now-this.lastSend>800&&(this.frames.length||now-this.lastSend>2000))this.flush(true);
 this.draw(now);this.frame=requestAnimationFrame(t=>this.loop(t));}
 sprite(src,columns,rows,frame,x,y,w,h,flip=1,rotation=0,alpha=1){const im=image(src);if(!im.complete||!im.naturalWidth)return;const g=this.ctx,sw=im.width/columns,sh=im.height/rows;g.save();g.translate(x,y);g.rotate(rotation);g.scale(flip,1);g.globalAlpha=alpha;g.drawImage(im,(frame%columns)*sw,Math.floor(frame/columns)*sh,sw,sh,-w/2,-h*.84,w,h);g.restore();}
 effect(kind,x,y,w,h=w,angle=0,alpha=1){const frame={slash:0,bolt:1,impact:2,rune:3}[kind]??0;const im=image(asset('effects'));if(!im.complete||!im.naturalWidth)return;const g=this.ctx,sw=im.width/2,sh=im.height/2;g.save();g.translate(x,y);g.rotate(angle);g.globalAlpha=alpha;g.drawImage(im,frame%2*sw,Math.floor(frame/2)*sh,sw,sh,-w/2,-h/2,w,h);g.restore();}
 draw(now){const b=this.b,f=TOWER_FLOORS[b.floor-1],g=this.ctx;g.clearRect(0,0,1000,1200);const bg=image(asset('arena'));if(bg.complete&&bg.naturalWidth)g.drawImage(bg,0,0,1000,1200);
 for(const h of b.hazards){const active=b.tick>=h.at,alpha=active?.95:.4+.3*(1+Math.sin(now/85))/2;if(h.type==='line'){const len=Math.hypot(h.tx-h.x,h.ty-h.y),steps=Math.max(1,Math.ceil(len/Math.max(50,h.width*.7)));for(let i=0;i<=steps;i++)this.effect('rune',h.x+(h.tx-h.x)*i/steps,h.y+(h.ty-h.y)*i/steps,h.width,h.width,0,alpha);}else{this.effect('rune',h.x,h.y,h.r*2,h.r*2,now/5000,alpha);if(h.inner){for(let i=0;i<12;i++){const a=i*Math.PI/6,r=(h.inner+h.r)/2;this.effect('rune',h.x+Math.cos(a)*r,h.y+Math.sin(a)*r,(h.r-h.inner)*.8,undefined,0,alpha);}}}}
 for(const key of ['player','enemy']){this.visual[key].x+=(b[key].x-this.visual[key].x)*.45;this.visual[key].y+=(b[key].y-this.visual[key].y)*.45;}
 const drawPlayer=()=>{const casting=b.tick<b.skillUntil,attacking=b.tick<b.attackUntil,frame=casting?3:attacking?2:b.player.moving?1:0;const bob=b.player.moving?Math.sin(now/65)*7:Math.sin(now/450)*2;this.sprite(asset('hero-'+b.classId),2,2,frame,this.visual.player.x,this.visual.player.y+bob,190,190,b.player.face,attacking?b.player.face*.09:0,b.tick<b.invulnerableUntil?.6:1);if(b.tick<b.guardUntil)this.effect('rune',b.player.x,b.player.y,180,105,-now/1100,.65);};
 const drawBoss=()=>{const frame=b.tick<b.enemyCastUntil?1:b.tick<b.enemyAttackUntil?2:0;this.sprite(asset('boss-'+f.art),3,1,frame,this.visual.enemy.x,this.visual.enemy.y+Math.sin(now/400)*3,310,310,b.enemy.face,0,b.tick<(b.enemyHurtUntil||0)?.65:1);};
 if(b.player.y<b.enemy.y){drawPlayer();drawBoss();}else{drawBoss();drawPlayer();}
 for(const q of b.projectiles)if(b.tick>=q.at)this.effect('bolt',q.x,q.y,q.side==='enemy'?100:90,55,Math.atan2(q.dy,q.dx),1);
 for(const e of b.effects){const age=(b.tick-e.start)/(e.end-e.start);this.effect(e.kind,e.x,e.y,e.size*(.75+age*.45),undefined,e.kind==='slash'?age*.5:0,1-age*.6);}
 for(const n of b.numbers){g.save();g.font=`bold ${n.kind==='critical'?43:33}px system-ui`;g.textAlign='center';g.lineWidth=5;g.strokeStyle='#130f17';g.fillStyle=n.kind==='incoming'?'#ff7a83':n.kind==='heal'?'#8cffb9':n.kind==='critical'?'#ffdc80':'#fff4d4';const y=n.y-(b.tick-n.start)*5;g.strokeText((n.kind==='heal'?'+':n.kind==='incoming'?'-':'')+format(n.value),n.x,y);g.fillText((n.kind==='heal'?'+':n.kind==='incoming'?'-':'')+format(n.value),n.x,y);g.restore();if(n.id>this.lastSound&&n.kind!=='heal'){this.lastSound=n.id;this.sound?.('hit');}}
 const $=s=>this.host.querySelector(s);$('#tower-enemy-hp').textContent=`HP ${format(b.enemyHp)} / ${format(f.hp)}`;$('#tower-enemy-bar').style.width=(100*b.enemyHp/f.hp)+'%';$('#tower-player-hp').textContent=`내 HP ${format(b.hp)} / ${format(b.power.hp)}`;$('#tower-player-bar').style.width=(100*b.hp/b.power.hp)+'%';const left=Math.max(0,f.seconds-Math.floor(b.tick/10));$('#tower-clock').textContent=`${Math.floor(left/60)}:${String(left%60).padStart(2,'0')}`;
 const failed=this.required.some(src=>image(src).complete&&!image(src).naturalWidth);$('#tower-status').textContent=failed?'이미지를 불러오지 못했어요. 나갔다 다시 도전해 주세요.':!this.loaded?'전투 이미지를 불러오는 중…':this.error||this.frames.length>=25?'연결 대기 중 · 잠시만 기다려 주세요.':b.ended?'전투 결과를 저장하고 있어요…':b.tick<b.enemyCastUntil?f.pattern+' · 회피!':Math.hypot(b.player.x-b.enemy.x,b.player.y-b.enemy.y)>TOWER_CLASSES[b.classId].range?'보스에게 다가가 공격하세요.':f.guide;
 for(const [bit,key] of [[2,'skillReady'],[4,'dashReady'],[8,'ultimateReady']]){const el=this.host.querySelector(`[data-tower-button="${bit}"]`),sec=Math.max(0,Math.ceil((b[key]-b.tick)/10));el.classList.toggle('cooldown',sec>0);el.querySelector('b').textContent=sec?sec+'s':'';}
 }
 dispose(){this.disposed=true;cancelAnimationFrame(this.frame);this.abort.abort();this.resetInput();}
}
