import {FIFTH_SKILLS,fifthUnlocked,beginFifth,stepFifth} from './fifth-job.mjs?v=fifth-impact-121';
import {prepareFifthArt,drawFifth,drawFifthGround} from './fifth-effects.mjs?v=fifth-impact-121';
import {towerArena} from './tower-client.mjs?v=fifth-impact-121';
import {CLASS_SKILLS,SECOND_SKILLS,beginCombatSkill,stepCombatSkills} from './combat-skills.mjs?v=priest-potential-83';
import {THIRD_SKILLS,beginThird,stepThird,firstJobUnlocked} from './advancement.mjs?v=fifth-114';
import {FOURTH_SKILLS,beginFourth,stepFourth} from './fourth-job.mjs?v=fifth-114';
const SKILLS=[CLASS_SKILLS.warrior,SECOND_SKILLS.warrior,THIRD_SKILLS.warrior,FOURTH_SKILLS.warrior,FIFTH_SKILLS.warrior];
// Administrator-only, reward-free local 3D combat laboratory.
let current=null;
export function closeWarriorLab(){current?.dispose();current=null;}
export async function openWarriorLab({getState,onClose,sound=()=>{}}){
 const account=getState();
 if(!account?.isAdmin||account.classId!=='warrior')throw Error('관리자 전사만 입장할 수 있습니다.');
 if(account.battle||account.coopRoom||account.partyRoom)throw Error('진행 중인 전투를 끝내고 입장해 주세요.');
 closeWarriorLab();
 const host=document.createElement('section');host.className='wl-overlay';host.setAttribute('aria-label','전사 3D 테스트 전투');
 host.innerHTML=`<div class="wl-stage"></div><div class="wl-head"><small>관리자 전용 · 전사 · 연습</small><strong>잿불 성채의 파수꾼</strong><div class="wl-bar"><i data-hp="boss"></i></div><small data-wl="bossinfo"></small><div class="wl-bar-row"><span>전사</span><div class="wl-bar wl-player"><i data-hp="player"></i></div><span data-wl="hp"></span></div></div><button class="wl-close" aria-label="전투 나가기">나가기</button><div class="wl-notice" aria-live="polite"></div><div class="wl-joystick" aria-label="이동 조이스틱"><div class="wl-stick"></div></div><div class="wl-keys"><div class="wl-skill-bar">${SKILLS.map((sk,i)=>`<button data-wl="skill${i+1}" title="${sk.description}">${sk.name}<small>${['K','L','I','O','U'][i]} · ${sk.cooldown}초</small></button>`).join('')}</div><div class="wl-core-actions"><button data-wl="dash">회피<small>Space</small></button><button data-wl="attack">공격<small>J · 길게 누르기</small></button></div></div><div class="wl-help">이동 WASD / 방향키 · 검격 J · 스킬 1–4 · 회피 Space</div><div class="wl-result" hidden><div class="wl-result-card"><h2></h2><p></p><button data-wl="retry">다시 도전</button><button data-wl="leave">나가기</button></div></div><div class="wl-loading">성채에 입장하는 중…</div>`;
 const native=document.createElement('div');native.className='tower-play wl-native-controls';const template=document.createElement('template');template.innerHTML=towerArena({floor:1,classId:'warrior',runId:'lab-controls',power:{level:account.level,firstJob:firstJobUnlocked(account),advancement:account.advancement||0},advanced:(account.advancement||0)>=1,third:(account.advancement||0)>=2});const controls=template.content.querySelector('.tower-controls');native.append(controls);host.querySelector('.wl-joystick').remove();host.querySelector('.wl-keys').replaceWith(native);const joystick=controls.querySelector('.tower-stick');joystick.setAttribute('data-wl-joystick','');joystick.removeAttribute('id');const knob=joystick.querySelector('i');knob.setAttribute('data-wl-knob','');knob.removeAttribute('id');joystick.style.backgroundImage="url('./lab-art/control-joystick-v2.webp')";joystick.style.backgroundSize='100% 100%';knob.style.backgroundImage="url('./lab-art/control-knob-v2.webp')";knob.style.backgroundSize='100% 100%';const actions={'1':'attack','4':'dash','8':'skill1','2':'skill2','16':'skill3','32':'skill4','64':'skill5'};for(const button of controls.querySelectorAll('[data-tower-button]')){const kind=actions[button.dataset.towerButton];button.dataset.wl=kind;button.removeAttribute('data-tower-button');button.querySelectorAll('i').forEach(i=>i.remove());button.style.backgroundImage="url('./lab-art/control-"+(kind==='attack'?'attack':kind==='dash'?'dash':'skill')+"-v2.webp')";button.style.backgroundSize='100% 100%';}document.body.append(host);const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
 let abandoned=false;
 const placeholder={dispose(){abandoned=true;host.remove();document.body.style.overflow=oldOverflow;}};current=placeholder;
 host.querySelector('.wl-close').onclick=()=>{closeWarriorLab();onClose?.();};
 try{
  const T=await import('./vendor/three/three.module.min.js');
  const assets=await Promise.all(['arena','actors','effects','red-slash','orbit-sword','running'].map(name=>new Promise((resolve,reject)=>{const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>reject(Error('전투 이미지를 불러오지 못했습니다.'));img.src=new URL('./lab-art/'+name+(name==='running'?'-real-v4.webp':name==='orbit-sword'?'-fire-v5.webp':'-real-v3.webp'),import.meta.url).href;})));
  if(abandoned)return;
  await prepareFifthArt(['warrior'],src=>{const im=new Image();im.src=new URL(src,import.meta.url).href;return im;});
  if(!getState()?.isAdmin||getState()?.classId!=='warrior'){closeWarriorLab();return;}
  current=new Arena(T,host,{getState,onClose,sound,oldOverflow,assets});
  host.querySelector('.wl-loading').remove();
 }catch(e){if(abandoned)return;host.querySelector('.wl-loading').textContent='3D 화면을 열지 못했습니다. 나가기를 눌러 다시 시도해 주세요.';host.querySelector('.wl-close').style.zIndex=5;throw e;}
}
class Arena{
 constructor(T,host,opts){this.T=T;this.host=host;this.opts=opts;this.listeners=[];this.keys=new Set();this.move={x:0,z:0};this.attackHeld=false;this.running=true;this.paused=false;this.effects=[];this.shots=[];this.hazards=[];this.floaters=[];this.time=0;this.pattern=0;this.shake=0;this.combo=0;this.lastCombo=-5;
 this.scene=new T.Scene();this.scene.background=new T.Color('#24394b');this.scene.fog=new T.Fog('#24394b',24,48);
 this.camera=new T.PerspectiveCamera(43,1,.1,80);this.assets=opts.assets;this.actorFrames=this.sliceActors(opts.assets[1]);this.runFrames=this.sliceActors(opts.assets[5]);this.effectFrames=this.sliceActors(opts.assets[2],4,4,false);const canvas=document.createElement('canvas');this.ctx=canvas.getContext('2d',{alpha:false});if(!this.ctx)throw Error('이미지 전투 화면을 열지 못했습니다.');this.renderer={domElement:canvas,setSize:(w,h)=>{canvas.width=Math.round(w*Math.min(devicePixelRatio||1,3));canvas.height=Math.round(h*Math.min(devicePixelRatio||1,3));},dispose(){},forceContextLoss(){}};host.querySelector('.wl-stage').append(canvas);
const rim=new T.DirectionalLight(0x62aaff,2);rim.position.set(7,5,-7);this.scene.add(rim);
 this.materials={};this.obstacles=[{x:-11.4,z:-10,r:1},{x:11.4,z:-10,r:1},{x:-11.4,z:10,r:1},{x:11.4,z:10,r:1}];this.player=this.character(false);this.boss=this.character(true);this.scene.add(this.player.root,this.boss.root);this.reset();this.bind();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.previous=performance.now();this.frame=requestAnimationFrame(t=>this.loop(t));
 }
 mat(color,metal=.05,rough=.65){const key=color+':'+metal+':'+rough;return this.materials[key]??=new this.T.MeshStandardMaterial({color,metalness:metal,roughness:rough});}
 mesh(geo,color,parent,pos=[0,0,0],metal=.05){const m=new this.T.Mesh(geo,this.mat(color,metal));m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(w,h,d,color,parent,pos,metal){return this.mesh(new this.T.BoxGeometry(w,h,d),color,parent,pos,metal);}
 sphere(r,color,parent,pos){return this.mesh(new this.T.SphereGeometry(r,16,12),color,parent,pos);}
 buildArena(){const T=this.T;const floor=this.box(21,.55,31,'#607079',this.scene,[0,-.35,0]);floor.castShadow=false;
 const tileGeo=new T.BoxGeometry(1.93,.13,1.93);for(let x=-9;x<=9;x+=2)for(let z=-14;z<=14;z+=2){const tile=this.mesh(tileGeo,((x+z)%4===0?'#788389':'#68777c'),this.scene,[x,-.02,z]);tile.castShadow=false;}
 const borderGeo=new T.BoxGeometry(1.95,1.4,.85);for(let x=-10;x<=10;x+=2)for(const z of [-15.3,15.3]){this.mesh(borderGeo,'#555b68',this.scene,[x,.55,z]);this.box(2,.2,1,'#8d8b82',this.scene,[x,1.34,z]);}
 const sideGeo=new T.BoxGeometry(.85,1.4,1.95);for(let z=-14;z<=14;z+=2)for(const x of [-10.5,10.5]){this.mesh(sideGeo,'#555b68',this.scene,[x,.55,z]);this.box(1,.2,2,'#8d8b82',this.scene,[x,1.34,z]);}
 this.obstacles=[{x:-11.4,z:-10,r:1},{x:11.4,z:-10,r:1},{x:-11.4,z:10,r:1},{x:11.4,z:10,r:1}];
 for(const o of this.obstacles){this.box(2.2,.38,2.2,'#444f60',this.scene,[o.x,.18,o.z]);this.mesh(new T.CylinderGeometry(.8,1,2.9,8),'#8a9295',this.scene,[o.x,1.8,o.z]);this.mesh(new T.CylinderGeometry(1.05,1.05,.28,8),'#a8a69d',this.scene,[o.x,3.3,o.z]);this.mesh(new T.CylinderGeometry(.62,.78,.55,8),'#3c3546',this.scene,[o.x,3.75,o.z]);const fire=this.sphere(.3,'#ffb554',this.scene,[o.x,4.1,o.z]);fire.material=this.mat('#ffae48');fire.material.emissive=new T.Color('#ff8a23');fire.material.emissiveIntensity=2;const light=new T.PointLight(0xff974f,6,7);light.position.set(o.x,4,o.z);this.scene.add(light);}
 const rune=new T.Mesh(new T.RingGeometry(3.5,3.58,64),new T.MeshBasicMaterial({color:0xcdb28c,transparent:true,opacity:.5,side:T.DoubleSide}));rune.rotation.x=-Math.PI/2;rune.position.y=.08;this.scene.add(rune);
 }
 character(boss){const T=this.T,root=new T.Group(),body=new T.Group();root.add(body);const scale=boss?1.75:1;root.scale.setScalar(scale);const steel=boss?'#4c485d':'#91b8cd',gold=boss?'#d29351':'#dcb66d',cloth=boss?'#842d3a':'#234f87';
 const torso=this.mesh(new T.CylinderGeometry(.47,.36,.7,8),steel,body,[0,1.2,0],.5);this.box(.22,.43,.12,gold,body,[0,1.2,.43],.7);this.mesh(new T.CylinderGeometry(.39,.52,.4,8),cloth,body,[0,.75,0]);
 const head=this.sphere(.33,boss?'#655163':'#e6b793',body,[0,1.83,0]);const helm=this.mesh(new T.SphereGeometry(.37,16,12,0,Math.PI*2,0,Math.PI*.57),steel,body,[0,1.88,0],.5);this.box(.7,.15,.16,steel,body,[0,1.88,.25],.55);this.box(.57,.07,.05,boss?'#ff6b42':'#173548',body,[0,1.84,.355]);this.box(.09,.45,.09,gold,body,[0,2.02,.34],.6);
 if(boss){for(const sign of [-1,1]){const horn=this.mesh(new T.ConeGeometry(.13,.63,8),gold,body,[sign*.41,2.1,0]);horn.rotation.z=-sign*.65;}}else{const plume=this.mesh(new T.CapsuleGeometry(.13,.5,4,8),'#ba3749',body,[0,2.22,-.1]);plume.rotation.x=.8;}
 const cape=this.box(.69,.98,.12,cloth,body,[0,1.12,-.38]);cape.rotation.x=-.18;
 const arms=[],legs=[];for(const sign of [-1,1]){const leg=new T.Group();leg.position.set(sign*.23,.72,0);body.add(leg);this.mesh(new T.CapsuleGeometry(.15,.33,4,8),'#263346',leg,[0,-.27,0]);this.box(.29,.25,.44,steel,leg,[0,-.58,.08],.4);legs.push(leg);
 const arm=new T.Group();arm.position.set(sign*.56,1.47,0);body.add(arm);this.sphere(.25,steel,arm,[0,-.03,0]);this.mesh(new T.CapsuleGeometry(.12,.31,4,8),cloth,arm,[0,-.32,0]);this.sphere(.14,gold,arm,[0,-.58,0]);arms.push(arm);}
 const weapon=new T.Group();arms[1].add(weapon);weapon.position.set(0,-.58,.12);this.mesh(new T.CylinderGeometry(.065,.065,.35,8),'#573846',weapon,[0,.02,0]);this.box(.68,.1,.12,gold,weapon,[0,.24,0],.7);const blade=this.box(boss?.37:.19,boss?1.25:1.08,.065,boss?'#c38671':'#def4ff',weapon,[0,.87,0],.7);const tip=this.mesh(new T.ConeGeometry(boss?.24:.14,.36,4),boss?'#ffe0aa':'#effbff',weapon,[0,1.62,0],.65);tip.rotation.y=Math.PI/4;
 const shield=this.mesh(new T.CylinderGeometry(.36,.36,.13,8),steel,arms[0],[0,-.36,.16],.5);shield.rotation.x=Math.PI/2;this.sphere(.13,gold,arms[0],[0,-.36,.27]);
 return {root,body,arms,legs,cape,weapon,x:0,z:0,hp:boss?6000:100,max:boss?6000:100,r:boss?.95:.48,attack:0,inv:0,hit:0,walk:0,angle:0};
 }
 reset(){this.clearTransient();this.time=0;this.pattern=0;this.nextPattern=2;this.cast=null;this.enraged=false;this.done=false;this.combo=0;this.lastCombo=-5;this.cooldowns={attack:0,dash:0};this.fifthEffects=[];this.skillActor={id:'warrior',classId:'warrior',x:0,y:0,power:{level:this.opts.getState().level,firstJob:firstJobUnlocked(this.opts.getState()),advancement:this.opts.getState().advancement||0},advancement:this.opts.getState().advancement||0};Object.assign(this.player,{x:0,z:7,hp:100,inv:1,attack:0,hit:0,angle:Math.PI});Object.assign(this.boss,{x:0,z:-4,hp:6000,attack:0,hit:0,angle:0});this.dash=null;this.camX=this.player.x;this.camZ=this.player.z-2.5;this.host.querySelector('.wl-result').hidden=true;this.keys.clear();this.move={x:0,z:0};this.attackHeld=false;this.notice('벽과 기둥을 이용해 투사체를 피하세요');this.updateHUD();}
 bind(){const listen=(el,type,fn,options)=>{el.addEventListener(type,fn,options);this.listeners.push(()=>el.removeEventListener(type,fn,options));};
 this.host.querySelector('.wl-close').onclick=()=>this.leave();this.host.querySelector('[data-wl="leave"]').onclick=()=>this.leave();this.host.querySelector('[data-wl="retry"]').onclick=()=>this.reset();
 const joy=this.host.querySelector('[data-wl-joystick]'),stick=joy.querySelector('[data-wl-knob]');let pointer=null;
 const update=e=>{const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),max=parseFloat(getComputedStyle(joy).getPropertyValue('--stick-travel'))||29,k=len>max?max/len:1;stick.style.transform=`translate(${dx*k}px,${dz*k}px)`;this.move={x:dx*k/max,z:dz*k/max};};
 listen(joy,'pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;joy.setPointerCapture(pointer);update(e);e.preventDefault();});listen(joy,'pointermove',e=>{if(e.pointerId===pointer)update(e);});const release=e=>{if(e.pointerId!==pointer)return;pointer=null;this.move={x:0,z:0};stick.style.transform='';};listen(joy,'pointerup',release);listen(joy,'pointercancel',release);listen(joy,'lostpointercapture',release);
 for(const kind of ['attack','skill1','skill2','skill3','skill4','skill5','dash']){const button=this.host.querySelector(`[data-wl="${kind}"]`);listen(button,'pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);if(kind==='attack')this.attackHeld=true;this.skill(kind);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])listen(button,ev,()=>{if(kind==='attack')this.attackHeld=false;});}
 listen(window,'keydown',e=>{if(!['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyJ','KeyK','KeyL','KeyI','KeyO','KeyU','Digit1','Digit2','Digit3','Digit4','Digit5','Space','Escape'].includes(e.code))return;e.preventDefault();if(e.code==='Escape'){this.leave();return;}this.keys.add(e.code);if(e.code==='KeyJ')this.attackHeld=true;if(!e.repeat&&['KeyK','KeyL','KeyI','KeyO','KeyU'].includes(e.code))this.skill('skill'+(['KeyK','KeyL','KeyI','KeyO','KeyU'].indexOf(e.code)+1));if(!e.repeat&&/^Digit[1-5]$/.test(e.code))this.skill('skill'+e.code.slice(-1));if(!e.repeat&&e.code==='Space')this.skill('dash');});listen(window,'keyup',e=>{this.keys.delete(e.code);if(e.code==='KeyJ')this.attackHeld=false;});
 const clear=()=>{this.keys.clear();this.attackHeld=false;this.move={x:0,z:0};pointer=null;stick.style.transform='';};listen(window,'blur',()=>{clear();this.paused=true;});listen(window,'focus',()=>{this.paused=document.hidden;this.previous=performance.now();});listen(document,'visibilitychange',()=>{clear();this.paused=document.hidden;this.previous=performance.now();});listen(this.renderer.domElement,'webglcontextlost',e=>{e.preventDefault();this.paused=true;this.finish(false,'그래픽 연결이 중단됐습니다. 나간 뒤 다시 입장해 주세요.');});
 }
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h,false);this.width=w;this.height=h;this.scale=Math.max(w/16,(h-120)/25);this.camX??=this.player.x;this.camZ??=this.player.z-2.5;this.originX=w/2-this.camX*this.scale;this.originY=h*.46-this.camZ*this.scale;}
 leave(){closeWarriorLab();this.opts.onClose?.();}
 notice(text){this.host.querySelector('.wl-notice').textContent=text;}
 skill(kind){if(this.done||this.paused||!this.running||(this.cooldowns[kind]||0)>this.time)return;const p=this.player,b=this.boss;let dx=b.x-p.x,dz=b.z-p.z,len=Math.hypot(dx,dz)||1;
 if(kind.startsWith('skill')){const slot=Number(kind.slice(-1)),tick=Math.floor(this.time*10),a=this.skillActor,target={id:'guardian',x:b.x*100,y:b.z*100};a.x=p.x*100;a.y=p.z*100;const ok=slot<=2?beginCombatSkill(a,target,tick,slot):slot===3?beginThird(a,target,tick):slot===4?beginFourth(a,target,tick):beginFifth(a,target,tick);if(ok){p.angle=Math.atan2(dx,dz);p.attack=.5;p.attackDuration=.5;this.notice(SKILLS[slot-1].name);this.opts.sound('warrior-skill-'+slot);}return;}
 if(kind==='attack'){this.cooldowns.attack=this.time+.9;const move=this.direction();if(len<3.5)p.angle=Math.atan2(dx,dz);else if(Math.hypot(move.x,move.z)>.05)p.angle=Math.atan2(move.x,move.z);p.attack=.32;p.attackDuration=.32;const forward={x:Math.sin(p.angle),z:Math.cos(p.angle)};this.arc({x:p.x+forward.x*.75,z:p.z+forward.z*.75},0xc5eeff,1.6,.3,p.angle,1.8);const effect=this.effects.at(-1);effect.art=0;effect.artSize=3.2;effect.artAngle=Math.atan2(forward.z,forward.x)+Math.PI;if(len<2.925&&(dx/len*forward.x+dz/len*forward.z)>.35){this.hurt(b,140);this.spark(b.x,1.6,b.z,0xffe4a6,10);}this.opts.sound('warrior-attack');}
 if(kind==='dash'){this.cooldowns.dash=this.time+3;const movement=this.direction();if(Math.hypot(movement.x,movement.z)>.1){dx=movement.x;dz=movement.z;len=Math.hypot(dx,dz);}this.dash={x:dx/len,z:dz/len,left:.22};p.angle=Math.atan2(dx,dz);p.inv=.38;this.opts.sound('battle-dash');}
 }
 stepSkills(){const a=this.skillActor,p=this.player,b=this.boss,tick=Math.floor(this.time*10),target={id:'guardian',x:b.x*100,y:b.z*100};a.x=p.x*100;a.y=p.z*100;
 const hit=scale=>{if(!this.done)this.hurt(b,Math.round(140*scale));};const emit=e=>{if(e.kind==='fifth'||e.kind==='fifth-field'){this.fifthEffects.push(e);return;}const x=e.x/100,z=e.y/100;if(e.kind==='third'){this.redSlash(e.fromX/100,e.fromY/100,x,z,e.angle||0);this.opts.sound('warrior-skill-3');return;}if(e.phase==='charge'){this.stamp(6,x,z,3.8,.4);return;}if(e.phase==='pulse'){if(e.final){this.swordBurst(x,z,1,.5);}else{const fromX=e.fromX/100,fromZ=e.fromY/100;this.stamp(0,fromX,fromZ,3.5,.25,Math.atan2(z-fromZ,x-fromX)+Math.PI);this.stamp(1,x,z,5.4,.4);}this.spark(x,.7,z,e.final?0xffdf92:0xc5eaff,8);}if(e.kind==='fourth'){this.swordOrbit(p,e.pulse);}};
 stepCombatSkills(a,[target],tick,hit,emit);stepThird(a,target,tick,hit,emit);// Lab-only radius is 70% of the previous doubled range; shared damage timeline is retained.
 const saved={x:a.x,y:a.y,castX:a.fourthCast?.x,castY:a.fourthCast?.y};a.x/=1.4;a.y/=1.4;if(a.fourthCast){a.fourthCast.x/=1.4;a.fourthCast.y/=1.4;}stepFourth(a,{...target,x:target.x/1.4,y:target.y/1.4},tick,hit,e=>emit({...e,x:e.x*1.4,y:e.y*1.4,size:e.size*1.4}));a.x=saved.x;a.y=saved.y;if(a.fourthCast){a.fourthCast.x=saved.castX;a.fourthCast.y=saved.castY;}
 stepFifth(a,[{...target,hp:b.hp,maxHp:b.max}],tick,hit,emit);this.fifthEffects=this.fifthEffects.filter(e=>e.end>tick);
 // First-job impact follows the same 0.3-second damage pulse as the existing game.
 if(a.firstCast&&tick>=a.firstCast.start+2&&!a.firstCast.labShown){a.firstCast.labShown=true;this.stamp(1,a.firstCast.target.x/100,a.firstCast.target.y/100,7.2,.6);this.stamp(5,a.firstCast.target.x/100,a.firstCast.target.y/100,5.2,.45);this.shake=.12;}
 }
 stamp(art,x,z,size,life,angle=0){const mesh=new this.T.Group();mesh.position.set(x,0,z);this.scene.add(mesh);this.effects.push({mesh,left:life,max:life,art,artSize:size,artAngle:angle});}
 redSlash(fromX,fromZ,toX,toZ,fan){const mesh=new this.T.Group();mesh.position.set(fromX,0,fromZ);this.scene.add(mesh);this.effects.push({mesh,left:.55,max:.55,red:true,fromX,fromZ,toX,toZ,angle:Math.atan2(toZ-fromZ,toX-fromX),fan});}
 swordBurst(x,z,count,life){for(let i=0;i<count;i++){const T=this.T,root=new T.Group();root.position.set(x+(i-.5)*.7,.2,z);const blade=new T.Mesh(new T.BoxGeometry(.22,3.4,.09),new T.MeshStandardMaterial({color:0xd9f2ff,emissive:0x66aaff,emissiveIntensity:1.3,transparent:true,metalness:.65,roughness:.2}));root.add(blade);const guard=new T.Mesh(new T.BoxGeometry(.9,.15,.18),new T.MeshBasicMaterial({color:0xffdc89,transparent:true}));guard.position.y=-1;root.add(guard);root.rotation.z=.15*(i%2?1:-1);this.scene.add(root);this.effects.push({mesh:root,left:life,max:life,rise:4,art:2,artSize:5});}}
 swordOrbit(p,pulse){const root=new this.T.Group();root.position.set(p.x,0,p.z);this.scene.add(root);this.effects.push({mesh:root,left:.38,max:.38,swordRing:true,phase:pulse*.32,rings:4,count:4,outerRadius:FOURTH_SKILLS.warrior.radius*.014,swordLength:1.8});}
 direction(){let x=this.move.x,z=this.move.z;x+=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);z+=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);const n=Math.hypot(x,z);return n>1?{x:x/n,z:z/n}:{x,z};}
 moveActor(a,dx,dz){a.x=Math.max(-19.4+a.r,Math.min(19.4-a.r,a.x+dx));a.z=Math.max(-29.3+a.r,Math.min(29.3-a.r,a.z+dz));for(const o of this.obstacles){const x=a.x-o.x,z=a.z-o.z,n=Math.hypot(x,z),r=a.r+o.r;if(n<r){a.x=o.x+(n?x/n:1)*r;a.z=o.z+(n?z/n:0)*r;}}}
 hurt(a,n){if(a===this.player&&a.inv>0)return;a.hp=Math.max(0,a.hp-n);a.hit=.18;if(a===this.player){a.inv=.65;this.shake=.18;this.opts.sound('battle-hurt');}this.floating(a,n);if(a.hp<=0)this.finish(a===this.boss);}
 finish(won,custom){if(this.done)return;this.done=true;this.attackHeld=false;this.keys.clear();this.move={x:0,z:0};this.notice(won?'파수꾼 처치':'전투 종료');const panel=this.host.querySelector('.wl-result');panel.hidden=false;panel.querySelector('h2').textContent=won?'성채 정복':'다시 도전';panel.querySelector('p').textContent=custom||`${Math.floor(this.time)}초 전투 · ${won?'파수꾼을 쓰러뜨렸습니다.':'공격 예고를 보고 돌진으로 피하세요.'} 관리자 연습 전투로 재화와 도전 횟수는 소비되지 않으며 보상은 없습니다.`;panel.querySelector('[data-wl="retry"]').hidden=!!custom;this.opts.sound(won?'battle-victory':'battle-defeat');}
 floating(a,n){const el=document.createElement('b');el.textContent='−'+n;Object.assign(el.style,{position:'absolute',color:a===this.player?'#ff8585':'#fff1ab',fontSize:a===this.player?'20px':'24px',fontWeight:'900',textShadow:'0 2px 3px #000',pointerEvents:'none',transform:'translate(-50%,-50%)'});this.host.append(el);this.floaters.push({el,x:a.x,z:a.z,y:a===this.player?2.4:3.7,left:.8});}
 arc(a,color,r,life,angle,length){const T=this.T,mat=new T.MeshBasicMaterial({color,transparent:true,opacity:.85,side:T.DoubleSide,depthWrite:false});const mesh=new T.Mesh(new T.RingGeometry(r-.23,r,40,1,0,length),mat);mesh.rotation.x=-Math.PI/2;mesh.rotation.z=-(angle+Math.PI/2+length/2);mesh.position.set(a.x,.8,a.z);this.scene.add(mesh);this.effects.push({mesh,left:life,max:life,spin:length>6?10:0,rise:.1});}
 spark(x,y,z,color,count=12){const T=this.T;for(let i=0;i<count;i++){const m=new T.Mesh(new T.IcosahedronGeometry(.07,0),new T.MeshBasicMaterial({color,transparent:true}));m.position.set(x,y,z);this.scene.add(m);this.effects.push({mesh:m,left:.45,max:.45,v:{x:(Math.random()-.5)*7,y:Math.random()*5,z:(Math.random()-.5)*7}});}}
 ring(x,z,r,color,opacity=.3){const T=this.T,m=new T.Mesh(new T.CircleGeometry(r,48),new T.MeshBasicMaterial({color,transparent:true,opacity,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.13,z);this.scene.add(m);return m;}
 startPattern(){const b=this.boss,p=this.player,k=this.pattern++%4;const dx=p.x-b.x,dz=p.z-b.z,angle=Math.atan2(dx,dz);b.angle=angle;
 if(k===0){this.notice('화염 산탄 · 기둥 뒤로 피하세요');this.cast={kind:'fan',left:.85,angle,marks:[this.ring(b.x,b.z,1.8,0xff874a)]};}
 if(k===1){this.notice('내려찍기 · 붉은 원에서 벗어나세요');this.cast={kind:'slam',left:1.05,x:p.x,z:p.z,marks:[this.ring(p.x,p.z,2.8,0xff4444)]};}
 if(k===2){this.notice('파수꾼 돌진 · 옆으로 피하세요');const T=this.T,mark=new T.Mesh(new T.PlaneGeometry(2.5,10),new T.MeshBasicMaterial({color:0xff614c,transparent:true,opacity:.32,side:T.DoubleSide,depthWrite:false}));mark.rotation.x=-Math.PI/2;mark.rotation.z=-angle;mark.position.set(b.x+Math.sin(angle)*5,.12,b.z+Math.cos(angle)*5);this.scene.add(mark);this.cast={kind:'charge',left:1,angle,marks:[mark]};}
 if(k===3){this.notice('화염 파동 · 틈으로 이동하거나 돌진하세요');this.cast={kind:'nova',left:1.1,marks:[this.ring(b.x,b.z,3.2,0xff874a)]};}
 this.opts.sound('boss-warning');}
 releasePattern(c){const b=this.boss,p=this.player;for(const m of c.marks)this.remove(m);this.cast=null;b.attack=.6;this.nextPattern=this.time+(this.enraged?1.8:2.7);
 if(c.kind==='fan'){for(let i=-2;i<=2;i++)this.projectile(b.x,b.z,c.angle+i*.23,8.5,12);if(this.enraged)for(let i=-1;i<=1;i++)this.projectile(b.x,b.z,c.angle+i*.4,6.5,12);}
 if(c.kind==='slam'){this.spark(c.x,.3,c.z,0xffae50,24);this.arc({x:c.x,z:c.z},0xff9c42,2.8,.5,0,Math.PI*2);if(Math.hypot(p.x-c.x,p.z-c.z)<2.8+p.r)this.hurt(p,24);this.shake=.15;this.opts.sound('battle-crit');}
 if(c.kind==='charge')this.bossCharge={x:Math.sin(c.angle),z:Math.cos(c.angle),left:.7,hit:false};
 if(c.kind==='nova'){const offset=this.pattern*.41;for(let i=0;i<14;i++)if(i!==3&&i!==4)this.projectile(b.x,b.z,offset+i*Math.PI*2/14,5.4,14);}
 }
 projectile(x,z,angle,speed,damage){const T=this.T,root=new T.Group();root.position.set(x,.65,z);const orb=new T.Mesh(new T.IcosahedronGeometry(.28,1),new T.MeshStandardMaterial({color:0xffd176,emissive:0xff681d,emissiveIntensity:2,roughness:.2}));root.add(orb);const tail=new T.Mesh(new T.ConeGeometry(.22,.95,8),new T.MeshBasicMaterial({color:0xff732e,transparent:true,opacity:.65}));tail.rotation.x=Math.PI/2;tail.position.z=-.5;root.add(tail);root.rotation.y=angle;this.scene.add(root);this.shots.push({mesh:root,x,z,vx:Math.sin(angle)*speed,vz:Math.cos(angle)*speed,left:5,damage});}
 update(dt){const p=this.player,b=this.boss;this.time+=dt;if(!this.opts.getState()?.isAdmin||this.opts.getState()?.classId!=='warrior'){this.leave();return;}for(const a of [p,b]){a.inv=Math.max(0,a.inv-dt);a.attack=Math.max(0,a.attack-dt);a.hit=Math.max(0,a.hit-dt);}this.shake=Math.max(0,this.shake-dt);
 if(!this.done){let dir=this.direction();if(this.dash){this.moveActor(p,this.dash.x*21*dt,this.dash.z*21*dt);this.dash.left-=dt;if(this.dash.left<=0)this.dash=null;}else{this.moveActor(p,dir.x*4.6*dt,dir.z*4.6*dt);if(Math.hypot(dir.x,dir.z)>.05)p.angle=Math.atan2(dir.x,dir.z);}p.speed=Math.hypot(dir.x,dir.z);p.walk+=p.speed*dt*10;
 if(this.attackHeld)this.skill('attack');this.stepSkills();if(!this.enraged&&b.hp<=b.max*.5){this.enraged=true;this.notice('분노 · 공격 간격이 빨라집니다');this.opts.sound('boss-warning');}
 if(this.bossCharge){const c=this.bossCharge;this.moveActor(b,c.x*13*dt,c.z*13*dt);c.left-=dt;if(!c.hit&&Math.hypot(b.x-p.x,b.z-p.z)<b.r+p.r){c.hit=true;this.hurt(p,26);}if(c.left<=0)this.bossCharge=null;}
 else if(this.cast){this.cast.left-=dt;for(const m of this.cast.marks)m.material.opacity=.22+.16*Math.sin(this.time*14);if(this.cast.left<=0)this.releasePattern(this.cast);}
 else if(this.time>=this.nextPattern)this.startPattern();
 else{const dx=p.x-b.x,dz=p.z-b.z,n=Math.hypot(dx,dz)||1;b.angle=Math.atan2(dx,dz);if(n>3.2){this.moveActor(b,dx/n*1.2*dt,dz/n*1.2*dt);b.walk+=dt*5;}}
 const distance=Math.hypot(p.x-b.x,p.z-b.z),min=p.r+b.r;if(distance<min){this.moveActor(p,(p.x-b.x)/(distance||1)*(min-distance),(p.z-b.z)/(distance||1)*(min-distance));}
 }
 for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];if(!this.done){s.x+=s.vx*dt;s.z+=s.vz*dt;}s.left-=dt;s.mesh.position.set(s.x,.65+Math.sin(this.time*12)*.04,s.z);s.mesh.children[0].rotation.y+=dt*5;let remove=s.left<=0||Math.abs(s.x)>20||Math.abs(s.z)>30||this.obstacles.some(o=>Math.hypot(s.x-o.x,s.z-o.z)<o.r+.2);if(!this.done&&Math.hypot(s.x-p.x,s.z-p.z)<p.r+.25){this.hurt(p,s.damage);remove=true;}if(remove){this.spark(s.x,.6,s.z,0xffb868,4);this.remove(s.mesh);this.shots.splice(i,1);}}
 for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.left-=dt;e.mesh.traverse(m=>{if(m.material)m.material.opacity=Math.max(0,e.left/e.max);});if(e.orbit)e.mesh.rotation.y+=e.orbit*dt;if(e.spin)e.mesh.rotation.z+=e.spin*dt;if(e.rise)e.mesh.position.y+=dt*e.rise;if(e.v){e.v.y-=10*dt;e.mesh.position.x+=e.v.x*dt;e.mesh.position.y+=e.v.y*dt;e.mesh.position.z+=e.v.z*dt;}if(e.left<=0){this.remove(e.mesh);this.effects.splice(i,1);}}
 for(const a of [p,b])this.animate(a,dt);this.updateHUD();}
 animate(a,dt){a.root.position.set(a.x,0,a.z);const target=a.angle;let delta=Math.atan2(Math.sin(target-a.root.rotation.y),Math.cos(target-a.root.rotation.y));a.root.rotation.y+=delta*Math.min(1,dt*18);const walking=a===this.player?(Math.hypot(this.direction().x,this.direction().z)>.1&&!this.done):(!this.cast&&!this.done&&Math.hypot(a.x-this.player.x,a.z-this.player.z)>3.2);const wave=walking?Math.sin(a.walk)*.52:Math.sin(this.time*2)*.025;a.legs[0].rotation.x=wave;a.legs[1].rotation.x=-wave;a.body.position.y=walking?Math.abs(Math.sin(a.walk))*.05:Math.sin(this.time*2)*.025;a.cape.rotation.x=-.18-wave*.12;a.arms[0].rotation.x=-wave*.45;a.arms[1].rotation.x=a.attack>0?-1.7+Math.sin(a.attack*19)*.9:wave*.45;a.arms[1].rotation.z=a.attack>0?-.6:0;a.body.rotation.z=a.hit>0?Math.sin(a.hit*70)*.13:0;if(a===this.player)a.root.visible=a.inv<=0||Math.floor(this.time*18)%3!==0;}
 updateHUD(){this.host.querySelector('[data-hp="boss"]').style.width=(this.boss.hp/this.boss.max*100)+'%';this.host.querySelector('[data-hp="player"]').style.width=this.player.hp+'%';this.host.querySelector('[data-wl="hp"]').textContent=Math.ceil(this.player.hp)+'/100';this.host.querySelector('[data-wl="bossinfo"]').textContent=Math.ceil(this.boss.hp).toLocaleString()+' / 6,000 · '+(this.enraged?'분노 · ':'')+Math.floor(this.time)+'초';for(const k of ['skill1','skill2','skill3','skill4','skill5','dash']){const el=this.host.querySelector(`[data-wl="${k}"]`);const slot=Number(k.slice(-1)),a=this.skillActor,unlocked=k==='dash'||(slot===5?fifthUnlocked(this.opts.getState()):slot===1?firstJobUnlocked(this.opts.getState()):(this.opts.getState().advancement||0)>=slot-1);const ready=k==='dash'?this.cooldowns.dash:(a[['ultimateReady','skillReady','thirdReady','fourthReady','fifthReady'][slot-1]]||0)/10;const left=Math.max(0,ready-this.time);el.disabled=left>0||this.done||!unlocked;el.querySelector('b').textContent=left>0?left.toFixed(1):'';el.style.setProperty('--cooldown',Math.min(100,left/(k==='dash'?3:SKILLS[slot-1].cooldown)*100)+'%');el.querySelector('small').textContent=!unlocked?'전직 필요':left>0?left.toFixed(1)+'초':k==='dash'?'Space · 준비':['K','L','I','O','U'][slot-1]+' · '+(slot===5?SKILLS[4].cooldown+'초':'준비');}}

 sliceActors(image,cols=8,rows=8,feet=true){
 // Generated atlases have unequal row spacing. Identify each complete connected
 // silhouette instead of cutting through a fixed mathematical grid.
 const source=document.createElement('canvas');source.width=image.width;source.height=image.height;const sc=source.getContext('2d');sc.drawImage(image,0,0);const pixels=sc.getImageData(0,0,source.width,source.height),data=pixels.data,w=source.width,h=source.height,labels=new Int32Array(w*h),queue=new Int32Array(w*h),parts=[];let label=0;
 for(let start=0;start<w*h;start++){if(labels[start]||data[start*4+3]<32)continue;label++;let head=0,tail=1,minX=w,minY=h,maxX=0,maxY=0;queue[0]=start;labels[start]=label;while(head<tail){const n=queue[head++],x=n%w,y=Math.floor(n/w);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);for(const next of [x>0?n-1:-1,x<w-1?n+1:-1,y>0?n-w:-1,y<h-1?n+w:-1])if(next>=0&&!labels[next]&&data[next*4+3]>=32){labels[next]=label;queue[tail++]=next;}}if(tail>500)parts.push({label,minX,minY,maxX,maxY,area:tail});}
 const figures=parts.sort((a,b)=>b.area-a.area).slice(0,cols*rows).sort((a,b)=>a.minY-b.minY);if(figures.length!==cols*rows)throw Error('캐릭터 동작 이미지 구성이 맞지 않습니다.');const ordered=[];for(let row=0;row<rows;row++)ordered.push(...figures.slice(row*cols,row*cols+cols).sort((a,b)=>a.minX-b.minX));
 const groups=feet?2:1,span=cols*rows/groups;const sizes=Array.from({length:groups},(_,group)=>Math.max(...ordered.slice(group*span,group*span+span).map(p=>Math.max((p.maxX-p.minX+1)*2,p.maxY-p.minY+1)))+48);
 return ordered.map((part,index)=>{const canvas=document.createElement('canvas'),size=sizes[Math.floor(index/span)];canvas.width=canvas.height=size;const ctx=canvas.getContext('2d'),out=ctx.createImageData(size,size);let sumX=0,weight=0;const footY=feet?part.maxY-(part.maxY-part.minY)*.18:part.minY;for(let y=Math.ceil(footY);y<=part.maxY;y++)for(let x=part.minX;x<=part.maxX;x++){const i=y*w+x;if(labels[i]===part.label){sumX+=x;weight++;}}const pivot=weight?sumX/weight:(part.minX+part.maxX)/2,ox=Math.round(size/2-pivot),oy=feet?size-24-part.maxY:Math.round((size-(part.maxY-part.minY+1))/2-part.minY);for(let y=Math.max(0,part.minY-2);y<=Math.min(h-1,part.maxY+2);y++)for(let x=Math.max(0,part.minX-2);x<=Math.min(w-1,part.maxX+2);x++){const i=y*w+x,dx=x+ox,dy=y+oy;if(dx<0||dx>=size||dy<0||dy>=size)continue;const belongs=labels[i]===part.label||(!labels[i]&&data[i*4+3]>0&&[i-1,i+1,i-w,i+w].some(n=>n>=0&&n<labels.length&&labels[n]===part.label));if(belongs)out.data.set(data.subarray(i*4,i*4+4),(dy*size+dx)*4);}ctx.putImageData(out,0,0);canvas.footPadding=24/size;canvas.bodyHeight=ordered.slice(Math.floor(index/span)*span,Math.floor(index/span)*span+cols).map(p=>p.maxY-p.minY+1).sort((a,b)=>a-b)[Math.floor(cols/2)];return canvas;});
 }
 screen(x,z){return {x:this.originX+x*this.scale,y:this.originY+z*this.scale};}
 drawCell(image,col,row,cols,rows,x,y,w,h,angle=0,alpha=1){const ctx=this.ctx,cw=image.width/cols,ch=image.height/rows;ctx.save();ctx.translate(x,y);ctx.rotate(angle);ctx.globalAlpha=alpha;ctx.drawImage(image,col*cw,row*ch,cw,ch,-w/2,-h/2,w,h);ctx.restore();}
 drawArt(){const ctx=this.ctx,dpr=Math.min(devicePixelRatio||1,3),w=this.width,h=this.height,scale=this.scale;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.globalAlpha=1;ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality='high';ctx.fillStyle='#111c29';ctx.fillRect(0,0,w,h);const top=this.screen(-21,-31);ctx.drawImage(this.assets[0],top.x,top.y,42*scale,62*scale);
 const fx=(id,x,z,size,angle=0,alpha=1)=>{const pt=this.screen(x,z);this.drawCell(this.effectFrames[id],0,0,1,1,pt.x,pt.y,size*scale,size*scale,angle,alpha);};
 for(const m of this.cast?.marks||[]){const r=m.geometry.parameters.radius||4;fx(6,m.position.x,m.position.z,r*2,0,.65+.18*Math.sin(this.time*12));if(this.cast.kind==='charge'){const b=this.boss,c=this.cast;for(let i=1;i<=4;i++)fx(6,b.x+Math.sin(c.angle)*i*2,b.z+Math.cos(c.angle)*i*2,2.5,0,.55);}}
 for(const a of [this.player,this.boss])fx(9,a.x,a.z,a===this.player?1.61:2.66,0,.55);
 const objects=[...this.obstacles.map(o=>({kind:'pillar',...o})),{kind:'actor',a:this.player,z:this.player.z},{kind:'actor',a:this.boss,z:this.boss.z}].sort((a,b)=>a.z-b.z);
 for(const o of objects){if(o.kind==='pillar'){const pt=this.screen(o.x,o.z);this.drawCell(this.effectFrames[8],0,0,1,1,pt.x,pt.y-1.2*scale,3.2*scale,3.8*scale);continue;}const a=o.a,pt=this.screen(a.x,a.z),boss=a===this.boss,walking=boss?!this.cast&&!this.done&&Math.hypot(a.x-this.player.x,a.z-this.player.z)>3.2:Math.hypot(this.direction().x,this.direction().z)>.1&&!this.done;const dir=((Math.round(-a.root.rotation.y/(Math.PI/4))%8)+8)%8;const attack=a.attack>0,phase=attack?Math.max(0,Math.min(1,1-a.attack/(a.attackDuration||.6))):0;const lunge=attack?Math.sin(phase*Math.PI)*.12:0;const x=pt.x+Math.sin(a.angle)*lunge*scale;const alpha=a===this.player&&a.inv>0?.78+.22*Math.sin(this.time*20):1;let frame;if(attack)frame=this.actorFrames[(3+(boss?4:0))*8+dir];else if(walking){const cycle=Math.floor(a.walk*.65)%4;frame=this.runFrames[(cycle+(boss?4:0))*8+dir];}else frame=this.actorFrames[(boss?4:0)*8+dir];const size=(boss?2.5:1.7)*scale*frame.width/frame.bodyHeight;const y=pt.y-size*.5+frame.footPadding*size+Math.cos(a.angle)*lunge*scale;this.drawCell(frame,0,0,1,1,x,y,size,size,0,alpha);}

 const fg=this.ctx;fg.save();fg.translate(this.originX,this.originY);fg.scale(scale/100,scale/100);for(const e of this.fifthEffects){if(e.kind==='fifth-field')drawFifthGround(fg,e,this.time*10,.8);drawFifth(fg,{...e,targetX:this.boss.x*100,targetY:this.boss.z*100},this.time*10,.85);}fg.restore();
 for(const s of this.shots)fx(4,s.x,s.z,1.3,Math.atan2(s.vz,s.vx));
 for(const e of this.effects){if(e.swordRing){const phase=this.time*2.8+e.phase,alpha=Math.min(1,e.left/.12);for(let row=0;row<e.rings;row++){const radius=1.7+(e.outerRadius-.5-1.7)*row/(e.rings-1),offset=row*Math.PI/8;for(let i=0;i<e.count;i++){const angle=i*Math.PI*2/e.count+phase+offset,nextAngle=angle+Math.PI*2/e.count,x=this.player.x+Math.sin(angle)*radius,z=this.player.z+Math.cos(angle)*radius,nextX=this.player.x+Math.sin(nextAngle)*radius,nextZ=this.player.z+Math.cos(nextAngle)*radius,pt=this.screen(x,z),heading=Math.atan2(nextZ-z,nextX-x)+Math.PI/2;this.drawCell(this.assets[4],0,0,1,1,pt.x,pt.y,e.swordLength*.5*scale,e.swordLength*scale,heading,alpha);}}continue;}if(e.red){const age=e.max-e.left,t=Math.min(1,age/.22),x=e.fromX+(e.toX-e.fromX)*t,z=e.fromZ+(e.toZ-e.fromZ)*t,pt=this.screen(x,z),frame=age<.08?0:age<.16?1:age<.26?2:3;this.drawCell(this.assets[3],frame,0,4,1,pt.x,pt.y,5.5*scale,3.8*scale,e.angle+Math.PI,Math.min(1,e.left/.18));continue;}const pos=e.mesh.position,id=e.art??(e.orbit?3:e.v?5:e.rise===4?2:e.spin?3:0),size=e.artSize??(e.v?.8:e.orbit?9:e.rise===4?4.8:e.mesh.geometry?.parameters.outerRadius?e.mesh.geometry.parameters.outerRadius*2:4);fx(id,pos.x,pos.z,size,e.orbit?this.time*3:e.artAngle||0,Math.min(1,e.left/e.max*2));}
 if(this.dash)fx(7,this.player.x,this.player.z,3.3,Math.atan2(this.dash.z,this.dash.x));
 for(let i=this.floaters.length-1;i>=0;i--){const f=this.floaters[i],pt=this.screen(f.x,f.z);f.el.style.left=pt.x+'px';f.el.style.top=(pt.y-45-(1-f.left/.8)*35)+'px';f.el.style.opacity=Math.max(0,f.left/.8);if(f.left<=0){f.el.remove();this.floaters.splice(i,1);}}
 }
 loop(now){if(!this.running)return;this.frame=requestAnimationFrame(t=>this.loop(t));const dt=Math.min(.035,(now-this.previous)/1000);this.previous=now;if(!this.paused){this.update(dt);for(const f of this.floaters)f.left-=dt;}if(this.running){const follow=1-Math.exp(-dt*7);this.camX+=(this.player.x-this.camX)*follow;this.camZ+=(this.player.z-2.5-this.camZ)*follow;this.originX=this.width/2-this.camX*this.scale;this.originY=this.height*.46-this.camZ*this.scale;this.originX+=Math.sin(this.time*87)*this.shake*this.scale*.08;this.originY+=Math.cos(this.time*79)*this.shake*this.scale*.06;this.drawArt();}}
 remove(root){root.traverse(m=>{if(m.geometry)m.geometry.dispose();if(m.material&&!Object.values(this.materials).includes(m.material))m.material.dispose();});root.removeFromParent();}
 clearTransient(){for(const e of this.effects)this.remove(e.mesh);for(const s of this.shots)this.remove(s.mesh);for(const m of this.cast?.marks||[])this.remove(m);for(const f of this.floaters)f.el.remove();this.effects=[];this.shots=[];this.floaters=[];this.cast=null;this.bossCharge=null;this.dash=null;}
 dispose(){if(!this.running)return;this.running=false;cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();for(const fn of this.listeners)fn();this.clearTransient();const geos=new Set(),mats=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)mats.add(o.material);});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());this.renderer.dispose();this.renderer.forceContextLoss();this.host.remove();document.body.style.overflow=this.opts.oldOverflow;}
}
