import {towerArena} from './tower-client.mjs?v=priest-potential-83';
import {CLASS_SKILLS,SECOND_SKILLS,beginCombatSkill,stepCombatSkills} from './combat-skills.mjs?v=priest-potential-83';
import {THIRD_SKILLS,beginThird,stepThird,firstJobUnlocked} from './advancement.mjs?v=priest-potential-83';
import {FOURTH_SKILLS,beginFourth,stepFourth} from './fourth-job.mjs?v=priest-potential-83';
const SKILLS=[CLASS_SKILLS.warrior,SECOND_SKILLS.warrior,THIRD_SKILLS.warrior,FOURTH_SKILLS.warrior];
// Administrator-only, reward-free local 3D combat laboratory.
let current=null;
export function closeWarriorLab(){current?.dispose();current=null;}
export async function openWarriorLab({getState,onClose,sound=()=>{}}){
 const account=getState();
 if(!account?.isAdmin||account.classId!=='warrior')throw Error('관리자 전사만 입장할 수 있습니다.');
 if(account.battle||account.coopRoom||account.partyRoom)throw Error('진행 중인 전투를 끝내고 입장해 주세요.');
 closeWarriorLab();
 const host=document.createElement('section');host.className='wl-overlay';host.setAttribute('aria-label','전사 3D 테스트 전투');
 host.innerHTML=`<div class="wl-stage"></div><div class="wl-head"><small>관리자 전용 · 전사 · 연습</small><strong>잿불 성채의 파수꾼</strong><div class="wl-bar"><i data-hp="boss"></i></div><small data-wl="bossinfo"></small><div class="wl-bar-row"><span>전사</span><div class="wl-bar wl-player"><i data-hp="player"></i></div><span data-wl="hp"></span></div></div><button class="wl-close" aria-label="전투 나가기">나가기</button><div class="wl-notice" aria-live="polite"></div><div class="wl-joystick" aria-label="이동 조이스틱"><div class="wl-stick"></div></div><div class="wl-keys"><div class="wl-skill-bar">${SKILLS.map((sk,i)=>`<button data-wl="skill${i+1}" title="${sk.description}">${sk.name}<small>${['K','L','I','O'][i]} · ${sk.cooldown}초</small></button>`).join('')}</div><div class="wl-core-actions"><button data-wl="dash">회피<small>Space</small></button><button data-wl="attack">공격<small>J · 길게 누르기</small></button></div></div><div class="wl-help">이동 WASD / 방향키 · 검격 J · 스킬 1–4 · 회피 Space</div><div class="wl-result" hidden><div class="wl-result-card"><h2></h2><p></p><button data-wl="retry">다시 도전</button><button data-wl="leave">나가기</button></div></div><div class="wl-loading">성채에 입장하는 중…</div>`;
 const native=document.createElement('div');native.className='tower-play wl-native-controls';const template=document.createElement('template');template.innerHTML=towerArena({floor:1,classId:'warrior',runId:'lab-controls',power:{firstJob:firstJobUnlocked(account),advancement:account.advancement||0},advanced:(account.advancement||0)>=1,third:(account.advancement||0)>=2});const controls=template.content.querySelector('.tower-controls');native.append(controls);host.querySelector('.wl-joystick').remove();host.querySelector('.wl-keys').replaceWith(native);const joystick=controls.querySelector('.tower-stick');joystick.setAttribute('data-wl-joystick','');joystick.removeAttribute('id');const knob=joystick.querySelector('i');knob.setAttribute('data-wl-knob','');knob.removeAttribute('id');joystick.style.backgroundImage="url('./lab-art/control-joystick-v2.webp')";joystick.style.backgroundSize='100% 100%';knob.style.backgroundImage="url('./lab-art/control-knob-v2.webp')";knob.style.backgroundSize='100% 100%';const actions={'1':'attack','4':'dash','8':'skill1','2':'skill2','16':'skill3','32':'skill4'};for(const button of controls.querySelectorAll('[data-tower-button]')){const kind=actions[button.dataset.towerButton];button.dataset.wl=kind;button.removeAttribute('data-tower-button');button.querySelectorAll('i').forEach(i=>i.remove());button.style.backgroundImage="url('./lab-art/control-"+(kind==='attack'?'attack':kind==='dash'?'dash':'skill')+"-v2.webp')";button.style.backgroundSize='100% 100%';}document.body.append(host);const oldOverflow=document.body.style.overflow;document.body.style.overflow='hidden';
 let abandoned=false;
 const placeholder={dispose(){abandoned=true;host.remove();document.body.style.overflow=oldOverflow;}};current=placeholder;
 host.querySelector('.wl-close').onclick=()=>{closeWarriorLab();onClose?.();};
 try{
  const T=await import('./vendor/three/three.module.min.js');
  const assets=[];
  if(abandoned)return;
  if(!getState()?.isAdmin||getState()?.classId!=='warrior'){closeWarriorLab();return;}
  current=new Arena(T,host,{getState,onClose,sound,oldOverflow,assets});
  host.querySelector('.wl-loading').remove();
 }catch(e){if(abandoned)return;host.querySelector('.wl-loading').textContent='3D 화면을 열지 못했습니다. 나가기를 눌러 다시 시도해 주세요.';host.querySelector('.wl-close').style.zIndex=5;throw e;}
}
class Arena{
 constructor(T,host,opts){this.T=T;this.host=host;this.opts=opts;this.listeners=[];this.keys=new Set();this.move={x:0,z:0};this.attackHeld=false;this.running=true;this.paused=false;this.effects=[];this.shots=[];this.hazards=[];this.floaters=[];this.time=0;this.pattern=0;this.shake=0;this.combo=0;this.lastCombo=-5;
 this.scene=new T.Scene();this.scene.background=new T.Color('#171d23');this.scene.fog=new T.Fog('#171d23',42,85);
 this.camera=new T.PerspectiveCamera(43,1,.1,110);this.renderer=new T.WebGLRenderer({antialias:true,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));this.renderer.outputColorSpace=T.SRGBColorSpace;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.15;this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;host.querySelector('.wl-stage').append(this.renderer.domElement);
 this.scene.add(new T.HemisphereLight(0xb9cbd9,0x302921,1.3));const sun=new T.DirectionalLight(0xffe2bc,3);sun.position.set(-12,25,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-25,right:25,top:35,bottom:-35,near:.5,far:80});sun.shadow.bias=-.0003;sun.shadow.normalBias=.035;this.scene.add(sun);const rim=new T.DirectionalLight(0x819cb4,1.4);rim.position.set(12,10,-14);this.scene.add(rim);
 this.materials={};this.obstacles=[{x:-11.4,z:-10,r:1},{x:11.4,z:-10,r:1},{x:-11.4,z:10,r:1},{x:11.4,z:10,r:1}];this.buildArena();this.player=this.character(false);this.boss=this.character(true);this.scene.add(this.player.root,this.boss.root);this.reset();this.bind();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(host);this.resize();this.previous=performance.now();this.frame=requestAnimationFrame(t=>this.loop(t));
 }
 mat(color,metal=.05,rough=.65){const key=color+':'+metal+':'+rough;return this.materials[key]??=new this.T.MeshStandardMaterial({color,metalness:metal,roughness:rough});}
 mesh(geo,color,parent,pos=[0,0,0],metal=.05){const m=new this.T.Mesh(geo,this.mat(color,metal));m.position.set(...pos);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 box(w,h,d,color,parent,pos,metal){return this.mesh(new this.T.BoxGeometry(w,h,d),color,parent,pos,metal);}
 sphere(r,color,parent,pos){return this.mesh(new this.T.SphereGeometry(r,16,12),color,parent,pos);}
 buildArena(){const T=this.T;
 // Fine stone grain stays in world space rather than stretching a background image.
 const textureCanvas=document.createElement('canvas');textureCanvas.width=textureCanvas.height=256;const ctx=textureCanvas.getContext('2d');const pixels=ctx.createImageData(256,256);let seed=71;for(let i=0;i<pixels.data.length;i+=4){seed=(seed*1664525+1013904223)>>>0;const v=105+(seed>>>24)*.18;pixels.data[i]=v;pixels.data[i+1]=v*.96;pixels.data[i+2]=v*.9;pixels.data[i+3]=255;}ctx.putImageData(pixels,0,0);const stone=new T.CanvasTexture(textureCanvas);stone.wrapS=stone.wrapT=T.RepeatWrapping;stone.repeat.set(2,2);stone.colorSpace=T.SRGBColorSpace;stone.anisotropy=Math.min(8,this.renderer.capabilities.getMaxAnisotropy());this.stoneTexture=stone;
 this.box(42,.5,62,'#353634',this.scene,[0,-.38,0]);const tileGeo=new T.BoxGeometry(1.96,.14,1.96);const tileMat=new T.MeshStandardMaterial({map:stone,bumpMap:stone,bumpScale:.06,roughness:.94,color:0x9c9b94});this.materials.stone=tileMat;for(let x=-20;x<=20;x+=2)for(let z=-30;z<=30;z+=2){const m=new T.Mesh(tileGeo,tileMat);m.position.set(x,-.06,z);m.receiveShadow=true;this.scene.add(m);}
 for(const z of [-31,31])for(let x=-20;x<=20;x+=2){this.box(1.97,3,1,'#535450',this.scene,[x,1.3,z]);this.box(2,.22,1.2,'#74746d',this.scene,[x,2.91,z]);}
 for(const x of [-21,21])for(let z=-30;z<=30;z+=2){this.box(1,3,1.97,'#535450',this.scene,[x,1.3,z]);this.box(1.2,.22,2,'#74746d',this.scene,[x,2.91,z]);}
 this.obstacles=[{x:-11.4,z:-10,r:1},{x:11.4,z:-10,r:1},{x:-11.4,z:10,r:1},{x:11.4,z:10,r:1}];for(const o of this.obstacles){this.box(2.3,.3,2.3,'#55544f',this.scene,[o.x,.1,o.z]);this.mesh(new T.CylinderGeometry(.8,1,3.6,24),'#74756e',this.scene,[o.x,1.95,o.z]);for(const y of [.45,3.6])this.mesh(new T.CylinderGeometry(1.08,1.08,.22,24),'#96938a',this.scene,[o.x,y,o.z]);this.mesh(new T.CylinderGeometry(.7,.4,.5,24),'#292b2e',this.scene,[o.x,4,o.z],.7);const flame=this.mesh(new T.SphereGeometry(.22,12,8),'#ffc16b',this.scene,[o.x,4.3,o.z]);flame.material=this.mat('#ffb052');flame.material.emissive=new T.Color('#ff6e20');flame.material.emissiveIntensity=3;const light=new T.PointLight(0xffa352,16,10,2);light.position.set(o.x,4.5,o.z);this.scene.add(light);}
 }
 character(boss){const T=this.T,root=new T.Group(),body=new T.Group();root.add(body);const scale=boss?1.225:.7;root.scale.setScalar(scale);const steel=boss?'#454344':'#78848b',gold=boss?'#91714a':'#a28d63',cloth=boss?'#4a2024':'#283944';
 const torso=this.mesh(new T.CylinderGeometry(.47,.36,.7,24),steel,body,[0,1.2,0],.5);this.box(.22,.43,.12,gold,body,[0,1.2,.43],.7);this.mesh(new T.CylinderGeometry(.39,.52,.4,24),cloth,body,[0,.75,0]);
 const head=this.sphere(.33,boss?'#655163':'#e6b793',body,[0,1.83,0]);const helm=this.mesh(new T.SphereGeometry(.37,16,12,0,Math.PI*2,0,Math.PI*.57),steel,body,[0,1.88,0],.5);this.box(.7,.15,.16,steel,body,[0,1.88,.25],.55);this.box(.57,.07,.05,boss?'#ff6b42':'#173548',body,[0,1.84,.355]);this.box(.09,.45,.09,gold,body,[0,2.02,.34],.6);
 if(boss){for(const sign of [-1,1]){const horn=this.mesh(new T.ConeGeometry(.13,.63,8),gold,body,[sign*.41,2.1,0]);horn.rotation.z=-sign*.65;}}else{const plume=this.mesh(new T.CapsuleGeometry(.13,.5,4,8),'#ba3749',body,[0,2.22,-.1]);plume.rotation.x=.8;}
 const cape=this.box(.69,.98,.12,cloth,body,[0,1.12,-.38]);cape.rotation.x=-.18;
 const arms=[],legs=[];for(const sign of [-1,1]){const leg=new T.Group();leg.position.set(sign*.23,.72,0);body.add(leg);this.mesh(new T.CapsuleGeometry(.15,.33,4,8),'#263346',leg,[0,-.27,0]);this.box(.29,.25,.44,steel,leg,[0,-.58,.08],.4);legs.push(leg);
 const arm=new T.Group();arm.position.set(sign*.56,1.47,0);body.add(arm);this.sphere(.25,steel,arm,[0,-.03,0]);this.mesh(new T.CapsuleGeometry(.12,.31,4,8),cloth,arm,[0,-.32,0]);this.sphere(.14,gold,arm,[0,-.58,0]);arms.push(arm);}
 const weapon=new T.Group();arms[1].add(weapon);weapon.position.set(0,-.58,.12);this.mesh(new T.CylinderGeometry(.065,.065,.35,8),'#573846',weapon,[0,.02,0]);this.box(.68,.1,.12,gold,weapon,[0,.24,0],.7);const blade=this.box(boss?.37:.19,boss?1.25:1.08,.065,boss?'#c38671':'#def4ff',weapon,[0,.87,0],.7);const tip=this.mesh(new T.ConeGeometry(boss?.24:.14,.36,4),boss?'#ffe0aa':'#effbff',weapon,[0,1.62,0],.65);tip.rotation.y=Math.PI/4;
 const shield=this.mesh(new T.CylinderGeometry(.36,.36,.13,8),steel,arms[0],[0,-.36,.16],.5);shield.rotation.x=Math.PI/2;this.sphere(.13,gold,arms[0],[0,-.36,.27]);
 return {root,body,arms,legs,cape,weapon,x:0,z:0,hp:boss?6000:100,max:boss?6000:100,r:boss?.95:.48,attack:0,inv:0,hit:0,walk:0,angle:0};
 }
 reset(){this.clearTransient();this.time=0;this.pattern=0;this.nextPattern=2;this.cast=null;this.enraged=false;this.done=false;this.combo=0;this.lastCombo=-5;this.cooldowns={attack:0,dash:0};this.skillActor={id:'warrior',classId:'warrior',x:0,y:0,power:{firstJob:firstJobUnlocked(this.opts.getState()),advancement:this.opts.getState().advancement||0},advancement:this.opts.getState().advancement||0};Object.assign(this.player,{x:0,z:7,hp:100,inv:1,attack:0,hit:0,angle:Math.PI});Object.assign(this.boss,{x:0,z:-4,hp:6000,attack:0,hit:0,angle:0});this.dash=null;this.camX=this.player.x;this.camZ=this.player.z-2.5;this.host.querySelector('.wl-result').hidden=true;this.keys.clear();this.move={x:0,z:0};this.attackHeld=false;this.notice('벽과 기둥을 이용해 투사체를 피하세요');this.updateHUD();}
 bind(){const listen=(el,type,fn,options)=>{el.addEventListener(type,fn,options);this.listeners.push(()=>el.removeEventListener(type,fn,options));};
 this.host.querySelector('.wl-close').onclick=()=>this.leave();this.host.querySelector('[data-wl="leave"]').onclick=()=>this.leave();this.host.querySelector('[data-wl="retry"]').onclick=()=>this.reset();
 const joy=this.host.querySelector('[data-wl-joystick]'),stick=joy.querySelector('[data-wl-knob]');let pointer=null;
 const update=e=>{const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dz=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dz),max=parseFloat(getComputedStyle(joy).getPropertyValue('--stick-travel'))||29,k=len>max?max/len:1;stick.style.transform=`translate(${dx*k}px,${dz*k}px)`;this.move={x:dx*k/max,z:dz*k/max};};
 listen(joy,'pointerdown',e=>{if(pointer!==null)return;pointer=e.pointerId;joy.setPointerCapture(pointer);update(e);e.preventDefault();});listen(joy,'pointermove',e=>{if(e.pointerId===pointer)update(e);});const release=e=>{if(e.pointerId!==pointer)return;pointer=null;this.move={x:0,z:0};stick.style.transform='';};listen(joy,'pointerup',release);listen(joy,'pointercancel',release);listen(joy,'lostpointercapture',release);
 for(const kind of ['attack','skill1','skill2','skill3','skill4','dash']){const button=this.host.querySelector(`[data-wl="${kind}"]`);listen(button,'pointerdown',e=>{e.preventDefault();button.setPointerCapture(e.pointerId);if(kind==='attack')this.attackHeld=true;this.skill(kind);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])listen(button,ev,()=>{if(kind==='attack')this.attackHeld=false;});}
 listen(window,'keydown',e=>{if(!['KeyW','KeyA','KeyS','KeyD','ArrowUp','ArrowDown','ArrowLeft','ArrowRight','KeyJ','KeyK','KeyL','KeyI','KeyO','Digit1','Digit2','Digit3','Digit4','Space','Escape'].includes(e.code))return;e.preventDefault();if(e.code==='Escape'){this.leave();return;}this.keys.add(e.code);if(e.code==='KeyJ')this.attackHeld=true;if(!e.repeat&&['KeyK','KeyL','KeyI','KeyO'].includes(e.code))this.skill('skill'+(['KeyK','KeyL','KeyI','KeyO'].indexOf(e.code)+1));if(!e.repeat&&/^Digit[1-4]$/.test(e.code))this.skill('skill'+e.code.slice(-1));if(!e.repeat&&e.code==='Space')this.skill('dash');});listen(window,'keyup',e=>{this.keys.delete(e.code);if(e.code==='KeyJ')this.attackHeld=false;});
 const clear=()=>{this.keys.clear();this.attackHeld=false;this.move={x:0,z:0};pointer=null;stick.style.transform='';};listen(window,'blur',()=>{clear();this.paused=true;});listen(window,'focus',()=>{this.paused=document.hidden;this.previous=performance.now();});listen(document,'visibilitychange',()=>{clear();this.paused=document.hidden;this.previous=performance.now();});listen(this.renderer.domElement,'webglcontextlost',e=>{e.preventDefault();this.paused=true;this.finish(false,'그래픽 연결이 중단됐습니다. 나간 뒤 다시 입장해 주세요.');});
 }
 resize(){const w=this.host.clientWidth,h=this.host.clientHeight;this.renderer.setSize(w,h,false);this.width=w;this.height=h;this.camera.aspect=w/h;this.camera.updateProjectionMatrix();}
 leave(){closeWarriorLab();this.opts.onClose?.();}
 notice(text){this.host.querySelector('.wl-notice').textContent=text;}
 skill(kind){if(this.done||this.paused||!this.running||(this.cooldowns[kind]||0)>this.time)return;const p=this.player,b=this.boss;let dx=b.x-p.x,dz=b.z-p.z,len=Math.hypot(dx,dz)||1;
 if(kind.startsWith('skill')){const slot=Number(kind.slice(-1)),tick=Math.floor(this.time*10),a=this.skillActor,target={id:'guardian',x:b.x*100,y:b.z*100};a.x=p.x*100;a.y=p.z*100;const ok=slot<=2?beginCombatSkill(a,target,tick,slot):slot===3?beginThird(a,target,tick):beginFourth(a,target,tick);if(ok){p.angle=Math.atan2(dx,dz);p.attack=.5;p.attackDuration=.5;this.notice(SKILLS[slot-1].name);this.opts.sound('warrior-skill-'+slot);}return;}
 if(kind==='attack'){this.cooldowns.attack=this.time+.9;const move=this.direction();if(len<3.5)p.angle=Math.atan2(dx,dz);else if(Math.hypot(move.x,move.z)>.05)p.angle=Math.atan2(move.x,move.z);p.attack=.32;p.attackDuration=.32;const forward={x:Math.sin(p.angle),z:Math.cos(p.angle)};this.arc({x:p.x+forward.x*.75,z:p.z+forward.z*.75},0xc5eeff,1.6,.3,p.angle,1.8);const effect=this.effects.at(-1);effect.art=0;effect.artSize=3.2;effect.artAngle=Math.atan2(forward.z,forward.x)+Math.PI;if(len<2.925&&(dx/len*forward.x+dz/len*forward.z)>.35){this.hurt(b,140);this.spark(b.x,1.6,b.z,0xffe4a6,10);}this.opts.sound('warrior-attack');}
 if(kind==='dash'){this.cooldowns.dash=this.time+3;const movement=this.direction();if(Math.hypot(movement.x,movement.z)>.1){dx=movement.x;dz=movement.z;len=Math.hypot(dx,dz);}this.dash={x:dx/len,z:dz/len,left:.22};p.angle=Math.atan2(dx,dz);p.inv=.38;this.opts.sound('battle-dash');}
 }
 stepSkills(){const a=this.skillActor,p=this.player,b=this.boss,tick=Math.floor(this.time*10),target={id:'guardian',x:b.x*100,y:b.z*100};a.x=p.x*100;a.y=p.z*100;
 const hit=scale=>{if(!this.done)this.hurt(b,Math.round(140*scale));};const emit=e=>{const x=e.x/100,z=e.y/100;if(e.kind==='third'){this.redSlash(e.fromX/100,e.fromY/100,x,z,e.angle||0);this.opts.sound('warrior-skill-3');return;}if(e.phase==='charge'){this.stamp(6,x,z,3.8,.4);return;}if(e.phase==='pulse'){if(e.final){this.swordBurst(x,z,1,.5);}else{const fromX=e.fromX/100,fromZ=e.fromY/100;this.stamp(0,fromX,fromZ,3.5,.25,Math.atan2(z-fromZ,x-fromX)+Math.PI);this.stamp(1,x,z,5.4,.4);}this.spark(x,.7,z,e.final?0xffdf92:0xc5eaff,8);}if(e.kind==='fourth'){this.swordOrbit(p,e.pulse);}};
 stepCombatSkills(a,[target],tick,hit,emit);stepThird(a,target,tick,hit,emit);// Scale coordinates only for the lab's fourth-skill geometry; retain its shared damage timeline.
 const saved={x:a.x,y:a.y,castX:a.fourthCast?.x,castY:a.fourthCast?.y};a.x/=2;a.y/=2;if(a.fourthCast){a.fourthCast.x/=2;a.fourthCast.y/=2;}stepFourth(a,{...target,x:target.x/2,y:target.y/2},tick,hit,e=>emit({...e,x:e.x*2,y:e.y*2,size:e.size*2}));a.x=saved.x;a.y=saved.y;if(a.fourthCast){a.fourthCast.x=saved.castX;a.fourthCast.y=saved.castY;}
 // First-job impact follows the same 0.3-second damage pulse as the existing game.
 if(a.firstCast&&tick>=a.firstCast.start+2&&!a.firstCast.labShown){a.firstCast.labShown=true;this.stamp(1,a.firstCast.target.x/100,a.firstCast.target.y/100,7.2,.6);this.stamp(5,a.firstCast.target.x/100,a.firstCast.target.y/100,5.2,.45);this.shake=.12;}
 }
 stamp(art,x,z,size,life,angle=0){if(art===6){this.arc({x,z},0x8cbde0,size/2,life,0,Math.PI*2);return;}if(art===0){this.arc({x,z},0xd5e8ed,size/2,life,Math.PI/2-angle,2.1);return;}this.spark(x,.6,z,art===5?0xffc68a:0xc1ddeb,art===5?18:12);if(art===1)this.arc({x,z},0x9cbaca,size*.32,life,0,Math.PI*2);}
 redSlash(fromX,fromZ,toX,toZ,fan){const angle=Math.atan2(toX-fromX,toZ-fromZ)+fan*.12;const mesh=new this.T.Group();mesh.position.set(fromX,.9,fromZ);const blade=new this.T.Mesh(new this.T.RingGeometry(.9,1.12,40,1,0,2.1),new this.T.MeshBasicMaterial({color:0xe04c35,transparent:true,opacity:.8,side:this.T.DoubleSide,depthWrite:false}));blade.rotation.x=-Math.PI/2;blade.rotation.z=-angle;mesh.add(blade);this.scene.add(mesh);this.effects.push({mesh,left:.55,max:.55,v:{x:(toX-fromX)/.24,y:0,z:(toZ-fromZ)/.24},slash:true});}
 spectralSword(){const T=this.T,root=new T.Group();this.box(.11,1.45,.045,'#c9d9e0',root,[0,.4,0],.9);this.mesh(new T.ConeGeometry(.08,.25,4),'#e5edf0',root,[0,1.25,0],.9);this.box(.5,.065,.1,'#a58e63',root,[0,-.32,0],.75);this.mesh(new T.CylinderGeometry(.04,.04,.32,8),'#332c29',root,[0,-.5,0]);return root;}
 swordBurst(x,z,count,life){const root=this.spectralSword();root.position.set(x,3,z);this.scene.add(root);this.effects.push({mesh:root,left:life,max:life,rise:-6});}
 swordOrbit(p,pulse){const root=new this.T.Group();root.position.set(p.x,.9,p.z);for(let i=0;i<32;i++){const angle=i*Math.PI*2/32,sword=this.spectralSword();sword.scale.setScalar(.7);sword.position.set(Math.sin(angle)*10.8,0,Math.cos(angle)*10.8);sword.rotation.set(Math.PI/2,0,-angle);root.add(sword);}root.rotation.y=pulse*.32;this.scene.add(root);this.effects.push({mesh:root,left:.38,max:.38,orbit:2.8,follow:true});}
 direction(){let x=this.move.x,z=this.move.z;x+=(this.keys.has('KeyD')||this.keys.has('ArrowRight')?1:0)-(this.keys.has('KeyA')||this.keys.has('ArrowLeft')?1:0);z+=(this.keys.has('KeyS')||this.keys.has('ArrowDown')?1:0)-(this.keys.has('KeyW')||this.keys.has('ArrowUp')?1:0);const n=Math.hypot(x,z);return n>1?{x:x/n,z:z/n}:{x,z};}
 moveActor(a,dx,dz){a.x=Math.max(-19.4+a.r,Math.min(19.4-a.r,a.x+dx));a.z=Math.max(-29.3+a.r,Math.min(29.3-a.r,a.z+dz));for(const o of this.obstacles){const x=a.x-o.x,z=a.z-o.z,n=Math.hypot(x,z),r=a.r+o.r;if(n<r){a.x=o.x+(n?x/n:1)*r;a.z=o.z+(n?z/n:0)*r;}}}
 hurt(a,n){if(a===this.player&&a.inv>0)return;a.hp=Math.max(0,a.hp-n);a.hit=.18;if(a===this.player){a.inv=.65;this.shake=.18;this.opts.sound('battle-hurt');}this.floating(a,n);if(a.hp<=0)this.finish(a===this.boss);}
 finish(won,custom){if(this.done)return;this.done=true;this.attackHeld=false;this.keys.clear();this.move={x:0,z:0};this.notice(won?'파수꾼 처치':'전투 종료');const panel=this.host.querySelector('.wl-result');panel.hidden=false;panel.querySelector('h2').textContent=won?'성채 정복':'다시 도전';panel.querySelector('p').textContent=custom||`${Math.floor(this.time)}초 전투 · ${won?'파수꾼을 쓰러뜨렸습니다.':'공격 예고를 보고 돌진으로 피하세요.'} 관리자 연습 전투로 재화와 도전 횟수는 소비되지 않으며 보상은 없습니다.`;panel.querySelector('[data-wl="retry"]').hidden=!!custom;this.opts.sound(won?'battle-victory':'battle-defeat');}
 floating(a,n){const el=document.createElement('b');el.textContent='−'+n;Object.assign(el.style,{position:'absolute',color:a===this.player?'#ff8585':'#fff1ab',fontSize:a===this.player?'20px':'24px',fontWeight:'900',textShadow:'0 2px 3px #000',pointerEvents:'none',transform:'translate(-50%,-50%)'});this.host.append(el);this.floaters.push({el,x:a.x,z:a.z,y:a===this.player?2.4:3.7,left:.8});}
 arc(a,color,r,life,angle,length){const T=this.T,mat=new T.MeshBasicMaterial({color,transparent:true,opacity:.85,side:T.DoubleSide,depthWrite:false});const mesh=new T.Mesh(new T.RingGeometry(r-.23,r,40,1,0,length),mat);mesh.rotation.x=-Math.PI/2;mesh.rotation.z=-(angle+Math.PI/2+length/2);mesh.position.set(a.x,.8,a.z);this.scene.add(mesh);this.effects.push({mesh,left:life,max:life,spin:length>6?10:0,rise:.1});}
 spark(x,y,z,color,count=12){const T=this.T;for(let i=0;i<count;i++){const m=new T.Mesh(new T.IcosahedronGeometry(.07,0),new T.MeshBasicMaterial({color,transparent:true}));m.position.set(x,y,z);this.scene.add(m);this.effects.push({mesh:m,left:.45,max:.45,v:{x:(Math.random()-.5)*7,y:Math.random()*5,z:(Math.random()-.5)*7}});}}
 ring(x,z,r,color,opacity=.3){const T=this.T,m=new T.Mesh(new T.CircleGeometry(r,48),new T.MeshBasicMaterial({color,transparent:true,opacity,side:T.DoubleSide,depthWrite:false}));m.rotation.x=-Math.PI/2;m.position.set(x,.13,z);this.scene.add(m);return m;}
 startPattern(){const b=this.boss,p=this.player,k=this.pattern++%4;const dx=p.x-b.x,dz=p.z-b.z,angle=Math.atan2(dx,dz);b.angle=angle;
 if(k===0){this.notice('화염 산탄 · 기둥 뒤로 피하세요');this.cast={kind:'fan',left:.85,angle,marks:[this.ring(b.x,b.z,1.8,0xff874a)]};}
 if(k===1){this.notice('내려찍기 · 붉은 원에서 벗어나세요');this.cast={kind:'slam',left:1.05,x:p.x,z:p.z,marks:[this.ring(p.x,p.z,2.8,0xff4444)]};}
 if(k===2){this.notice('파수꾼 돌진 · 옆으로 피하세요');const T=this.T,mark=new T.Mesh(new T.PlaneGeometry(2.5,10),new T.MeshBasicMaterial({color:0xff614c,transparent:true,opacity:.32,side:T.DoubleSide,depthWrite:false}));mark.rotation.x=-Math.PI/2;mark.rotation.z=-angle;mark.position.set(b.x+Math.sin(angle)*5,.12,b.z+Math.cos(angle)*5);this.scene.add(mark);this.cast={kind:'charge',left:1,angle,marks:[mark]};}
 if(k===3){this.notice('화염 파동 · 틈으로 이동하거나 돌진하세요');this.cast={kind:'nova',left:1.1,marks:[this.ring(b.x,b.z,3.2,0xff874a)]};}
 this.opts.sound('boss-warning');}
 releasePattern(c){const b=this.boss,p=this.player;for(const m of c.marks)this.remove(m);this.cast=null;b.attack=.6;this.nextPattern=this.time+(this.enraged?1.8:2.7);
 if(c.kind==='fan'){for(let i=-2;i<=2;i++)this.projectile(b.x,b.z,c.angle+i*.23,8.5,12);if(this.enraged)for(let i=-1;i<=1;i++)this.projectile(b.x,b.z,c.angle+i*.4,6.5,12);}
 if(c.kind==='slam'){this.spark(c.x,.3,c.z,0xffae50,24);this.arc({x:c.x,z:c.z},0xff9c42,2.8,.5,0,Math.PI*2);if(Math.hypot(p.x-c.x,p.z-c.z)<2.8+p.r)this.hurt(p,24);this.shake=.15;this.opts.sound('battle-crit');}
 if(c.kind==='charge')this.bossCharge={x:Math.sin(c.angle),z:Math.cos(c.angle),left:.7,hit:false};
 if(c.kind==='nova'){const offset=this.pattern*.41;for(let i=0;i<14;i++)if(i!==3&&i!==4)this.projectile(b.x,b.z,offset+i*Math.PI*2/14,5.4,14);}
 }
 projectile(x,z,angle,speed,damage){const T=this.T,root=new T.Group();root.position.set(x,.65,z);const orb=new T.Mesh(new T.IcosahedronGeometry(.28,1),new T.MeshStandardMaterial({color:0xffd176,emissive:0xff681d,emissiveIntensity:2,roughness:.2}));root.add(orb);const tail=new T.Mesh(new T.ConeGeometry(.22,.95,8),new T.MeshBasicMaterial({color:0xff732e,transparent:true,opacity:.65}));tail.rotation.x=Math.PI/2;tail.position.z=-.5;root.add(tail);root.rotation.y=angle;this.scene.add(root);this.shots.push({mesh:root,x,z,vx:Math.sin(angle)*speed,vz:Math.cos(angle)*speed,left:5,damage});}
 update(dt){const p=this.player,b=this.boss;this.time+=dt;if(!this.opts.getState()?.isAdmin||this.opts.getState()?.classId!=='warrior'){this.leave();return;}for(const a of [p,b]){a.inv=Math.max(0,a.inv-dt);a.attack=Math.max(0,a.attack-dt);a.hit=Math.max(0,a.hit-dt);}this.shake=Math.max(0,this.shake-dt);
 if(!this.done){let dir=this.direction();if(this.dash){this.moveActor(p,this.dash.x*21*dt,this.dash.z*21*dt);this.dash.left-=dt;if(this.dash.left<=0)this.dash=null;}else{this.moveActor(p,dir.x*4.6*dt,dir.z*4.6*dt);if(Math.hypot(dir.x,dir.z)>.05)p.angle=Math.atan2(dir.x,dir.z);}p.walk+=Math.hypot(dir.x,dir.z)*dt*10;
 if(this.attackHeld)this.skill('attack');this.stepSkills();if(!this.enraged&&b.hp<=b.max*.5){this.enraged=true;this.notice('분노 · 공격 간격이 빨라집니다');this.opts.sound('boss-warning');}
 if(this.bossCharge){const c=this.bossCharge;this.moveActor(b,c.x*13*dt,c.z*13*dt);c.left-=dt;if(!c.hit&&Math.hypot(b.x-p.x,b.z-p.z)<b.r+p.r){c.hit=true;this.hurt(p,26);}if(c.left<=0)this.bossCharge=null;}
 else if(this.cast){this.cast.left-=dt;for(const m of this.cast.marks)m.material.opacity=.22+.16*Math.sin(this.time*14);if(this.cast.left<=0)this.releasePattern(this.cast);}
 else if(this.time>=this.nextPattern)this.startPattern();
 else{const dx=p.x-b.x,dz=p.z-b.z,n=Math.hypot(dx,dz)||1;b.angle=Math.atan2(dx,dz);if(n>3.2){this.moveActor(b,dx/n*1.2*dt,dz/n*1.2*dt);b.walk+=dt*5;}}
 const distance=Math.hypot(p.x-b.x,p.z-b.z),min=p.r+b.r;if(distance<min){this.moveActor(p,(p.x-b.x)/(distance||1)*(min-distance),(p.z-b.z)/(distance||1)*(min-distance));}
 }
 for(let i=this.shots.length-1;i>=0;i--){const s=this.shots[i];if(!this.done){s.x+=s.vx*dt;s.z+=s.vz*dt;}s.left-=dt;s.mesh.position.set(s.x,.65+Math.sin(this.time*12)*.04,s.z);s.mesh.children[0].rotation.y+=dt*5;let remove=s.left<=0||Math.abs(s.x)>20||Math.abs(s.z)>30||this.obstacles.some(o=>Math.hypot(s.x-o.x,s.z-o.z)<o.r+.2);if(!this.done&&Math.hypot(s.x-p.x,s.z-p.z)<p.r+.25){this.hurt(p,s.damage);remove=true;}if(remove){this.spark(s.x,.6,s.z,0xffb868,4);this.remove(s.mesh);this.shots.splice(i,1);}}
 for(let i=this.effects.length-1;i>=0;i--){const e=this.effects[i];e.left-=dt;e.mesh.traverse(m=>{if(m.material)m.material.opacity=Math.max(0,e.left/e.max);});if(e.follow){e.mesh.position.x=p.x;e.mesh.position.z=p.z;}if(e.orbit)e.mesh.rotation.y+=e.orbit*dt;if(e.spin)e.mesh.rotation.z+=e.spin*dt;if(e.rise)e.mesh.position.y+=dt*e.rise;if(e.v){if(!e.slash)e.v.y-=10*dt;e.mesh.position.x+=e.v.x*dt;e.mesh.position.y+=e.v.y*dt;e.mesh.position.z+=e.v.z*dt;}if(e.left<=0){this.remove(e.mesh);this.effects.splice(i,1);}}
 for(const a of [p,b])this.animate(a,dt);this.updateHUD();}
 animate(a,dt){a.root.position.set(a.x,0,a.z);const target=a.angle;let delta=Math.atan2(Math.sin(target-a.root.rotation.y),Math.cos(target-a.root.rotation.y));a.root.rotation.y+=delta*Math.min(1,dt*18);const walking=a===this.player?(Math.hypot(this.direction().x,this.direction().z)>.1&&!this.done):(!this.cast&&!this.done&&Math.hypot(a.x-this.player.x,a.z-this.player.z)>3.2);const wave=walking?Math.sin(a.walk)*.52:Math.sin(this.time*2)*.025;a.legs[0].rotation.x=wave;a.legs[1].rotation.x=-wave;a.body.position.y=walking?Math.abs(Math.sin(a.walk))*.05:Math.sin(this.time*2)*.025;a.cape.rotation.x=-.18-wave*.12;a.arms[0].rotation.x=-wave*.45;a.arms[1].rotation.x=a.attack>0?-1.7+Math.sin(a.attack*19)*.9:wave*.45;a.arms[1].rotation.z=a.attack>0?-.6:0;a.body.rotation.z=a.hit>0?Math.sin(a.hit*70)*.13:0;a.root.visible=true;a.body.rotation.x=this.dash&&a===this.player?-.5:walking?.08:0;const phase=1-a.attack/(a.attackDuration||.6);if(a.attack>0){const swing=Math.sin(Math.min(1,phase)*Math.PI);a.body.rotation.y=-.45+swing*.9;a.arms[1].rotation.x=-.4-swing*2.2;a.arms[1].rotation.z=-.3-swing*.75;}else a.body.rotation.y*=Math.exp(-dt*14);}
 updateHUD(){this.host.querySelector('[data-hp="boss"]').style.width=(this.boss.hp/this.boss.max*100)+'%';this.host.querySelector('[data-hp="player"]').style.width=this.player.hp+'%';this.host.querySelector('[data-wl="hp"]').textContent=Math.ceil(this.player.hp)+'/100';this.host.querySelector('[data-wl="bossinfo"]').textContent=Math.ceil(this.boss.hp).toLocaleString()+' / 6,000 · '+(this.enraged?'분노 · ':'')+Math.floor(this.time)+'초';for(const k of ['skill1','skill2','skill3','skill4','dash']){const el=this.host.querySelector(`[data-wl="${k}"]`);const slot=Number(k.slice(-1)),a=this.skillActor,unlocked=k==='dash'||(slot===1?firstJobUnlocked(this.opts.getState()):(this.opts.getState().advancement||0)>=slot-1);const ready=k==='dash'?this.cooldowns.dash:(a[['ultimateReady','skillReady','thirdReady','fourthReady'][slot-1]]||0)/10;const left=Math.max(0,ready-this.time);el.disabled=left>0||this.done||!unlocked;el.querySelector('b').textContent=left>0?left.toFixed(1):'';el.style.setProperty('--cooldown',Math.min(100,left/(k==='dash'?3:SKILLS[slot-1].cooldown)*100)+'%');el.querySelector('small').textContent=!unlocked?'전직 필요':left>0?left.toFixed(1)+'초':k==='dash'?'Space · 준비':['K','L','I','O'][slot-1]+' · 준비';}}

 renderScene(dt){const follow=1-Math.exp(-dt*7);this.camX+=(this.player.x-this.camX)*follow;this.camZ+=(this.player.z-2.5-this.camZ)*follow;const distance=this.camera.aspect<.8?25:21;this.camera.position.set(this.camX,distance*.92,this.camZ+distance*.75);this.camera.lookAt(this.camX,0,this.camZ);if(this.shake>0){this.camera.position.x+=Math.sin(this.time*87)*this.shake*.3;this.camera.position.y+=Math.cos(this.time*79)*this.shake*.2;}this.renderer.render(this.scene,this.camera);for(let i=this.floaters.length-1;i>=0;i--){const f=this.floaters[i],pt=new this.T.Vector3(f.x,f.y+(1-f.left/.8)*.8,f.z).project(this.camera);f.el.style.left=((pt.x*.5+.5)*this.width)+'px';f.el.style.top=((-pt.y*.5+.5)*this.height)+'px';f.el.style.opacity=Math.max(0,f.left/.8);if(f.left<=0){f.el.remove();this.floaters.splice(i,1);}}}
 loop(now){if(!this.running)return;this.frame=requestAnimationFrame(t=>this.loop(t));const dt=Math.min(.035,(now-this.previous)/1000);this.previous=now;if(!this.paused){this.update(dt);for(const f of this.floaters)f.left-=dt;}if(this.running)this.renderScene(dt);}
 remove(root){root.traverse(m=>{if(m.geometry)m.geometry.dispose();if(m.material&&!Object.values(this.materials).includes(m.material))m.material.dispose();});root.removeFromParent();}
 clearTransient(){for(const e of this.effects)this.remove(e.mesh);for(const s of this.shots)this.remove(s.mesh);for(const m of this.cast?.marks||[])this.remove(m);for(const f of this.floaters)f.el.remove();this.effects=[];this.shots=[];this.floaters=[];this.cast=null;this.bossCharge=null;this.dash=null;}
 dispose(){if(!this.running)return;this.running=false;cancelAnimationFrame(this.frame);this.resizeObserver?.disconnect();for(const fn of this.listeners)fn();this.clearTransient();const geos=new Set(),mats=new Set();this.scene.traverse(o=>{if(o.geometry)geos.add(o.geometry);if(o.material)mats.add(o.material);});geos.forEach(g=>g.dispose());mats.forEach(m=>m.dispose());this.stoneTexture?.dispose();this.renderer.dispose();this.renderer.forceContextLoss();this.host.remove();document.body.style.overflow=this.opts.oldOverflow;}
}
